/*
 * Copyright (c) 1995, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's java.awt.Container
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.awt;

// Generated by vaadinx.internal.Generator from java.awt.Container, then hand-finished.

/** Emulator for {@link java.awt.Container}. */
public class Container extends vaadinx.awt.Component {

    // Swing-side child list — authoritative for getComponents/indexing/z-order.
    // Peer DOM is kept in sync but may contain extra peer-internal wrapper elements
    // that must not leak through getComponents().
    private final java.util.List<vaadinx.awt.Component> components = new java.util.ArrayList<>();

    // AWT's layout-manager hook. Wired in per R_infra_not_surface: we copy the original Swing
    // code that notifies the LayoutManager on add/remove/invalidate/pref-etc.,
    // guarded by null so a freshly-constructed Container behaves exactly as
    // today (no manager installed → zero layout-manager calls). Once a real
    // manager lands, every call site is already in place.
    private vaadinx.awt.LayoutManager layoutMgr;

    // Guards the Option-A one-shot WARN: a custom (non-CssEmitting) LayoutManager
    // warns once at first doLayout, not on every re-layout. Re-armed by setLayout.
    private boolean warnedCustomLayout;

    // Focus-traversal state. No traversal engine reads any of it (D_focus_managers tier 3), but
    // AWT's getters answer from these fields and its setters fire a bound property
    // from each, so R_decline_effect_only keeps them. Defaults are AWT's: no policy, not a cycle root
    // (Window overrides isFocusCycleRoot to true), not a provider.
    private java.awt.FocusTraversalPolicy focusTraversalPolicy;
    private boolean focusCycleRoot;
    private boolean focusTraversalPolicyProvider;

    // ContainerListener storage lives in Component.listenerList (shared
    // EventListenerList for all AWT listener types). Snapshot iteration in
    // processContainerEvent makes in-dispatch listener mutation safe — same
    // guarantee the old per-Container CopyOnWriteArrayList gave us.

    public Container() {
        // Plain Div peer — D_layout_css_on_content's assumed substrate for LayoutManager CSS.
        this(new com.vaadin.flow.component.html.Div());
    }

    protected Container(com.vaadin.flow.component.Component peer) {
        super(peer);
    }

    /**
     * Peer-side element that child peers get attached to, and that built-in
     * LayoutManagers write container-wide CSS to per D_layout_css_on_content. Defaults to the
     * container's own peer element; subclasses whose peer has internal
     * structure (e.g. JFrame with a title-bar + content slot) override this
     * to redirect children to the content slot. Index positions passed to
     * addImpl apply within this element only.
     *
     * {@link vaadinx.EHelper#applyContainerCss} gates LayoutManager writes on
     * this element being a plain &lt;div&gt;; non-Div peers fall through to
     * {@link vaadinx.EHelper#onUnsupportedPeerShape}.
     *
     * <p>Visibility is {@code public} so cross-package layout managers
     * (e.g. {@code vaadinx.swing.BoxLayout}, whose JDK package is
     * {@code javax.swing} not {@code java.awt}) can resolve the dispatch
     * element. Same-package layouts ({@link vaadinx.awt.FlowLayout},
     * {@link vaadinx.awt.BorderLayout}) reach in identically.
     */
    public com.vaadin.flow.dom.Element peerContentElement() {
        return getPeer().getElement();
    }

    public void remove(vaadinx.awt.Component comp) {
        int i = components.indexOf(comp);
        if (i >= 0) remove(i);
    }

    public void remove(int index) {
        // Match AWT: ArrayIndexOutOfBoundsException with a specific message.
        // D_never_fail_on_gaps doesn't suppress failure modes Swing has by design — only
        // incomplete emulation. Bare ArrayList.remove throws the parent type
        // IndexOutOfBoundsException, which a `catch (ArrayIndexOutOfBoundsException)`
        // would miss.
        if (index < 0 || index >= components.size()) {
            throw new ArrayIndexOutOfBoundsException(index);
        }
        vaadinx.awt.Component removed = components.get(index);
        // AWT's `if (peer != null) comp.removeNotify()`, and it comes first —
        // ahead of the layout manager, the unlink and PARENT_CHANGED (measured
        // on JDK 25: removeNotify brackets, then the parent event). A component
        // leaving a displayable container is undisplayable, subtree and all.
        if (displayable) {
            removed.removeNotify();
        }
        // AWT: notify the layout manager *before* unlinking (R_infra_not_surface — still copy
        // the Swing-side call even if layoutMgr is null today).
        if (layoutMgr != null) {
            layoutMgr.removeLayoutComponent(removed);
        }
        components.remove(index);
        withPeer(p -> removed.getPeer().getElement().removeFromParent());
        removed.parent = null;
        // Fire COMPONENT_REMOVED *after* the bookkeeping is settled (AWT
        // ordering) so a listener inspecting the container sees the
        // post-removal state.
        fireContainerEvent(vaadinx.awt.event.ContainerEvent.COMPONENT_REMOVED, removed);
        // AWT also fires a HIERARCHY_CHANGED(PARENT_CHANGED) on the removed
        // subtree. changedParent is `this` even post-unlink — AWT passes the
        // old parent so listeners can tell which container the component
        // used to belong to.
        removed.fireHierarchyEvent(
                vaadinx.awt.event.HierarchyEvent.HIERARCHY_CHANGED,
                removed, this, vaadinx.awt.event.HierarchyEvent.PARENT_CHANGED);
    }

    public void update(java.awt.Graphics g) {
        // AWT: clear background then paint. Painting is effectively no-op (R_layouts_close_enough —
        // browser paints), but paint() recurses into children so user-overridden
        // paint() on leaves still fires.
        paint(g);
    }

    // All five add(...) overloads funnel to addImpl, matching AWT's choke-point design —
    // subclasses only need to override addImpl to intercept every add path.

    public vaadinx.awt.Component add(vaadinx.awt.Component comp) {
        addImpl(comp, null, -1);
        return comp;
    }

    public void add(vaadinx.awt.Component comp, java.lang.Object constraints) {
        addImpl(comp, constraints, -1);
    }

    public vaadinx.awt.Component add(vaadinx.awt.Component comp, int index) {
        addImpl(comp, null, index);
        return comp;
    }

    public void add(vaadinx.awt.Component comp, java.lang.Object constraints, int index) {
        addImpl(comp, constraints, index);
    }

    public vaadinx.awt.Component add(java.lang.String name, vaadinx.awt.Component comp) {
        // Legacy AWT 1.0 named-constraint form; the String is the constraint.
        addImpl(comp, name, -1);
        return comp;
    }

    public void list(java.io.PrintStream out, int indent) {
        // AWT: print self at the given indent, then each child indented deeper.
        super.list(out, indent);
        for (vaadinx.awt.Component child : components) {
            child.list(out, indent + 1);
        }
    }

    public void list(java.io.PrintWriter out, int indent) {
        // PrintWriter variant of list — same recursion.
        super.list(out, indent);
        for (vaadinx.awt.Component child : components) {
            child.list(out, indent + 1);
        }
    }

    public void validate() {
        // AWT walks the subtree doing layout. Under D_layout_css_on_content this is how
        // container-wide CSS (display: grid, flex, …) actually lands on
        // peers — validateTree → doLayout → LayoutManager.layoutContainer
        // writes the CSS. Per-child CSS already landed at add time via
        // addLayoutComponent; this pass handles the container side.
        //
        // Unguarded by isValid() on purpose: Component.isValid() always
        // returns true, and re-running validateTree is idempotent (CSS
        // writes overwrite themselves). Needs an external trigger —
        // Window.setVisible(true) (pending) or an explicit user validate().
        validateTree();
        super.validate();
    }

    public void print(java.awt.Graphics g) {
        // Matches paint(): self-print is no-op (R_layouts_close_enough), but we walk children so
        // user overrides on leaves fire. R_swing_is_truth — preserve the Swing dispatch contract.
        super.print(g);
        printComponents(g);
    }

    protected java.lang.String paramString() {
        // AWT's Container.paramString appends ",layout=<mgr-class>" when a
        // manager is installed. Empty otherwise so subclasses concatenating
        // super.paramString() produce tidy output (R_swing_is_truth / D_never_fail_on_gaps).
        java.lang.String s = super.paramString();
        if (layoutMgr != null) {
            s = s + ",layout=" + layoutMgr.getClass().getName();
        }
        return s;
    }

    public void removeAll() {
        // Iterate tail-first so each remove(int) sees a valid index.
        while (!components.isEmpty()) remove(components.size() - 1);
    }

    public vaadinx.awt.Component getComponent(int n) {
        // AWT throws ArrayIndexOutOfBoundsException — match exactly, since code
        // that catches that subtype won't catch ArrayList.get's plain IOBE.
        if (n < 0 || n >= components.size()) {
            throw new ArrayIndexOutOfBoundsException("No such child: " + n);
        }
        return components.get(n);
    }

    public void invalidate() {
        // AWT's Container.invalidate also tells a LayoutManager2 to drop its
        // cached layout state, then walks up to the nearest validate-root.
        // The walk-up is Vaadin's job (R_layouts_close_enough); the notification is not — R_infra_not_surface says
        // copy the Swing call even when no manager is installed yet.
        if (layoutMgr instanceof vaadinx.awt.LayoutManager2 lm2) {
            lm2.invalidateLayout(this);
        }
        super.invalidate();
    }

    public int countComponents() {
        // Deprecated AWT 1.0 alias.
        return getComponentCount();
    }

    public vaadinx.awt.Component[] getComponents() {
        // Defensive copy — AWT returns a fresh array so callers can't mutate
        // the container's state.
        return components.toArray(new vaadinx.awt.Component[0]);
    }

    public java.awt.Insets insets() {
        // Deprecated AWT 1.0 alias for getInsets.
        return getInsets();
    }

    public java.awt.Insets getInsets() {
        // Bare Container has no border. A JComponent subclass with a Border will
        // override to report the border's insets. Fresh instance because AWT's
        // contract lets callers mutate the returned Insets.
        return new java.awt.Insets(0, 0, 0, 0);
    }

    /**
     * Walks from {@code this} upward, so it catches {@code add(this)}
     * too — which is why a self-add reports "adding container's
     * parent to itself" rather than the more obvious "adding
     * component to itself". AWT has no separate self-check, so
     * neither do we.
     */
    private void checkAddToSelf(vaadinx.awt.Component comp) {
        if (comp instanceof vaadinx.awt.Container) {
            for (vaadinx.awt.Container cn = this; cn != null; cn = (cn.parent instanceof vaadinx.awt.Container p) ? p : null) {
                if (cn == comp) {
                    throw new IllegalArgumentException("adding container's parent to itself");
                }
            }
        }
    }

    /**
     * Without this, nesting a {@code Window} silently succeeds and
     * renders its peer element inline inside ours, instead of failing
     * where the mistake is.
     */
    private void checkNotAWindow(vaadinx.awt.Component comp) {
        if (comp instanceof vaadinx.awt.Window) {
            throw new IllegalArgumentException("adding a window to a container");
        }
    }

    /**
     * Lifts a {@code disabled} this container pushed to its peer while it was
     * still empty, leaving {@link #isEnabled()} false. Call once a child has
     * been linked, from every insertion path (D_container_enabled_no_cascade).
     */
    private void releasePeerDisableForNewChild() {
        if (!isEnabled() && !pushesEnabledToPeer()
                && getPeer() instanceof com.vaadin.flow.component.HasEnabled he) {
            withPeer(p -> he.setEnabled(true));
        }
    }

    protected void addImpl(vaadinx.awt.Component comp, java.lang.Object constraints, int index) {
        // The single choke point: the five add(...) overloads all funnel here, so
        // subclasses override only this method to intercept every insertion path.

        // Reject the same misuses AWT rejects — D_never_fail_on_gaps only suppresses failures
        // caused by incomplete emulation, not programming errors Swing itself
        // catches. Guard *order* is AWT's, not ours to tidy: the bounds check
        // runs first, so add(this, 999) reports the bad position rather than
        // the bad component, exactly as java.awt.Container does.
        if (index < -1 || index > components.size()) {
            throw new IllegalArgumentException("illegal component position");
        }
        checkAddToSelf(comp);
        checkNotAWindow(comp);

        // Detach from previous parent first. AWT does the same — reparenting a
        // component without an intermediate remove() is legal and common.
        if (comp.parent != null) {
            comp.parent.remove(comp);
            // AWT re-checks after the detach and *throws* rather than clamping:
            // if comp was our own child, its removal shrank the list and an
            // old-end index now points past the new end. Clamping instead would
            // silently accept a position AWT rejects (R_match_swing_errors).
            if (index > components.size()) {
                throw new IllegalArgumentException("illegal component position");
            }
        } else if (comp.displayable) {
            // No AWT counterpart, because AWT cannot reach this state: outside
            // Windows, displayability implies a parent that would have just
            // unrealised it. SB-Emulators can — an emulator added straight to a vanilla
            // Vaadin layout is a realisation root (Component.onPeerAttached),
            // displayable with no parent. Unrealise it here, exactly as the
            // reparent above would have, so that the addNotify below is its
            // first and not its second.
            comp.removeNotify();
        }

        int insertAt = index == -1 ? components.size() : index;
        components.add(insertAt, comp);
        comp.parent = this;
        releasePeerDisableForNewChild();

        // Mirror into the peer DOM. peerContentElement() lets subclasses redirect
        // children into a peer-internal content slot without overriding addImpl.
        withPeer(p -> peerContentElement().insertChild(insertAt, comp.getPeer().getElement()));

        // AWT's `if (peer != null) comp.addNotify()`: a component added to an
        // already-displayable container is realised on the spot, subtree and
        // all. Guarded on *our* displayability only, as the JDK guards it —
        // in AWT the child cannot already be displayable here, since the
        // reparent above unrealised it. The parent link is set *before* the
        // DOM insert, so the Vaadin attach that insert triggers already sees a
        // non-null parent and stands down (Component.onPeerAttached) — leaving
        // this the single realisation path, in AWT's order, rather than a race
        // with it.
        if (displayable) {
            comp.addNotify();
        }

        // AWT: notify the layout manager with the constraint object. R_infra_not_surface — we
        // keep this call shape even while layoutMgr is null in practice, so
        // real managers plug in without touching every call site. The
        // LayoutManager2 branch gets arbitrary constraints; the plain
        // LayoutManager branch only accepts String constraints (that's the
        // whole reason LayoutManager2 was introduced).
        if (layoutMgr != null) {
            if (layoutMgr instanceof vaadinx.awt.LayoutManager2 lm2) {
                lm2.addLayoutComponent(comp, constraints);
            } else if (constraints instanceof java.lang.String s) {
                layoutMgr.addLayoutComponent(s, comp);
            }
        }

        // Fire COMPONENT_ADDED last, after the child is fully linked and the
        // layout manager knows about it — matches AWT's ordering so a
        // listener can e.g. call container.validate() and get a correct tree.
        // Deliberately not fired from setComponentZOrder: AWT documents that
        // method as specifically skipping the event (that's its whole reason
        // for existing alongside add(comp, index)).
        fireContainerEvent(vaadinx.awt.event.ContainerEvent.COMPONENT_ADDED, comp);
        // AWT also fires HIERARCHY_CHANGED(PARENT_CHANGED) on the added
        // subtree — each descendant's HierarchyListeners see it, with
        // changedParent set to the new parent (this).
        comp.fireHierarchyEvent(
                vaadinx.awt.event.HierarchyEvent.HIERARCHY_CHANGED,
                comp, this, vaadinx.awt.event.HierarchyEvent.PARENT_CHANGED);
    }

    /**
     * Insert {@code comp} into this container's component list and reparent
     * it to this container <em>without</em> mirroring into the peer DOM and
     * <em>without</em> notifying the layout manager. Mirror of {@link #addImpl}
     * for slot-based containers whose peer manages its own child DOM
     * (Vaadin {@code Scroller.setContent}, {@code SplitLayout.setPrimary/Secondary},
     * …) — the AWT-side bookkeeping (`components`, parent linkage,
     * COMPONENT_ADDED + HIERARCHY_CHANGED) still needs to land so
     * {@link #getComponents()} / {@link #getComponentCount()} reflect the
     * JDK tree shape per R_swing_is_truth. Without this seam, slot-based subclasses
     * either skip {@code components} entirely (silent wrong tree shape)
     * or call {@code super.addImpl} and end up with phantom peer-DOM
     * insertions fighting the slot setter.
     */
    protected void addSlotChild(vaadinx.awt.Component comp, int index) {
        if (comp == this) {
            throw new IllegalArgumentException("adding component to itself");
        }
        if (comp instanceof vaadinx.awt.Container c && c.isAncestorOf(this)) {
            throw new IllegalArgumentException("adding container's parent to itself");
        }
        if (index < -1 || index > components.size()) {
            throw new IllegalArgumentException("illegal component position");
        }
        if (comp.parent != null) {
            comp.parent.remove(comp);
        }
        int size = components.size();
        int insertAt = (index == -1 || index > size) ? size : index;
        components.add(insertAt, comp);
        comp.parent = this;
        releasePeerDisableForNewChild();
        fireContainerEvent(vaadinx.awt.event.ContainerEvent.COMPONENT_ADDED, comp);
        comp.fireHierarchyEvent(
                vaadinx.awt.event.HierarchyEvent.HIERARCHY_CHANGED,
                comp, this, vaadinx.awt.event.HierarchyEvent.PARENT_CHANGED);
    }

    /**
     * Mirror of {@link #addSlotChild} for removal. Unlinks {@code comp}
     * from {@code components} + clears parent + fires AWT events, without
     * touching the peer DOM. No-op if {@code comp} isn't a child of this
     * container.
     */
    protected void removeSlotChild(vaadinx.awt.Component comp) {
        int i = components.indexOf(comp);
        if (i < 0) return;
        components.remove(i);
        comp.parent = null;
        fireContainerEvent(vaadinx.awt.event.ContainerEvent.COMPONENT_REMOVED, comp);
        comp.fireHierarchyEvent(
                vaadinx.awt.event.HierarchyEvent.HIERARCHY_CHANGED,
                comp, this, vaadinx.awt.event.HierarchyEvent.PARENT_CHANGED);
    }

    private void fireContainerEvent(int id, vaadinx.awt.Component child) {
        // Short-circuit construction when nobody's listening — the event
        // holds references we don't want to pin alive for nothing.
        if (listenerList.getListenerCount(vaadinx.awt.event.ContainerListener.class) == 0) return;
        vaadinx.awt.event.ContainerEvent e = new vaadinx.awt.event.ContainerEvent(this, id, child);
        processContainerEvent(e);
    }

    @Override
    protected void fireHierarchyEvent(int id, vaadinx.awt.Component changed,
                                      vaadinx.awt.Container changedParent, long flags) {
        // AWT: when a component's parent/displayability/showing changes, the
        // event fires on the changed component AND every descendant. Component's
        // impl fires on self; we override to also recurse so each descendant's
        // own listeners see it (with source = that descendant).
        super.fireHierarchyEvent(id, changed, changedParent, flags);
        for (vaadinx.awt.Component child : components) {
            child.fireHierarchyEvent(id, changed, changedParent, flags);
        }
    }

    public int getComponentZOrder(vaadinx.awt.Component comp) {
        // AWT: z-order is just the child-list index, -1 if not a child.
        // indexOf does exactly that (and tolerates null — returns -1).
        return components.indexOf(comp);
    }

    public void removeNotify() {
        // AWT Container.removeNotify unrealises every child *before* chaining
        // to super, so the calls enter top-down while the displayable flags
        // flip bottom-up (measured on JDK 25: `mid>`, `leaf>`, `leaf<`,
        // `mid<`). Backwards, over the live list rather than a snapshot, and
        // unguarded: all three are the JDK's, whose own comment explains the
        // index loop — a menu is assigned as a child of JLayeredPane rather
        // than of a particular component, so the collection can change under
        // an iterator when a menu shows or hides.
        for (int i = components.size() - 1; i >= 0; i--) {
            components.get(i).removeNotify();
        }
        super.removeNotify();
    }

    public boolean isFocusCycleRoot(vaadinx.awt.Container container) {
        // AWT default: only true when `container` is the focus-cycle-root
        // ancestor of this component. We don't model focus traversal (R_infra_not_surface), so
        // false is the honest answer — not an unimplemented gap.
        return false;
    }

    public boolean isFocusCycleRoot() {
        // AWT default is false for plain Container; Window overrides to true.
        return focusCycleRoot;
    }

    public java.awt.FocusTraversalPolicy getFocusTraversalPolicy() {
        // AWT's own gate, which is pure logic and so survives: a Container that is
        // neither a policy provider nor a cycle root answers null whatever was
        // installed. The ancestor walk beyond it is not reproduced — with no
        // traversal engine there is no default policy to fall back to, so null
        // stands in for "would have inherited one".
        if (!isFocusTraversalPolicyProvider() && !isFocusCycleRoot()) {
            return null;
        }
        return focusTraversalPolicy;
    }

    public int getComponentCount() {
        return components.size();
    }

    public void addNotify() {
        // AWT Container.addNotify realises this container first (super, which
        // sets the displayable bit) and only then walks its children, so a
        // child's addNotify already sees its parent displayable. Forwards,
        // over the live list, unguarded — see removeNotify for why the JDK
        // spells the loop this way.
        super.addNotify();
        for (int i = 0; i < components.size(); i++) {
            components.get(i).addNotify();
        }
    }

    @Override
    void onPeerAttached() {
        super.onPeerAttached();
        // Lay out *this* container the moment its peer enters the live UI.
        // validate()/pack() only fires layoutContainer for the tree that
        // exists at that call; containers built and added later (a CaseView
        // opened into a tab, a dialog's content pane, any lazily-created
        // subtree) would otherwise keep their per-child grid-area styles but
        // never get the parent-side `display:grid` + templates that
        // layoutContainer writes — so the children fall back to the peer's
        // default flex/block and the layout looks scrambled.
        //
        // On the Vaadin hook rather than on addNotify, which is where it used
        // to sit: layout is a DOM concern and wants the DOM lifecycle, while
        // addNotify now follows AWT's displayability cascade and fires for
        // subtrees that have no DOM presence at all (pack() on a never-shown
        // window). Vaadin fires attach for every descendant on a subtree
        // attach, so each Container still lays itself out without a walk.
        // Idempotent with the pack()/validate() path (the CSS write overwrites
        // itself). No-op when no manager is installed.
        doLayout();
    }

    public void layout() {
        // Deprecated AWT 1.0 alias; super is already a no-op (R_layouts_close_enough).
        super.layout();
    }

    public boolean isValidateRoot() {
        // AWT's Container default. JRootPane / JScrollPane override to true.
        return false;
    }

    protected void validateTree() {
        // AWT pre-order: doLayout on self, then validateTree on each Container
        // child. doLayout dispatches into the installed LayoutManager, which
        // under D_layout_css_on_content writes container-wide CSS to the peer. Recursion also
        // preserves user overrides on child Containers — R_swing_is_truth.
        doLayout();
        for (vaadinx.awt.Component child : components) {
            if (child instanceof vaadinx.awt.Container c) {
                c.validateTree();
            }
        }
    }

    public void doLayout() {
        // AWT: hand off to the installed LayoutManager. Under D_layout_css_on_content this is
        // where container-wide CSS gets written (BorderLayout → display:grid,
        // FlowLayout → display:flex, …). No manager installed → stay silent:
        // the container has no layout declared, children render as browser
        // defaults under the peer's own CSS.
        if (layoutMgr == null) {
            // No manager rules on the children, so each child's own preferred size
            // does — the "child owns both axes" policy of D_layout_owns_child_sizing.
            // Written rather than left absent for the two reasons sizingCss states:
            // it clears a previous manager's policy after setLayout(null), and it
            // stops a child from inheriting an ancestor's `auto` (this is the very
            // shape that does it — an absolute-layout panel sitting in a
            // BorderLayout region, its children carrying pref sizes).
            applyChildSizingPolicy(false, false);
            super.doLayout();
            return;
        }
        if (!(layoutMgr instanceof vaadinx.awt.CssEmittingLayoutManager)) {
            // The M1D_custom_layoutmanager fallback: a hand-rolled pixel
            // LayoutManager with no CSS translation. WARN once and fall back to
            // a readable vertical stack rather than leaving children in the
            // peer's default flow — Swing itself doesn't throw here (R_layouts_close_enough), so we
            // don't either. A migrator who needs faithful placement implements
            // CssEmittingLayoutManager instead.
            if (!warnedCustomLayout) {
                vaadinx.EHelper.onUnimplemented("vaadinx.awt.Container",
                        "setLayout(custom LayoutManager — no CSS translation, vertical fallback)",
                        layoutMgr.getClass().getName());
                warnedCustomLayout = true;
            }
            withPeer(p -> vaadinx.EHelper.applyContainerCss(peerContentElement(), "CustomLayoutFallback",
                    com.vaadin.swingbridge.surrogates.util.LayoutCss.verticalFallbackCss()));
            // The real manager's per-axis opinion is unreadable (that is why we are
            // in the fallback at all), so leave each child at its preferred size
            // rather than guessing — and write the policy, since the fallback may
            // have replaced a manager whose policy is still on the children
            // (D_layout_owns_child_sizing).
            applyChildSizingPolicy(false, false);
        }
        // Still notify the manager (R_infra_not_surface/R_swing_is_truth — AWT's doLayout always calls it): for
        // a CssEmittingLayoutManager this is where the CSS is emitted; for a
        // custom one it's a harmless best-effort setBounds pass over the fallback.
        layoutMgr.layoutContainer(this);
    }

    /**
     * Write the same {@code D_layout_owns_child_sizing} axis policy onto every child —
     * the manager-less counterpart to a {@code CssEmittingLayoutManager}'s per-child
     * {@code childCss}, used by the two paths in {@link #doLayout} that have no
     * translatable manager to ask.
     */
    private void applyChildSizingPolicy(boolean layoutSizesWidth, boolean layoutSizesHeight) {
        java.util.Map<String, String> css =
                com.vaadin.swingbridge.surrogates.util.LayoutCss.sizingCss(layoutSizesWidth, layoutSizesHeight);
        withPeer(p -> {
            for (vaadinx.awt.Component child : components) {
                vaadinx.EHelper.applyChildCss(child.getPeer().getElement(), css);
            }
        });
    }

    // setFont inherited from Component. AWT's Container.setFont additionally fires
    // an event for descendants with null font so they repaint; CSS inheritance does
    // that automatically for us, so we need no recursion here.

    // AWT's Container versions of these getters consult the LayoutManager
    // when no explicit value was set. We replicate the dispatch (R_infra_not_surface):
    // the explicit-value path wins, a LayoutManager2's hint comes next, and the
    // Component fallback answers for a plain LayoutManager or none at all.

    public java.awt.Dimension preferredSize() {
        return getPreferredSize();
    }

    public java.awt.Dimension minimumSize() {
        return getMinimumSize();
    }

    public java.awt.Dimension getMaximumSize() {
        // Explicit set > LayoutManager2 hint > Component default.
        if (isMaximumSizeSet()) return super.getMaximumSize();
        if (layoutMgr instanceof vaadinx.awt.LayoutManager2 lm2) {
            return lm2.maximumLayoutSize(this);
        }
        return super.getMaximumSize();
    }

    public float getAlignmentX() {
        if (layoutMgr instanceof vaadinx.awt.LayoutManager2 lm2) {
            return lm2.getLayoutAlignmentX(this);
        }
        return super.getAlignmentX();
    }

    public float getAlignmentY() {
        if (layoutMgr instanceof vaadinx.awt.LayoutManager2 lm2) {
            return lm2.getLayoutAlignmentY(this);
        }
        return super.getAlignmentY();
    }

    public void paint(java.awt.Graphics g) {
        // AWT: paint self, then paintComponents(children). Effective painting is
        // no-op (R_layouts_close_enough), but the recursion lets user-overridden paint() on
        // leaves run — R_swing_is_truth.
        super.paint(g);
        paintComponents(g);
    }

    // getListeners(Class) inherited from Component. AWT's Container.getListeners
    // has its own override to fold ContainerListener in; we don't need that
    // split because Container now stores ContainerListener in the same
    // listenerList Component's impl reads from.

    protected void processContainerEvent(vaadinx.awt.event.ContainerEvent e) {
        // AWT dispatches to one of two listener methods based on the event id.
        // We don't route through processEvent(AWTEvent) because our dispatch
        // path skips Toolkit/EventQueue entirely (D_own_awt_package — no java.desktop
        // runtime); fireContainerEvent calls us directly.
        int id = e.getID();
        for (vaadinx.awt.event.ContainerListener l : awtListeners(vaadinx.awt.event.ContainerListener.class)) {
            if (id == vaadinx.awt.event.ContainerEvent.COMPONENT_ADDED) {
                l.componentAdded(e);
            } else if (id == vaadinx.awt.event.ContainerEvent.COMPONENT_REMOVED) {
                l.componentRemoved(e);
            }
        }
    }

    protected void processEvent(java.awt.AWTEvent e) {
        if (e instanceof vaadinx.awt.event.ContainerEvent) {
            processContainerEvent((vaadinx.awt.event.ContainerEvent)e);
            return;
        }
        super.processEvent(e);
    }

    public vaadinx.awt.Component getComponentAt(java.awt.Point p) {
        return getComponentAt(p.x, p.y);
    }

    public vaadinx.awt.Component getComponentAt(int x, int y) {
        return locate(x, y);
    }

    @Deprecated
    public void deliverEvent(java.awt.Event e) {
        vaadinx.awt.Component comp = getComponentAt(e.x, e.y);
        if ((comp != null) && (comp != this)) {
            e.translate(-comp.getX(), -comp.getY());
            comp.deliverEvent(e);
        } else {
            postEvent(e);
        }
    }

    public vaadinx.awt.Component locate(int x, int y) {
        vaadinx.EHelper.onUnimplemented("Container", "locate", x, y);
        return null;
    }

    public vaadinx.awt.Component findComponentAt(java.awt.Point p) {
        vaadinx.EHelper.onUnimplemented("Container", "findComponentAt", p);
        return null;
    }

    public vaadinx.awt.Component findComponentAt(int x, int y) {
        vaadinx.EHelper.onUnimplemented("Container", "findComponentAt", x, y);
        return null;
    }

    public final boolean isFocusTraversalPolicyProvider() {
        return focusTraversalPolicyProvider;
    }

    public void applyComponentOrientation(java.awt.ComponentOrientation o) {
        // AWT: set own orientation, then recurse into children. Component's impl
        // only sets its own — Container is where the recursion lives (R_swing_is_truth).
        super.applyComponentOrientation(o);
        for (vaadinx.awt.Component child : components) {
            child.applyComponentOrientation(o);
        }
    }

    public void addPropertyChangeListener(java.beans.PropertyChangeListener listener) {
        // AWT's Container overrides this to track focus-traversal-keys bookkeeping.
        // We don't model focus traversal, so this is a pure pass-through — but we
        // keep the override so the reason is visible at the call site.
        super.addPropertyChangeListener(listener);
    }

    public void addPropertyChangeListener(java.lang.String propertyName, java.beans.PropertyChangeListener listener) {
        // See addPropertyChangeListener(PropertyChangeListener) above for rationale.
        super.addPropertyChangeListener(propertyName, listener);
    }

    public synchronized void addContainerListener(vaadinx.awt.event.ContainerListener l) {
        // AWT silently ignores null listeners — EventListenerList.add already
        // checks and returns on null, so no explicit guard needed.
        listenerList.add(vaadinx.awt.event.ContainerListener.class, l);
    }

    public vaadinx.awt.LayoutManager getLayout() {
        return layoutMgr;
    }

    public void setComponentZOrder(vaadinx.awt.Component comp, int index) {
        // AWT's setComponentZOrder: reorder an existing child, or reparent a
        // component from another container, skipping ContainerListener events
        // (that's the whole reason it exists alongside add(comp, index)). We
        // don't fire ContainerEvents (D_event_port_policy — ContainerEvent needs a
        // java.awt.Component source we can't supply), so the distinction from
        // add(comp, index) is moot for us except for the intra-container
        // reorder case, which add() doesn't express.
        if (comp == null) throw new NullPointerException("illegal null argument");
        if (comp == this) throw new IllegalArgumentException("component and container cannot be the same");
        if (comp instanceof vaadinx.awt.Container c && c.isAncestorOf(this)) {
            throw new IllegalArgumentException("component and container are ancestors of each other");
        }
        // Bound check: for an intra-container move the list size stays the
        // same, so valid final positions are 0..size-1. AWT's own check is
        // looser (allows index == size) but then ArrayList.add blows up, so we
        // tighten it here — same spirit as D_never_fail_on_gaps (match Swing's failure modes,
        // but on clearly-invalid inputs).
        if (index < 0 || index >= components.size()) {
            throw new IllegalArgumentException("illegal component position " + index + " should be >=0 and <" + components.size());
        }

        int oldIndex = components.indexOf(comp);
        if (oldIndex < 0) {
            // Different-parent reparent. AWT handles it; current slice doesn't
            // need it (R_infra_not_surface). Flagged so an actual caller surfaces instead of
            // silently doing the wrong thing.
            vaadinx.EHelper.onUnimplemented("Container", "setComponentZOrder(reparent)", comp, index);
            return;
        }
        if (oldIndex == index) return;

        // AWT semantics: `index` is the position in the *post-removal* list.
        // Remove first, then add at `index` — no pre-adjustment. Moving index 0
        // to index 2 in [a,b,c] gives [b,c,a], not [b,a,c]. The peer DOM
        // mirrors this; insertChild auto-detaches same-parent children.
        components.remove(oldIndex);
        components.add(index, comp);
        withPeer(p -> peerContentElement().insertChild(index, comp.getPeer().getElement()));
    }

    public void setLayout(vaadinx.awt.LayoutManager mgr) {
        // AWT: stores the manager and invalidates so next validate re-lays out.
        // Our invalidate() is a no-op at the Component level (R_layouts_close_enough — Vaadin
        // re-lays on DOM change), but we still fire the call so LayoutManager2
        // gets its invalidateLayout() notification per R_infra_not_surface/R_swing_is_truth.
        //
        // We deliberately do NOT lay out here — AWT's setLayout only invalidates,
        // and the "user code calls revalidate() after mutating layout state" quirk
        // is emulated rather than fixed (see FlowLayout.setAlignment). But the
        // outgoing manager's container CSS is dropped, because the browser makes
        // the un-revalidated interval visible in a way Swing never does: stale
        // display:flex over children already carrying the new manager's grid-area
        // renders scrambled, where clearing it renders a coherent block flow.
        // Only when a manager is actually being replaced — a first setLayout (every
        // ctor's) has nothing of ours on the element yet.
        if (this.layoutMgr != null && this.layoutMgr != mgr) {
            withPeer(p -> vaadinx.EHelper.resetContainerCss(peerContentElement()));
        }
        this.layoutMgr = mgr;
        warnedCustomLayout = false; // re-arm the Option-A WARN for the new manager
        invalidate();
    }

    public java.awt.Dimension getPreferredSize() {
        // Explicit set > LayoutManager hint > Component default.
        if (isPreferredSizeSet()) return super.getPreferredSize();
        if (layoutMgr != null) return layoutMgr.preferredLayoutSize(this);
        return super.getPreferredSize();
    }

    public java.awt.Dimension getMinimumSize() {
        if (isMinimumSizeSet()) return super.getMinimumSize();
        if (layoutMgr != null) return layoutMgr.minimumLayoutSize(this);
        return super.getMinimumSize();
    }

    public void paintComponents(java.awt.Graphics g) {
        // AWT walks children invoking each one's paint. Painting is effectively
        // no-op (R_layouts_close_enough) but user overrides of paint() on leaves must still fire.
        for (vaadinx.awt.Component child : components) {
            child.paint(g);
        }
    }

    public void printComponents(java.awt.Graphics g) {
        // Print analogue of paintComponents.
        for (vaadinx.awt.Component child : components) {
            child.print(g);
        }
    }

    public synchronized void removeContainerListener(vaadinx.awt.event.ContainerListener l) {
        listenerList.remove(vaadinx.awt.event.ContainerListener.class, l);
    }

    public synchronized vaadinx.awt.event.ContainerListener[] getContainerListeners() {
        // AWT returns an empty array rather than null when no listeners are
        // registered. EventListenerList.getListeners honors that contract —
        // returns a fresh zero-length array when nothing's stored.
        return awtListeners(vaadinx.awt.event.ContainerListener.class);
    }

    public java.awt.Point getMousePosition(boolean allowChildren) throws java.awt.HeadlessException {
        // AWT returns null when the mouse isn't over this component — the
        // server never knows where the browser cursor is, so "not over us"
        // is the only answer we can honestly give. onUnsupported (peer
        // can't provide) rather than onUnimplemented (we haven't coded it):
        // this would require client-side cursor tracking even if we wanted
        // to provide it. Same category as createVolatileImage.
        vaadinx.EHelper.onUnsupported("Container", "getMousePosition", allowChildren);
        return null;
    }

    public boolean isAncestorOf(vaadinx.awt.Component c) {
        if (c == null) return false;
        vaadinx.awt.Container p = c.getParent();
        while (p != null) {
            if (p == this) return true;
            p = p.getParent();
        }
        return false;
    }

    public void setFocusTraversalKeys(int id, java.util.Set<? extends java.awt.AWTKeyStroke> keystrokes) {
        // Empty set = "use default traversal keys" — which in our model
        // means "browser picks", i.e. native Tab/Shift-Tab. Silent
        // accept. Non-empty = user-specified keys we don't wire (R_infra_not_surface);
        // WARN so the gap surfaces in migration logs.
        if (keystrokes != null && !keystrokes.isEmpty()) {
            vaadinx.EHelper.onUnimplemented("Container", "setFocusTraversalKeys", id, keystrokes);
        }
    }

    public java.util.Set<java.awt.AWTKeyStroke> getFocusTraversalKeys(int id) {
        // AWT would consult KeyboardFocusManager defaults (Tab / Shift-Tab) when
        // nothing is locally set. We don't model focus traversal (R_infra_not_surface), so
        // reporting any keystrokes would be misleading — nothing listens for
        // them. Empty set is the honest answer and pairs with
        // areFocusTraversalKeysSet(id) returning false silently.
        return java.util.Collections.emptySet();
    }

    public boolean areFocusTraversalKeysSet(int id) {
        // AWT default: false until setFocusTraversalKeys(id, …). Setter is a
        // stub (R_infra_not_surface), so the "explicitly set" flag is always off — matches AWT.
        return false;
    }

    // Focus-traversal *policy* dispatch is permanently out (D_focus_managers tier 3 / R_match_swing_errors (b)) —
    // nothing here consults these. Per R_decline_effect_only that licenses dropping the effect only:
    // all three are plain fields, their getters are what user code reads back, and
    // AWT fires a bound property from each, so state and notification stay.
    public void setFocusTraversalPolicy(java.awt.FocusTraversalPolicy policy) {
        java.awt.FocusTraversalPolicy oldPolicy = this.focusTraversalPolicy;
        this.focusTraversalPolicy = policy;
        vaadinx.EHelper.onUnimplemented("Container", "setFocusTraversalPolicy(traversal)", policy);
        firePropertyChange("focusTraversalPolicy", oldPolicy, policy);
    }

    public boolean isFocusTraversalPolicySet() {
        return focusTraversalPolicy != null;
    }

    public void setFocusCycleRoot(boolean focusCycleRoot) {
        boolean oldFocusCycleRoot = this.focusCycleRoot;
        this.focusCycleRoot = focusCycleRoot;
        vaadinx.EHelper.onUnimplemented("Container", "setFocusCycleRoot(traversal)", focusCycleRoot);
        firePropertyChange("focusCycleRoot", oldFocusCycleRoot, focusCycleRoot);
    }

    public final void setFocusTraversalPolicyProvider(boolean provider) {
        boolean oldProvider = this.focusTraversalPolicyProvider;
        this.focusTraversalPolicyProvider = provider;
        vaadinx.EHelper.onUnimplemented("Container", "setFocusTraversalPolicyProvider(traversal)", provider);
        firePropertyChange("focusTraversalPolicyProvider", oldProvider, provider);
    }

    public void transferFocusDownCycle() {
        vaadinx.EHelper.onUnimplemented("Container", "transferFocusDownCycle");
    }

}
