/*
 * Copyright (c) 1995, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's java.awt.Frame
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.awt;

// Generated by vaadinx.internal.Generator from java.awt.Frame, then hand-finished.

/** Emulator for {@link java.awt.Frame}. */
public class Frame extends vaadinx.awt.Window {

    // The frame-state bitmask, the argument side of setExtendedState / setState.
    // setExtendedState(JFrame.MAXIMIZED_BOTH) is one of the most common lines in a
    // Swing main(), and after the import swap `JFrame` resolves here — so these
    // absent meant that line did not compile, while SB-Emulators' own bodies (which reach
    // for java.awt.Frame's copies) built fine (D_missing_constants).
    public static final int NORMAL = 0;
    public static final int ICONIFIED = 1;
    public static final int MAXIMIZED_HORIZ = 2;
    public static final int MAXIMIZED_VERT = 4;
    public static final int MAXIMIZED_BOTH = MAXIMIZED_VERT | MAXIMIZED_HORIZ;

    // Obsoleted by java.awt.Cursor in JDK 1.1 and @Deprecated there since, but a
    // 1990s Swing app may still name them, so they carry Cursor's values as the
    // JDK's own do. Cursors themselves are R_layouts_close_enough cosmetics — these are the argument
    // constants, not a promise that the browser shows that pointer.
    /** @deprecated replaced by {@code java.awt.Cursor.DEFAULT_CURSOR}. */
    @Deprecated
    public static final int DEFAULT_CURSOR = java.awt.Cursor.DEFAULT_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.CROSSHAIR_CURSOR}. */
    @Deprecated
    public static final int CROSSHAIR_CURSOR = java.awt.Cursor.CROSSHAIR_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.TEXT_CURSOR}. */
    @Deprecated
    public static final int TEXT_CURSOR = java.awt.Cursor.TEXT_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.WAIT_CURSOR}. */
    @Deprecated
    public static final int WAIT_CURSOR = java.awt.Cursor.WAIT_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.SW_RESIZE_CURSOR}. */
    @Deprecated
    public static final int SW_RESIZE_CURSOR = java.awt.Cursor.SW_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.SE_RESIZE_CURSOR}. */
    @Deprecated
    public static final int SE_RESIZE_CURSOR = java.awt.Cursor.SE_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.NW_RESIZE_CURSOR}. */
    @Deprecated
    public static final int NW_RESIZE_CURSOR = java.awt.Cursor.NW_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.NE_RESIZE_CURSOR}. */
    @Deprecated
    public static final int NE_RESIZE_CURSOR = java.awt.Cursor.NE_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.N_RESIZE_CURSOR}. */
    @Deprecated
    public static final int N_RESIZE_CURSOR = java.awt.Cursor.N_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.S_RESIZE_CURSOR}. */
    @Deprecated
    public static final int S_RESIZE_CURSOR = java.awt.Cursor.S_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.W_RESIZE_CURSOR}. */
    @Deprecated
    public static final int W_RESIZE_CURSOR = java.awt.Cursor.W_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.E_RESIZE_CURSOR}. */
    @Deprecated
    public static final int E_RESIZE_CURSOR = java.awt.Cursor.E_RESIZE_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.HAND_CURSOR}. */
    @Deprecated
    public static final int HAND_CURSOR = java.awt.Cursor.HAND_CURSOR;
    /** @deprecated replaced by {@code java.awt.Cursor.MOVE_CURSOR}. */
    @Deprecated
    public static final int MOVE_CURSOR = java.awt.Cursor.MOVE_CURSOR;

    // AWT's Frame stores title separately from its peer; getTitle reads
    // this field directly rather than round-tripping through the Dialog.
    // Default is empty string per AWT contract — never null from getTitle,
    // even before setTitle has been called.
    private java.lang.String title = "";

    // AWT's Frame is resizable by default. An overlay-rendered frame (SFrame
    // peer) mirrors this onto the Vaadin Dialog's native resize grips via
    // setResizable below; the field still round-trips for R_swing_is_truth / R_match_swing_errors and gates
    // the InlineStrategy fixed-size-window opt-out per D_inline_route_sizing — setResizable
    // (false) + setPreferredSize + pack() on a @MainWindow JFrame (SJPanel
    // peer, no overlay) is the declared way to ask for a fixed-size main
    // window in the browser.
    private boolean resizable = true;

    private java.awt.Rectangle maximizedBounds;

    public Frame(java.lang.String title, vaadinx.awt.GraphicsConfiguration gc) {
        // Accepted and ignored: there is exactly one configuration (the browser viewport),
        // so choosing one cannot change where the frame lands.
        this(new com.vaadin.swingbridge.surrogates.SFrame());
        setTitle(title);
    }

    public Frame(java.lang.String title) throws java.awt.HeadlessException {
        this(new com.vaadin.swingbridge.surrogates.SFrame());
        setTitle(title);
    }

    public Frame(vaadinx.awt.GraphicsConfiguration gc) {
        // See the (String, GC) ctor — GraphicsConfiguration is accepted-and-ignored.
        this(new com.vaadin.swingbridge.surrogates.SFrame());
    }

    public Frame() throws java.awt.HeadlessException {
        this(new com.vaadin.swingbridge.surrogates.SFrame());
    }

    protected Frame(com.vaadin.flow.component.Component peer) {
        super(peer);
    }

    public void remove(java.awt.MenuComponent arg0) {
        vaadinx.EHelper.onUnimplemented("Frame", "remove", arg0);
    }

    public synchronized int getState() {
        // AWT's legacy single-bit view of the extended state, and — per R_no_vaadin_in_api
        // limb 2 — it derives rather than answers: an override of
        // getExtendedState must be what this reads, exactly as in the JDK.
        return (getExtendedState() & ICONIFIED) != 0
                ? ICONIFIED
                : NORMAL;
    }

    public synchronized void setState(int state) {
        // JDK body verbatim: a masked read-modify-write that routes through
        // setExtendedState, so that one override catches both entry points.
        // Note the JDK ignores anything that is neither ICONIFIED nor NORMAL
        // — setState(MAXIMIZED_BOTH) is a silent no-op here as it is there,
        // and the WARN for an unsupported request comes from setExtendedState
        // on the paths that actually reach it.
        int current = getExtendedState();
        if (state == ICONIFIED && (current & ICONIFIED) == 0) {
            setExtendedState(current | ICONIFIED);
        } else if (state == NORMAL && (current & ICONIFIED) != 0) {
            setExtendedState(current & ~ICONIFIED);
        }
    }

    protected java.lang.String paramString() {
        // AWT's Frame.paramString appends ",title=...,resizable,normal/iconified".
        // Title and resizable both round-trip through local fields; state is
        // always NORMAL (browser tabs don't iconify). Chain up so Container's
        // layout= line and Component's bounds are in front of our additions —
        // matches AWT's toString shape and keeps custom subclasses that chain
        // super.paramString() working.
        java.lang.String s = super.paramString();
        if (!title.isEmpty()) s = s + ",title=" + title;
        if (resizable) s = s + ",resizable";
        // Through getExtendedState, not the ",normal" constant it used to be:
        // the JDK reads its state here too, so an override of the getter has
        // to reach toString for the call graph to be honest.
        int st = getExtendedState();
        if (st == NORMAL) return s + ",normal";
        if ((st & ICONIFIED) != 0) s = s + ",iconified";
        if ((st & MAXIMIZED_BOTH) == MAXIMIZED_BOTH) {
            s = s + ",maximized";
        } else if ((st & MAXIMIZED_HORIZ) != 0) {
            s = s + ",maximized_horiz";
        } else if ((st & MAXIMIZED_VERT) != 0) {
            s = s + ",maximized_vert";
        }
        return s;
    }

    // addNotify / removeNotify inherited from Window → Container: they walk
    // children so user overrides on leaves still fire (R_swing_is_truth). The generator
    // re-stubbed them; removing the stubs restores the proper chain.

    /**
     * An AWT menu bar renders nothing here — {@code java.awt.MenuBar} is not a
     * {@code Component} and SB-Emulators ports no peer for it, where a Swing
     * {@code JMenuBar} goes through {@link vaadinx.swing.JFrame#setJMenuBar}. So the
     * effect drops and the state stays: AWT stores the bar and fires nothing
     * (D_window_fanout), and its parent/peer wiring is what needed the peer.
     */
    public void setMenuBar(java.awt.MenuBar arg0) {
        vaadinx.EHelper.onUnimplemented("Frame", "setMenuBar", arg0);
        if (menuBar == arg0) {
            return;   // AWT's own early return
        }
        menuBar = arg0;
    }

    private java.awt.MenuBar menuBar;

    public void setMaximizedBounds(java.awt.Rectangle bounds) {
        // R_decline_effect_only: AWT stores the field unconditionally and only then pushes
        // to the peer, so the state is ours to keep even though the pixel-exact maximize
        // is not (R_layouts_close_enough). The WARN reports the declined peer push alone.
        this.maximizedBounds = bounds;
        if (bounds != null) {
            vaadinx.EHelper.onUnimplemented("Frame", "setMaximizedBounds", bounds);
        }
    }

    public void setTitle(java.lang.String title) {
        // AWT's Frame coerces a null title to the empty string, and getTitle
        // is documented as never-null. Mirror that so user code doesn't have
        // to care which contract we honor.
        java.lang.String normalized = title != null ? title : "";
        java.lang.String old = this.title;
        this.title = normalized;
        // Delegate the peer-side Dialog.setHeaderTitle write to SFrame per
        // SD_sframe — SFrame's own setTitle does the normalize + mirror + fires
        // its own surrogate-layer "title" PCE. We still fire our own
        // emulator-layer PCE here so migrated PropertyChangeListener
        // registrations on Frame still hear the event (SD_sjslider/SD_sjspinner shape —
        // independent listener lists per layer).
        if (getPeer() instanceof com.vaadin.swingbridge.surrogates.SFrame sf) {
            withPeer(p -> sf.setTitle(normalized));
        }
        firePropertyChange("title", old, normalized);
    }

    // setIconImage / getIconImage inherited from Window — we don't wire
    // icons to the browser anyway (favicons are route-level, not Window-
    // level), so Window's single stub handles both classes uniformly.

    public void setResizable(boolean b) {
        // AWT's Frame is resizable by default. Field-shadow so isResizable
        // round-trips per R_swing_is_truth and PCE fires the "resizable" bound property
        // change. The field is also the gate for the InlineStrategy
        // fixed-size-window opt-out per D_inline_route_sizing: a @MainWindow JFrame with
        // setResizable(false) + setPreferredSize + pack() switches from
        // PWA-shape 100%/100% to pixel sizing.
        boolean old = this.resizable;
        this.resizable = b;
        // For an overlay-rendered frame (SFrame peer = Vaadin Dialog), drive
        // the native Dialog resize grips too. The @MainWindow case (SJPanel
        // peer) has no overlay to resize — the field alone gates D_inline_route_sizing there.
        if (getPeer() instanceof com.vaadin.swingbridge.surrogates.SFrame sf) {
            withPeer(p -> sf.setResizable(b));
        }
        firePropertyChange("resizable", old, b);
    }

    /**
     * AWT's frame state bitmask — NORMAL (0) | ICONIFIED (1) |
     * MAXIMIZED_HORIZ (2) | MAXIMIZED_VERT (4). The single writer is
     * {@link #setExtendedState}, which is why {@link #getState} /
     * {@link #setState} derive rather than shadow: one field, one writer,
     * one override point.
     *
     * <p>In practice this never leaves NORMAL, because
     * {@link #isFrameStateSupported} asks the toolkit and
     * {@link vaadinx.awt.Toolkit#isFrameStateSupported} declines every state
     * — a browser tab neither iconifies nor maximizes under a window
     * manager. The field exists anyway so the JDK's call graph is real: the
     * decline is data the toolkit supplies, not a constant wired into Frame.
     */
    private int state = NORMAL;

    public int getExtendedState() {
        return state;
    }

    public void setExtendedState(int state) {
        // JDK body: decline first, write second. The WARN rides the decline
        // rather than the "not NORMAL" test, so it reports what actually
        // happened — a request the toolkit refused. Silent when the frame is
        // already in the requested state, which is every NORMAL call.
        if (!isFrameStateSupported(state)) {
            if (state != this.state) {
                vaadinx.EHelper.onUnimplemented("Frame", "setExtendedState", state);
            }
            return;
        }
        this.state = state;
    }

    /**
     * JDK {@code Frame.isFrameStateSupported} verbatim, down to the
     * compound-state retry: {@code Toolkit.isFrameStateSupported} answers
     * {@code false} for a compound state even when every part is supported,
     * so an unsupported answer is re-asked with ICONIFIED masked off before
     * being believed.
     */
    private boolean isFrameStateSupported(int state) {
        if (!getToolkit().isFrameStateSupported(state)) {
            if (((state & ICONIFIED) != 0)
                    && !getToolkit().isFrameStateSupported(ICONIFIED)) {
                return false;
            } else {
                state &= ~ICONIFIED;
            }
            return getToolkit().isFrameStateSupported(state);
        }
        return true;
    }

    /**
     * R_swing_is_truth field shadow — see {@link #setUndecorated(boolean)}. AWT
     * default false: a Frame has titlebar and borders.
     */
    private boolean undecorated;

    public boolean isUndecorated() {
        return undecorated;
    }

    // setOpacity / setShape / setBackground: the JDK overrides all three on
    // Frame for one reason only — per-pixel translucency and non-rectangular
    // outlines require an undecorated frame, so a decorated one throws. That
    // is an R_match_swing_errors throw (real Swing rejects these inputs), and it is independent
    // of whether we can *render* the effect: each override chains to Window's,
    // which keeps its own R_layouts_close_enough stance (setOpacity WARNs, setShape WARNs only on
    // non-null, setBackground reaches Component's real CSS writer). JDK
    // messages verbatim.

    @Override
    public void setOpacity(float opacity) {
        if (opacity < 1.0f && !isUndecorated()) {
            throw new java.awt.IllegalComponentStateException("The frame is decorated");
        }
        super.setOpacity(opacity);
    }

    @Override
    public void setShape(java.awt.Shape shape) {
        if (shape != null && !isUndecorated()) {
            throw new java.awt.IllegalComponentStateException("The frame is decorated");
        }
        super.setShape(shape);
    }

    @Override
    public void setBackground(java.awt.Color bgColor) {
        if (bgColor != null && bgColor.getAlpha() < 255 && !isUndecorated()) {
            throw new java.awt.IllegalComponentStateException("The frame is decorated");
        }
        super.setBackground(bgColor);
    }

    public void setCursor(int type) {
        // Deprecated AWT 1.0 — delegates to Cursor.getPredefinedCursor(type)
        // and then setCursor(Cursor). Component.setCursor handles the CSS
        // write and PropertyChangeEvent; we just translate the int code.
        setCursor(java.awt.Cursor.getPredefinedCursor(type));
    }

    public java.lang.String getTitle() {
        // Never-null per AWT contract — initialised to "" and setTitle
        // normalises null to "" before storing.
        return title;
    }

    public java.awt.Image getIconImage() {
        // AWT's contract: getIconImage returns icons.isEmpty() ? null :
        // icons.get(0), reading from the same list setIconImages populates.
        // Window.getIconImages already returns an honest empty list (icons
        // aren't wired — favicons are route-level, not Window-level); derive
        // from it rather than maintain a parallel field, so setIconImages
        // and setIconImage keep a single source of truth.
        java.util.List<java.awt.Image> imgs = getIconImages();
        return imgs.isEmpty() ? null : imgs.get(0);
    }

    public java.awt.MenuBar getMenuBar() {
        return menuBar;
    }

    public boolean isResizable() {
        // AWT default is true; setResizable round-trips through the field
        // (kept in sync with the SFrame peer's native resize flag for
        // overlay frames). The field is the source of truth here because it
        // also covers the @MainWindow SJPanel peer (no overlay) and gates
        // the D_inline_route_sizing opt-out.
        return resizable;
    }

    /** @return what {@link #setMaximizedBounds} stored; null until set, as in AWT */
    public java.awt.Rectangle getMaximizedBounds() {
        return maximizedBounds;
    }

    public void setUndecorated(boolean b) {
        // R_swing_is_truth mirror driving SWindow's emul-undecorated CSS class (strips
        // header/padding/radius; keeps the box-shadow — R_layouts_close_enough divergence
        // documented at SWindow.setUndecoratedChrome). The displayable-time
        // throw matches JDK Frame.setUndecorated's contract (R_match_swing_errors — Swing throws on this
        // input, so do we); JDK message kept verbatim. InlineStrategy
        // frames (SJPanel peer, no overlay chrome to strip) field-shadow
        // only — the instanceof skips the peer write.
        if (isDisplayable()) {
            throw new java.awt.IllegalComponentStateException("The frame is displayable.");
        }
        this.undecorated = b;
        if (getPeer() instanceof com.vaadin.swingbridge.surrogates.SWindow sw) {
            withPeer(p -> sw.setUndecoratedChrome(b));
        }
    }

    public int getCursorType() {
        // Deprecated AWT 1.0 — returns the int type code of the current
        // cursor. Component.getCursor is never-null (falls back to default
        // cursor), so this is a safe one-liner.
        return getCursor().getType();
    }

    public static vaadinx.awt.Frame[] getFrames() {
        // AWT keeps a separate Frame registry; we derive it from Window's
        // live graph so there's one source of truth. Same leak-free property
        // as EHelper.getWindows.
        java.util.List<vaadinx.awt.Frame> out = new java.util.ArrayList<>();
        for (vaadinx.awt.Window w : vaadinx.EHelper.getWindows()) {
            if (w instanceof vaadinx.awt.Frame f) out.add(f);
        }
        return out.toArray(new vaadinx.awt.Frame[0]);
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("Frame", "getAccessibleContext");
        return null;
    }

}
