/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.swing.event;

import com.vaadin.flow.component.Component;
import com.vaadin.swingbridge.surrogates.awt.event.SComponentEvent;

/**
 * Surrogate-side port of {@link javax.swing.event.InternalFrameEvent}.
 * Source retyped from {@code javax.swing.JInternalFrame} to Vaadin
 * {@link com.vaadin.flow.component.Component} per SD_event_port_stance — the surrogate that
 * emits this event ({@code SJInternalFrame}) extends Dialog (via SWindow),
 * so "the internal frame" is a Vaadin Component, not a Swing JComponent.
 *
 * <p>Constants preserved verbatim from {@link javax.swing.event.InternalFrameEvent}
 * so {@code id} arithmetic carries across unchanged — migrated code that
 * checks {@code e.getID() == INTERNAL_FRAME_CLOSING} works against either
 * value (same int).
 *
 * <p>Extends {@link SComponentEvent} (not JDK {@code AWTEvent} directly)
 * so it shares the surrogate ComponentEvent shape the other surrogate
 * event ports use ({@link com.vaadin.swingbridge.surrogates.awt.event.SWindowEvent} takes the
 * same base). The Window↔InternalFrame parallel is exact: OPENED /
 * CLOSING / CLOSED / ICONIFIED / DEICONIFIED / ACTIVATED / DEACTIVATED map
 * 1:1 onto the Window ids, driven from {@code SJInternalFrame}'s lifecycle
 * (SD_internalframe_fire_seams).
 */
public class SInternalFrameEvent extends SComponentEvent {

    // Verbatim from javax.swing.event.InternalFrameEvent.
    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int INTERNAL_FRAME_ACTIVATED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_ACTIVATED;
    public static final int INTERNAL_FRAME_CLOSED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_CLOSED;
    public static final int INTERNAL_FRAME_CLOSING = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_CLOSING;
    public static final int INTERNAL_FRAME_DEACTIVATED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_DEACTIVATED;
    public static final int INTERNAL_FRAME_DEICONIFIED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_DEICONIFIED;
    public static final int INTERNAL_FRAME_FIRST = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_FIRST;
    public static final int INTERNAL_FRAME_ICONIFIED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_ICONIFIED;
    public static final int INTERNAL_FRAME_LAST = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_LAST;
    public static final int INTERNAL_FRAME_OPENED = javax.swing.event.InternalFrameEvent.INTERNAL_FRAME_OPENED;
    // --- end generated constants ---

    public SInternalFrameEvent(Component source, int id) {
        super(source, id);
    }

    /** Same as {@link #getComponent()} but named to match the JDK shape. */
    public Component getInternalFrame() {
        return getComponent();
    }

    @Override
    public String paramString() {
        return switch (id) {
            case INTERNAL_FRAME_OPENED      -> "INTERNAL_FRAME_OPENED";
            case INTERNAL_FRAME_CLOSING     -> "INTERNAL_FRAME_CLOSING";
            case INTERNAL_FRAME_CLOSED      -> "INTERNAL_FRAME_CLOSED";
            case INTERNAL_FRAME_ICONIFIED   -> "INTERNAL_FRAME_ICONIFIED";
            case INTERNAL_FRAME_DEICONIFIED -> "INTERNAL_FRAME_DEICONIFIED";
            case INTERNAL_FRAME_ACTIVATED   -> "INTERNAL_FRAME_ACTIVATED";
            case INTERNAL_FRAME_DEACTIVATED -> "INTERNAL_FRAME_DEACTIVATED";
            default                         -> "unknown type";
        };
    }
}
