/*
 * Copyright (c) 1997, 2024, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.text.JTextComponent
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing.text;

// Generated by vaadinx.internal.Generator from javax.swing.text.JTextComponent
// Hand-finished: Document wired (reused JDK PlainDocument
// per D_whitelist_porting — Document's source is Object, no port needed), setText /
// getText / setDocument / getDocument / setEditable + paramString.
// The R_swing_is_truth Document ↔ peer sync lives here, parameterised on a
// Vaadin TextFieldBase peer so JPasswordField (PasswordField peer) and
// JTextArea (TextArea peer) inherit it transparently without each
// re-implementing docToPeer + ValueChangeListener + preventPeerEvents.
// Caret + selection are the JDK's bodies over the installed Caret, a
// vaadinx.swing.text.DefaultCaret by default (D_emulator_caret): the caret owns
// dot/mark, this class renders them onto the peer's input and feeds the browser's
// own caret moves back through setDot / moveDot.
// Highlighter / Keymap / drag-drop / printing / scroll stay onUnimplemented.

/** Emulator for {@link javax.swing.text.JTextComponent}. */
public abstract class JTextComponent extends vaadinx.swing.JComponent implements javax.swing.Scrollable, javax.accessibility.Accessible {

    /**
     * The JDK's own name for the {@code "focusAcceleratorKey"} bound property.
     * {@link #setFocusAccelerator} fires it <em>and</em> {@code "focusAccelerator"}
     * — the JDK fires both, with a source comment naming the compatibility bug
     * (4341002) that made it fire the wrong name first (D_owed_events).
     */
    public static final java.lang.String FOCUS_ACCELERATOR_KEY = "focusAcceleratorKey";

    /** Key the JDK registers its built-in keymap under; kept for API shape. */
    public static final java.lang.String DEFAULT_KEYMAP = "default";

    // The installed caret, which every caret and selection method reads and writes.
    // setCaret installs one during construction, as the JDK's text UI does.
    private javax.swing.text.Caret caret;

    // R_decline_effect_only state for the eight JTextComponent properties whose *effect* has no
    // Vaadin counterpart at this layer but whose state and notification are
    // pure Java and therefore owed (D_owed_events). Defaults are the JDK's field
    // initialisers, not its L&F-installed values: real Swing fills the colours
    // and margin from UIManager during UI install, which is out of scope per R_match_swing_errors
    // sub-bucket (b), so a null colour here means "no L&F ran", not "Swing
    // would report null".
    private java.awt.Color caretColor;
    private java.awt.Color selectionColor;
    private java.awt.Color selectedTextColor;
    private java.awt.Color disabledTextColor;
    private java.awt.Insets margin;
    private javax.swing.text.Highlighter highlighter;
    private javax.swing.text.Keymap keymap;
    private char focusAccelerator = '\0';

    // Swing-side source of truth for the component's text. setText
    // mutates this Document (which fires DocumentListener events); our
    // internal docToPeer listener (installed below when the peer is a
    // TextFieldBase) pushes changes into peer.setValue under the R_swing_is_truth
    // preventPeerEvents discipline. Reused from the JDK per D_whitelist_porting.
    private javax.swing.text.Document document;

    // Swing default: editable=true. Propagates to peer.setReadOnly when
    // the peer is a TextFieldBase so the HTML input actually rejects
    // typing; "editable" PCE fires regardless.
    private boolean editable = true;

    // R_swing_is_truth feedback-loop guard. Set true before writing to the "other"
    // side (peer from doc, or doc from peer) so the listener that
    // side's write triggers sees the flag and bails. finally always
    // clears it; lives per-instance because each JTextComponent has
    // its own sync round-trip. Protected so subclasses synchronising
    // additional state through the same seam (future JEditorPane?)
    // can use the same flag rather than inventing a parallel guard.
    protected boolean preventPeerEvents;

    // Single DocumentListener instance, hooked on whichever Document
    // is currently installed. setDocument below unhooks from the old
    // doc and re-hooks on the new one so mutations on a swapped
    // Document still mirror into the peer.
    private final javax.swing.event.DocumentListener docToPeer =
            new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) { onDocumentMutated(); }
                @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) { onDocumentMutated(); }
                @Override
                public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    // Attribute changes only — PlainDocument never fires
                    // this, and rich-text attributes don't round-trip to
                    // a plain Vaadin TextFieldBase peer. Safe no-op.
                }
            };

    public JTextComponent() {
        // Abstract class — the no-arg path is only reachable if a
        // subclass explicitly calls super() with no args (rare; our
        // concrete subclasses route through the peer ctor). Div peer
        // + WARN so unexpected callers surface in migration logs.
        this(new com.vaadin.flow.component.html.Div());
        vaadinx.EHelper.onUnimplemented("JTextComponent", "<init>");
    }

    protected JTextComponent(com.vaadin.flow.component.Component peer) {
        super(peer);
        initTextComponent();
    }

    /** The lazy form: see {@link vaadinx.awt.Component#Component(Class, java.util.function.Supplier)}. */
    protected <P extends com.vaadin.flow.component.Component> JTextComponent(Class<P> peerType,
            java.util.function.Supplier<? extends P> peerFactory) {
        super(peerType, peerFactory);
        initTextComponent();
    }

    private void initTextComponent() {
        // Install the default Document immediately so getText/setText
        // have something to read from / write to in every subclass that
        // doesn't replace it. Subclasses override createDefaultDocument
        // to pick a richer Document model (JTextArea reuses PlainDocument,
        // a future JEditorPane would pick an EditorKit-driven doc).
        this.document = createDefaultDocument();
        this.document.addDocumentListener(docToPeer);
        withPeer(this::installPeerSync);
        setCaret(new DefaultCaret());
        // The Basic text UI's blink rate, which the JDK installs with the caret.
        caret.setBlinkRate(500);
    }

    /**
     * Whether {@code peer} holds the Document's text as its String value. D_jformattedtextfield's
     * number-family peers (IntegerField / LongField / NumberField) and DatePicker also descend
     * from TextFieldBase but parameterise V to a non-String type — wiring the Document through
     * them would {@code (String) e.getValue()} ClassCastException on every value change; each
     * installs its own value-change bridge in the surrogate.
     */
    private static boolean holdsDocumentText(com.vaadin.flow.component.Component peer) {
        return peer instanceof com.vaadin.flow.component.textfield.TextField
                || peer instanceof com.vaadin.flow.component.textfield.PasswordField
                || peer instanceof com.vaadin.flow.component.textfield.TextArea;
    }

    /** The peer-side half of the R_swing_is_truth sync: a write, since it needs the peer. */
    private void installPeerSync(com.vaadin.flow.component.Component peer) {
        if (holdsDocumentText(peer)) {
            com.vaadin.flow.component.textfield.TextFieldBase<?, ?> tf =
                    (com.vaadin.flow.component.textfield.TextFieldBase<?, ?>) peer;
            // EAGER fires ValueChange on every keystroke — closer to
            // Swing's "Document updates while typing" contract than the
            // default ON_CHANGE (which fires only on blur/Enter).
            tf.setValueChangeMode(com.vaadin.flow.data.value.ValueChangeMode.EAGER);

            // Peer → Swing: typing in the browser updates the Document.
            // Wrapped in EHelper.callSwing per R_callswing_envelope so the UI-fiber
            // virtual-thread treatment lands in one place when it arrives.
            @SuppressWarnings("unchecked")
            com.vaadin.flow.component.HasValue<?, Object> hv =
                    (com.vaadin.flow.component.HasValue<?, Object>) tf;
            hv.addValueChangeListener(e -> {
                // R_swing_is_truth's feedback-loop guard has to be read BEFORE entering callSwing,
                // not just inside the callback. This event fires synchronously from
                // our own write-through (onDocumentMutated → setValue), so when the
                // flag is set there is no peer→Swing work to envelope at all — and
                // callSwing throws if no UI is current, turning a self-inflicted echo
                // that should be ignored into a hard failure. The guard inside
                // syncDocumentFromPeer stays, as defence in depth for its other caller.
                if (preventPeerEvents) return;
                vaadinx.EHelper.callSwing(() -> syncDocumentFromPeer((String) e.getValue()));
            });
        }

        if (peer instanceof com.vaadin.swingbridge.surrogates.swing.text.JTextComponentMixin m) {
            selectionReports = m.addSelectionReportListener(this::onBrowserSelection,
                    selectionReportsEager ? 0 : SELECTION_REPORT_DEBOUNCE_MS);
            // A render scheduled while detached has no UI to wait on; attach flushes it.
            // A detach drops a scheduled one, and the input a re-attach brings shows
            // nothing we rendered.
            peer.addAttachListener(e -> {
                if (caretRenderPending) {
                    caretRenderPending = false;
                    flushCaretRender();
                }
            });
            peer.addDetachListener(e -> {
                caretRenderScheduled = false;
                caretRenderPending = true;
                renderedStart = UNKNOWN;
            });
        }
    }

    /**
     * Push the current Document's text into the peer, guarded by
     * preventPeerEvents so the peer's ValueChangeListener (which fires
     * synchronously inside setValue) bails rather than round-tripping
     * back into the Document. No-op when the peer isn't a
     * TextFieldBase (e.g. the Div fallback ctor).
     */
    @SuppressWarnings("unchecked")
    private void onDocumentMutated() {
        if (preventPeerEvents) return;
        // Read the Document directly, not via getText() — JPasswordField
        // overrides getText() to mask with echoChar, and masked stars
        // should never reach the peer value. The Document always holds
        // the raw cleartext.
        String text = readDocument();
        // Only this push hops: the Document mutation, and the user's
        // DocumentListeners it fired, stay on the caller's thread.
        withPeer(p -> {
            // Non-String-valued TextFieldBase peers (number family, DatePicker) cannot
            // accept String via setValue, so the Document does not reach them here.
            if (!holdsDocumentText(p)) return;
            preventPeerEvents = true;
            try {
                ((com.vaadin.flow.component.HasValue<?, String>) p).setValue(text);
            } finally {
                preventPeerEvents = false;
            }
            // Setting an input's value puts its caret at the end (HTML's value setter).
            renderedStart = text.length();
            renderedEnd = text.length();
            renderedBackward = false;
            scheduleCaretRender(p);
        });
    }

    /**
     * Unmasked snapshot of the Document's text for internal sync use.
     * Bypasses subclass getText() overrides (JPasswordField masks its
     * return value with echoChar) so the peer always sees cleartext.
     */
    private String readDocument() {
        try {
            return document.getText(0, document.getLength());
        } catch (javax.swing.text.BadLocationException e) {
            vaadinx.EHelper.onUnsupported("JTextComponent", "readDocument", e);
            return "";
        }
    }

    /**
     * Mirror the peer's current value into the Document as the <em>edit</em> that
     * produced it, then let the Document have the last word.
     *
     * <p>Two properties, both of which a user-supplied {@code Document} depends on:
     *
     * <ul>
     *   <li><b>The Document sees a delta, not a wholesale replacement.</b> A filtering
     *       {@code PlainDocument} is written against per-keystroke inserts — it tests
     *       {@code getLength() + str.length()} against a cap, or branches on
     *       {@code str.equals(",")}. Handed the entire field value it either rejects
     *       an edit it would have allowed (capping the whole value, not the keystroke)
     *       or never takes its single-character branches at all.
     *   <li><b>The Document is authoritative.</b> After the edit, if the Document does
     *       not hold what the browser sent — a filter rejected the insert, capped it, or
     *       <em>rewrote</em> it (a thousands-separator formatter turning {@code 1234}
     *       into {@code 1,234}) — the Document's text is pushed back to the peer and the
     *       caret restored, so the browser shows what {@code getText()} would return.
     *       Swing has this for free: there, the field renders the Document.
     * </ul>
     *
     * <p>The Document mutation still fires events to user-registered DocumentListeners —
     * that's R_swing_is_truth's whole point. A rejection is ordinary filter behaviour, not an
     * incompleteness, so it does <em>not</em> WARN: the {@code BadLocationException} a
     * filter throws to refuse an edit is caught and answered by the push-back.
     */
    private void syncDocumentFromPeer(String peerValue) {
        if (preventPeerEvents) return;
        final String incoming = peerValue == null ? "" : peerValue;
        preventPeerEvents = true;
        try {
            applyPeerEdit(incoming);
        } catch (javax.swing.text.BadLocationException e) {
            // A filter refusing the edit. Nothing to report — the push-back below
            // reverts the browser, which is what refusal means.
        } finally {
            preventPeerEvents = false;
        }

        if (readDocument().equals(incoming)) {
            // The caret followed the edit as the Document dictates, and the browser's
            // own caret moved with the keystroke. Take them to agree; the browser's
            // next selection report corrects the caret where they do not.
            markCaretRendered();
        } else {
            // The filter changed or refused something: push the Document back, and the
            // caret with it — a reformatting filter moves it deliberately.
            onDocumentMutated();
        }
    }

    /**
     * Apply {@code incoming} to the Document as the single contiguous edit that turns
     * the Document's current text into it — the shape a keystroke, a delete or a paste
     * actually has. Derived from the common prefix and suffix, so an insert arrives as
     * an insert, a deletion as a remove, and a replacement as both.
     *
     * <p>Every pair of strings yields exactly one such edit, so there is no
     * "unrecognised change" case to fall back on. It need not be literally the
     * keystroke the user pressed (an IME commit or an autofill can collapse into one
     * edit that merely has the same effect) — what matters is that a filter sees an
     * edit of the right shape and size instead of the whole field.
     */
    private void applyPeerEdit(String incoming) throws javax.swing.text.BadLocationException {
        final String current = readDocument();
        if (current.equals(incoming)) return;

        final int shorter = Math.min(current.length(), incoming.length());
        int prefix = 0;
        while (prefix < shorter && current.charAt(prefix) == incoming.charAt(prefix)) prefix++;
        int suffix = 0;
        while (suffix < shorter - prefix
                && current.charAt(current.length() - 1 - suffix)
                        == incoming.charAt(incoming.length() - 1 - suffix)) {
            suffix++;
        }

        final int removeLen = current.length() - prefix - suffix;
        final String inserted = incoming.substring(prefix, incoming.length() - suffix);
        // Remove then insert, as Swing's own replace does — so a filter that overrides
        // only one of the two still sees its half. If insertString refuses, the removal
        // stands and the push-back syncs the browser to that state, again like Swing.
        if (removeLen > 0) document.remove(prefix, removeLen);
        if (!inserted.isEmpty()) document.insertString(prefix, inserted, null);
    }

    /**
     * Factory for the default {@link javax.swing.text.Document}. Real
     * Swing subclasses override to pick richer Document models (the
     * EditorKit-driven path in JEditorPane, etc.). Our base picks
     * {@link javax.swing.text.PlainDocument} — the simplest line-
     * oriented model, and what JTextField would pick anyway.
     */
    protected javax.swing.text.Document createDefaultDocument() {
        return new javax.swing.text.PlainDocument();
    }

    public void copy() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "copy");
    }

    public boolean print(java.text.MessageFormat arg0, java.text.MessageFormat arg1, boolean arg2, javax.print.PrintService arg3, javax.print.attribute.PrintRequestAttributeSet arg4, boolean arg5) throws java.awt.print.PrinterException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "print", arg0, arg1, arg2, arg3, arg4, arg5);
        return false;
    }

    public boolean print(java.text.MessageFormat arg0, java.text.MessageFormat arg1) throws java.awt.print.PrinterException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "print", arg0, arg1);
        return false;
    }

    public boolean print() throws java.awt.print.PrinterException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "print");
        return false;
    }

    public void write(java.io.Writer arg0) throws java.io.IOException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "write", arg0);
    }

    protected java.lang.String paramString() {
        // Chain to JComponent and append JTextComponent-specific state —
        // editable plus the current text. Matches real Swing's toString
        // shape so migrated debug-logging code stays readable.
        return super.paramString()
                + ",editable=" + editable
                + ",text=" + getText();
    }

    public void read(java.io.Reader arg0, java.lang.Object arg1) throws java.io.IOException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "read", arg0, arg1);
    }

    public java.lang.String getText() {
        // Reads the full Document. BadLocationException for (0, length)
        // on a live Document is effectively unreachable, but Document's
        // declared checked exception forces us to handle it — fall back
        // to empty string per D_never_fail_on_gaps's never-fail stance for reads.
        try {
            return document.getText(0, document.getLength());
        } catch (javax.swing.text.BadLocationException e) {
            vaadinx.EHelper.onUnsupported("JTextComponent", "getText", e);
            return "";
        }
    }

    public java.lang.String getText(int offs, int len) throws javax.swing.text.BadLocationException {
        // Overload preserves BadLocationException — it's a documented
        // checked exception here, and user code catches it to detect
        // out-of-range reads. D_never_fail_on_gaps keeps Swing's own failure modes.
        return document.getText(offs, len);
    }

    public void setEditable(boolean b) {
        // Store + fire PCE, then propagate to peer.setReadOnly so the
        // HTML input actually rejects typing. TextFieldBase exposes the
        // readOnly contract uniformly across TextField / PasswordField
        // / TextArea, so this lifts out of JTextField cleanly. Non-
        // TextFieldBase peers (Div fallback) stay field-only.
        boolean old = this.editable;
        if (old == b) return;
        this.editable = b;
        withPeer(p -> {
            if (p instanceof com.vaadin.flow.component.textfield.TextFieldBase<?, ?> tf) tf.setReadOnly(!b);
        });
        firePropertyChange("editable", old, b);
    }

    /**
     * Stores the flag; text-drag-out is the browser's to offer, and R_decline_effect_only
     * lets the effect go but not the state.
     */
    public void setDragEnabled(boolean arg0) {
        dragEnabled = arg0;
        vaadinx.EHelper.onNoop("JTextComponent", "setDragEnabled");
    }

    public void updateUI() {
        // L&F swap — no-op for us. Same shape as JButton / JPanel /
        // JLabel. Real Swing reinstalls a TextUI from UIManager; the
        // Vaadin peer isn't pluggable.
    }

    public void setUI(javax.swing.plaf.TextUI arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setUI", arg0);
    }

    public javax.swing.plaf.TextUI getUI() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getUI");
        return null;
    }

    public javax.swing.text.Document getDocument() {
        return document;
    }

    public void setComponentOrientation(java.awt.ComponentOrientation o) {
        // Component.setComponentOrientation writes the `dir` attribute
        // on the peer and fires PCE — that's the whole dispatch we
        // need. JTextComponent's real override additionally handles
        // caret direction (which we don't model — R_layouts_close_enough). Chain up so the
        // base behaviour fires; override kept per the "call super with
        // rationale" convention.
        super.setComponentOrientation(o);
    }

    public javax.swing.Action[] getActions() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getActions");
        return null;
    }

    public int viewToModel(java.awt.Point arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "viewToModel", arg0);
        return 0;
    }

    public static javax.swing.text.Keymap addKeymap(java.lang.String arg0, javax.swing.text.Keymap arg1) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "addKeymap", arg0, arg1);
        return null;
    }

    /** @return always {@code false}: the browser composes input-method text, so none reaches the Document uncommitted */
    protected boolean saveComposedText(int pos) {
        return false;
    }

    /** Restores nothing — see {@link #saveComposedText}. */
    protected void restoreComposedText() {
    }

    public java.awt.Rectangle modelToView(int arg0) throws javax.swing.text.BadLocationException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "modelToView", arg0);
        return null;
    }

    public java.awt.geom.Rectangle2D modelToView2D(int arg0) throws javax.swing.text.BadLocationException {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "modelToView2D", arg0);
        return null;
    }

    public int viewToModel2D(java.awt.geom.Point2D arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "viewToModel2D", arg0);
        return 0;
    }

    public boolean isEditable() {
        return editable;
    }

    public void cut() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "cut");
    }

    public void paste() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "paste");
    }

    public void setDocument(javax.swing.text.Document doc) {
        // Re-hook docToPeer across the swap so later edits still
        // mirror into the peer. Swing fires "document" PCE too.
        // Unhook first and re-hook after so the intermediate PCE
        // doesn't see a half-wired state. Push the new Document's
        // text to the peer so the UI reflects the swap immediately.
        javax.swing.text.Document old = this.document;
        if (old == doc) return;
        if (old != null) {
            old.removeDocumentListener(docToPeer);
        }
        this.document = doc;
        if (doc != null) {
            doc.addDocumentListener(docToPeer);
        }
        firePropertyChange("document", old, doc);
        if (doc != null) {
            onDocumentMutated();
        }
    }

    public void removeNotify() {
        // Real Swing's JTextComponent.removeNotify detaches the caret
        // and unregisters from the focus manager. Our model has
        // neither (R_layouts_close_enough, R_infra_not_surface); Component's DetachListener-driven
        // removeNotify (D_notify_from_attach) is enough. Chain kept to anchor the
        // rationale.
        super.removeNotify();
    }

    // --- Caret + selection -------------------------------------------
    //
    // The JDK's bodies over the installed caret. Rendering is rule 5 of
    // D_emulator_owned_state: every caret change schedules one flush
    // for the end of the request, which pushes the current selection only when it
    // differs from what the input shows. The browser reports its own caret moves
    // back through the Caret's public setDot / moveDot.

    /**
     * How long the browser holds a caret move before reporting it. Flow sends a held
     * event ahead of any other DOM event, so this bounds only how stale the caret can be
     * to code the browser did not start, a Timer or a worker. Zero once anything listens.
     */
    private static final int SELECTION_REPORT_DEBOUNCE_MS = 1000;

    /** A {@link #renderedStart} meaning the input's selection is not known. */
    private static final int UNKNOWN = -1;

    private com.vaadin.flow.shared.Registration selectionReports;
    private boolean selectionReportsEager;

    // What the peer's input shows, as far as we know.
    private int renderedStart = UNKNOWN;
    private int renderedEnd = UNKNOWN;
    private boolean renderedBackward;
    private boolean caretRenderScheduled;
    private boolean caretRenderPending;

    /**
     * The JDK's {@code MutableCaretEvent}: relays the caret's change to this component's
     * {@code CaretListener}s, and schedules the render. While a drag is active the relay
     * holds the listeners back and fires once at its end, as the JDK does between a mouse
     * press and its release; here a drag is a browser report that moves both ends.
     */
    private final class CaretRelay implements javax.swing.event.ChangeListener {
        boolean dragActive;

        @Override
        public void stateChanged(javax.swing.event.ChangeEvent e) {
            scheduleCaretRender();
            if (!dragActive) {
                fire();
            }
        }

        void fire() {
            fireCaretUpdate(new com.vaadin.swingbridge.surrogates.swing.text.SCaretEvent(
                    JTextComponent.this, caret.getDot(), caret.getMark()));
        }
    }

    private final CaretRelay caretEvent = new CaretRelay();

    private void scheduleCaretRender() {
        withPeer(this::scheduleCaretRender);
    }

    /** {@link #scheduleCaretRender()}'s body, for a write that already holds the peer. */
    private void scheduleCaretRender(com.vaadin.flow.component.Component p) {
        if (!(p instanceof com.vaadin.swingbridge.surrogates.swing.text.JTextComponentMixin)) return;
        if (caretRenderScheduled) return;
        java.util.Optional<com.vaadin.flow.component.UI> ui = p.getUI();
        if (ui.isEmpty()) {
            caretRenderPending = true;
            return;
        }
        caretRenderScheduled = true;
        ui.get().beforeClientResponse(p, ctx -> {
            caretRenderScheduled = false;
            flushCaretRender();
        });
    }

    /** Pushes the caret's selection to the input, unless the input already shows it. */
    private void flushCaretRender() {
        if (caret == null
                || !(getPeer() instanceof com.vaadin.swingbridge.surrogates.swing.text.JTextComponentMixin m)) {
            return;
        }
        int dot = caret.getDot();
        int mark = caret.getMark();
        int start = Math.min(dot, mark);
        int end = Math.max(dot, mark);
        boolean backward = dot < mark;
        if (start == renderedStart && end == renderedEnd && backward == renderedBackward) return;
        renderedStart = start;
        renderedEnd = end;
        renderedBackward = backward;
        m.renderSelection(start, end, backward);
    }

    /** Records that the input shows the caret's current selection. */
    private void markCaretRendered() {
        if (caret == null) return;
        int dot = caret.getDot();
        int mark = caret.getMark();
        renderedStart = Math.min(dot, mark);
        renderedEnd = Math.max(dot, mark);
        renderedBackward = dot < mark;
    }

    /**
     * A browser caret move, delivered the way a desktop mouse or key gesture reaches the
     * JDK's caret: a new anchor through {@code setDot}, an extension through
     * {@code moveDot}. So a {@link javax.swing.text.NavigationFilter} sees it and may
     * redirect it, and the render then pushes the redirected selection back.
     */
    private void onBrowserSelection(int start, int end, boolean backward) {
        renderedStart = start;
        renderedEnd = end;
        renderedBackward = backward && start != end;
        vaadinx.EHelper.callSwing(() -> {
            javax.swing.text.Caret c = caret;
            if (c == null) return;
            int newDot = backward ? start : end;
            int newMark = backward ? end : start;
            if (c.getDot() == newDot && c.getMark() == newMark) {
                // Nothing moved: the echo of a render, or a move a filter already undid.
            } else if (newDot == newMark) {
                // A click, or an arrow key collapsing the selection.
                c.setDot(newDot);
            } else if (c.getMark() == newMark) {
                // A shift-arrow or shift-click extending from the anchor.
                c.moveDot(newDot);
            } else {
                // A drag-select: a fresh anchor, then the extension.
                caretEvent.dragActive = true;
                try {
                    c.setDot(newMark);
                    c.moveDot(newDot);
                } finally {
                    caretEvent.dragActive = false;
                }
                caretEvent.fire();
            }
            scheduleCaretRender();
        });
    }

    /**
     * Reports every browser caret move at once while anything listens for caret changes,
     * since a listener expects each move as it happens; until then they are held.
     */
    void caretListenersChanged() {
        if (selectionReportsEager) return;
        boolean listened = listenerList.getListenerCount(javax.swing.event.CaretListener.class) > 0
                || (caret instanceof DefaultCaret dc && dc.getChangeListeners().length > 1);
        if (!listened) return;
        selectionReportsEager = true;
        // After installPeerSync's write, which made the debounced subscription this replaces.
        withPeer(p -> {
            if (!(p instanceof com.vaadin.swingbridge.surrogates.swing.text.JTextComponentMixin m)) return;
            if (selectionReports != null) selectionReports.remove();
            selectionReports = m.addSelectionReportListener(this::onBrowserSelection, 0);
        });
    }

    public int getSelectionEnd() {
        int end = Math.max(caret.getDot(), caret.getMark());
        return end;
    }

    /**
     * Selects {@code [selectionStart, selectionEnd]}, clamping both into the Document
     * and collapsing an end before the start onto the start, as the JDK does.
     */
    public void select(int selectionStart, int selectionEnd) {
        // argument adjustment done by java.awt.TextComponent
        int docLength = getDocument().getLength();

        if (selectionStart < 0) {
            selectionStart = 0;
        }
        if (selectionStart > docLength) {
            selectionStart = docLength;
        }
        if (selectionEnd > docLength) {
            selectionEnd = docLength;
        }
        if (selectionEnd < selectionStart) {
            selectionEnd = selectionStart;
        }

        setCaretPosition(selectionStart);
        moveCaretPosition(selectionEnd);
    }

    public int getSelectionStart() {
        int start = Math.min(caret.getDot(), caret.getMark());
        return start;
    }

    /** @throws IllegalArgumentException if {@code position} is outside the Document */
    public void setCaretPosition(int position) {
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            if (position > doc.getLength() || position < 0) {
                throw new IllegalArgumentException("bad position: " + position);
            }
            caret.setDot(position);
        }
    }

    /** @throws IllegalArgumentException if {@code pos} is outside the Document */
    public void moveCaretPosition(int pos) {
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            if (pos > doc.getLength() || pos < 0) {
                throw new IllegalArgumentException("bad position: " + pos);
            }
            caret.moveDot(pos);
        }
    }

    public java.lang.String getToolTipText(vaadinx.awt.event.MouseEvent arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getToolTipText", arg0);
        return null;
    }

    public java.awt.print.Printable getPrintable(java.text.MessageFormat arg0, java.text.MessageFormat arg1) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getPrintable", arg0, arg1);
        return null;
    }

    // processInputMethodEvent / addInputMethodListener are NOT redeclared here.
    // vaadinx.awt.Component owns both in ported types, and Component's own
    // dispatch routes an InputMethodEvent to its version — these were
    // java.awt.event-typed ghosts that shadowed nothing, so a migrator's
    // import-swapped call reached Component's method regardless (R_no_vaadin_in_api limb 1).

    /**
     * Replaces the selection with {@code content} through the Document, so a filter sees
     * the edit; with nothing selected, inserts at the caret. The caret then follows the
     * edit under its update policy, as it follows any other.
     */
    public void replaceSelection(java.lang.String content) {
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            try {
                boolean composedTextSaved = saveComposedText(caret.getDot());
                int p0 = Math.min(caret.getDot(), caret.getMark());
                int p1 = Math.max(caret.getDot(), caret.getMark());
                if (doc instanceof javax.swing.text.AbstractDocument) {
                    ((javax.swing.text.AbstractDocument) doc).replace(p0, p1 - p0, content, null);
                } else {
                    if (p0 != p1) {
                        doc.remove(p0, p1 - p0);
                    }
                    if (content != null && content.length() > 0) {
                        doc.insertString(p0, content, null);
                    }
                }
                if (composedTextSaved) {
                    restoreComposedText();
                }
            } catch (javax.swing.text.BadLocationException e) {
                // The JDK beeps (provideErrorFeedback); there is no beep to give.
            }
        }
    }

    public javax.swing.text.Keymap getKeymap() {
        return keymap;
    }

    public static javax.swing.text.Keymap getKeymap(java.lang.String arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getKeymap", arg0);
        return null;
    }

    public javax.swing.text.Caret getCaret() {
        return caret;
    }

    /**
     * Installs {@code c} as the caret every caret and selection method goes through, and
     * fires {@code "caret"}. A {@link DefaultCaret} is installed fully: it follows the
     * Document from here on and the peer renders it. Any other {@code Caret} is used but
     * not installed — WARN — since {@link javax.swing.text.Caret#install} takes the JDK's
     * {@code JTextComponent}, which this class is not; one that does its setup there
     * starts uninitialised.
     */
    public void setCaret(javax.swing.text.Caret c) {
        if (caret != null) {
            caret.removeChangeListener(caretEvent);
            if (caret instanceof DefaultCaret dc) {
                dc.deinstall(this);
            }
        }
        javax.swing.text.Caret old = caret;
        caret = c;
        if (caret != null) {
            if (caret instanceof DefaultCaret dc) {
                dc.install(this);
            } else {
                vaadinx.EHelper.onUnimplemented("JTextComponent", "setCaret(install)", c);
            }
            caret.addChangeListener(caretEvent);
            caretListenersChanged();
        }
        firePropertyChange("caret", old, caret);
        if (old != null) {
            scheduleCaretRender();
        }
    }

    public void addCaretListener(javax.swing.event.CaretListener listener) {
        listenerList.add(javax.swing.event.CaretListener.class, listener);
        caretListenersChanged();
    }

    public void removeCaretListener(javax.swing.event.CaretListener listener) {
        listenerList.remove(javax.swing.event.CaretListener.class, listener);
    }

    public javax.swing.event.CaretListener[] getCaretListeners() {
        return listenerList.getListeners(javax.swing.event.CaretListener.class);
    }

    /** Notifies the caret listeners, last registered first, as the JDK does. */
    protected void fireCaretUpdate(javax.swing.event.CaretEvent e) {
        Object[] listeners = listenerList.getListenerList();
        for (int i = listeners.length - 2; i >= 0; i -= 2) {
            if (listeners[i] == javax.swing.event.CaretListener.class) {
                ((javax.swing.event.CaretListener) listeners[i + 1]).caretUpdate(e);
            }
        }
    }

    /**
     * Stores the margin and fires {@code "margin"}; the pixel inset is not
     * pushed. Vaadin's text controls take their inner padding from theme
     * custom properties on a shadow part, not from an inline style on the host,
     * so honouring an {@code Insets} would need the shadow-root CSS mechanism
     * (SD_add_css_rule) extended to the input family — a separate pass, and R_layouts_close_enough territory
     * either way. State and notification are owed regardless (R_decline_effect_only, D_owed_events).
     */
    public void setMargin(java.awt.Insets arg0) {
        java.awt.Insets old = this.margin;
        this.margin = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setMargin(padding)", arg0);
        firePropertyChange("margin", old, arg0);
    }

    public java.awt.Insets getMargin() {
        return margin;
    }

    /**
     * Stores the filter and fires nothing, which is the JDK's whole body. The
     * {@link DefaultCaret} hands it every {@code setDot} / {@code moveDot}, the
     * browser's caret moves included.
     */
    public void setNavigationFilter(javax.swing.text.NavigationFilter filter) {
        navigationFilter = filter;
    }

    public javax.swing.text.NavigationFilter getNavigationFilter() {
        return navigationFilter;
    }

    private javax.swing.text.NavigationFilter navigationFilter;

    public javax.swing.text.Highlighter getHighlighter() {
        return highlighter;
    }

    /**
     * Stores the highlighter and fires {@code "highlighter"}; nothing is
     * painted. Highlight rendering is user-authored {@code Graphics} painting
     * (R_match_swing_errors sub-bucket (b)) — a {@code Highlighter.HighlightPainter} draws
     * directly onto a {@code Graphics}, which has no counterpart in the DOM.
     * As with {@link #setCaret}, the JDK's {@code install} / {@code deinstall}
     * pair takes the JDK's own {@code JTextComponent} and so cannot be called
     * from here. State and notification are owed regardless (R_decline_effect_only, D_owed_events).
     */
    public void setHighlighter(javax.swing.text.Highlighter arg0) {
        javax.swing.text.Highlighter old = this.highlighter;
        this.highlighter = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setHighlighter(paint)", arg0);
        firePropertyChange("highlighter", old, arg0);
    }

    /**
     * Stores the keymap and fires {@code "keymap"}; the keymap itself dispatches
     * nothing. Real key dispatch is permanently out of scope per
     * {@link vaadinx.swing.FocusManager} / D_focus_managers, so what is declined here is the
     * effect only — the state and the notification are owed (R_decline_effect_only, D_owed_events). The
     * JDK's trailing {@code updateInputMap(old, map)}, which republishes the
     * keymap's bindings into the component's {@code InputMap}, is not
     * reproduced: SB-Emulators' InputMap is driven from
     * {@link vaadinx.swing.JComponent#registerKeyboardAction} instead.
     */
    public void setKeymap(javax.swing.text.Keymap arg0) {
        javax.swing.text.Keymap old = this.keymap;
        this.keymap = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setKeymap(dispatch)", arg0);
        firePropertyChange("keymap", old, arg0);
    }

    public boolean getDragEnabled() {
        return dragEnabled;
    }

    /**
     * Stores the mode, accepting the two a text component accepts and rejecting the other
     * six with Swing's own exception type — {@code USE_SELECTION} and {@code INSERT} only,
     * measured on JDK 25 (the ON / ROWS / COLS modes belong to list, table and tree).
     */
    public final void setDropMode(javax.swing.DropMode arg0) {
        if (arg0 != null && arg0 != javax.swing.DropMode.USE_SELECTION
                && arg0 != javax.swing.DropMode.INSERT) {
            throw new IllegalArgumentException(arg0 + ": Unsupported drop mode for text");
        }
        dropMode = arg0;
        vaadinx.EHelper.onNoop("JTextComponent", "setDropMode");
    }

    public final javax.swing.DropMode getDropMode() {
        return dropMode;
    }

    /** Text-drag-out flag — stored per R_decline_effect_only; the browser owns dragging. */
    private boolean dragEnabled;

    /** Drop mode, defaulting to {@code USE_SELECTION} as the JDK's does. */
    private javax.swing.DropMode dropMode = javax.swing.DropMode.USE_SELECTION;

    public static javax.swing.text.Keymap removeKeymap(java.lang.String arg0) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "removeKeymap", arg0);
        return null;
    }

    public java.awt.Color getCaretColor() {
        return caretColor;
    }

    /**
     * The one colour of the four with a real effect: {@code caret-color} is an
     * <em>inherited</em> CSS property, so a declaration on the peer's host
     * element reaches the {@code <input>} inside Vaadin's shadow root without
     * needing a shadow-part rule. A theme that sets {@code caret-color} on that
     * inner element directly would still win — the declaration is pushed, not
     * enforced. Null removes it, letting inheritance resume.
     */
    public void setCaretColor(java.awt.Color arg0) {
        java.awt.Color old = this.caretColor;
        this.caretColor = arg0;
        withPeer(p -> {
            com.vaadin.flow.dom.Style style = p.getElement().getStyle();
            if (arg0 != null) {
                style.set("caret-color", com.vaadin.swingbridge.surrogates.util.CssConvert.toCss(arg0));
            } else {
                style.remove("caret-color");
            }
        });
        firePropertyChange("caretColor", old, arg0);
    }

    public java.awt.Color getSelectionColor() {
        return selectionColor;
    }

    /**
     * Stores and fires; no paint. Selection colours live behind the
     * {@code ::selection} pseudo-element, which cannot be expressed as an
     * inline style and so needs the shadow-root CSS mechanism (SD_add_css_rule) extended
     * past the RTE — the same blocker as {@link #setSelectedTextColor} and
     * {@link #setDisabledTextColor}. State and notification are owed
     * regardless (R_decline_effect_only, D_owed_events).
     */
    public void setSelectionColor(java.awt.Color arg0) {
        java.awt.Color old = this.selectionColor;
        this.selectionColor = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setSelectionColor(paint)", arg0);
        firePropertyChange("selectionColor", old, arg0);
    }

    public java.awt.Color getSelectedTextColor() {
        return selectedTextColor;
    }

    /** Stores and fires; no paint — see {@link #setSelectionColor}. */
    public void setSelectedTextColor(java.awt.Color arg0) {
        java.awt.Color old = this.selectedTextColor;
        this.selectedTextColor = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setSelectedTextColor(paint)", arg0);
        firePropertyChange("selectedTextColor", old, arg0);
    }

    public java.awt.Color getDisabledTextColor() {
        return disabledTextColor;
    }

    /**
     * Stores and fires; no paint. Needs a {@code :disabled} rule inside the
     * peer's shadow root — see {@link #setSelectionColor}.
     */
    public void setDisabledTextColor(java.awt.Color arg0) {
        java.awt.Color old = this.disabledTextColor;
        this.disabledTextColor = arg0;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setDisabledTextColor(paint)", arg0);
        firePropertyChange("disabledTextColor", old, arg0);
    }

    /**
     * Uppercases the key, stores it, and fires <b>two</b> events —
     * {@link #FOCUS_ACCELERATOR_KEY} (i.e. {@code "focusAcceleratorKey"}) and
     * {@code "focusAccelerator"} — because the JDK fires both, deliberately:
     * its own source comments the compatibility bug (4341002) that shipped the
     * wrong name and the added correct one. Both carry the <em>uppercased</em>
     * value, so a listener never sees the argument as passed.
     *
     * <p>The Alt+key focus jump itself is not wired — that would be a Vaadin
     * {@code Shortcuts} registration — so this declines the <em>effect</em> only:
     * state and notification are owed regardless (R_decline_effect_only,
     * D_owed_events).
     */
    public void setFocusAccelerator(char arg0) {
        char upper = Character.toUpperCase(arg0);
        char old = this.focusAccelerator;
        this.focusAccelerator = upper;
        vaadinx.EHelper.onUnimplemented("JTextComponent", "setFocusAccelerator(shortcut)", arg0);
        firePropertyChange(FOCUS_ACCELERATOR_KEY, old, upper);
        firePropertyChange("focusAccelerator", old, upper);
    }

    public char getFocusAccelerator() {
        return focusAccelerator;
    }

    /**
     * @return the caret's dot. A caret the user moved in the browser has reached it by the
     *     time the server handles the next event the browser sends, and within a second
     *     otherwise
     */
    public int getCaretPosition() {
        return caret.getDot();
    }

    /**
     * Replaces the Document's text in one {@code replace}, so a {@code DocumentFilter}
     * sees a replace; a Document that is not an {@code AbstractDocument} gets a remove
     * and an insert.
     */
    public void setText(java.lang.String t) {
        try {
            javax.swing.text.Document doc = getDocument();
            if (doc instanceof javax.swing.text.AbstractDocument) {
                ((javax.swing.text.AbstractDocument) doc).replace(0, doc.getLength(), t, null);
            } else {
                doc.remove(0, doc.getLength());
                doc.insertString(0, t, null);
            }
        } catch (javax.swing.text.BadLocationException e) {
            // The JDK beeps (provideErrorFeedback); there is no beep to give.
        }
    }

    /**
     * @return the selected text, or {@code null} when nothing is selected
     * @throws IllegalArgumentException when the selection runs past the Document, which
     *     {@code getCaret().moveDot} can leave it doing
     */
    public java.lang.String getSelectedText() {
        java.lang.String txt = null;
        int p0 = Math.min(caret.getDot(), caret.getMark());
        int p1 = Math.max(caret.getDot(), caret.getMark());
        if (p0 != p1) {
            try {
                javax.swing.text.Document doc = getDocument();
                txt = doc.getText(p0, p1 - p0);
            } catch (javax.swing.text.BadLocationException e) {
                throw new IllegalArgumentException(e.getMessage());
            }
        }
        return txt;
    }

    /** Routes through {@link #select}, as the JDK does, so both ends clamp alike. */
    public void setSelectionStart(int selectionStart) {
        select(selectionStart, getSelectionEnd());
    }

    /** Routes through {@link #select}, as the JDK does, so both ends clamp alike. */
    public void setSelectionEnd(int selectionEnd) {
        select(getSelectionStart(), selectionEnd);
    }

    public void selectAll() {
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            setCaretPosition(0);
            moveCaretPosition(doc.getLength());
        }
    }

    public java.awt.Dimension getPreferredScrollableViewportSize() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getPreferredScrollableViewportSize");
        return null;
    }

    public int getScrollableUnitIncrement(java.awt.Rectangle arg0, int arg1, int arg2) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getScrollableUnitIncrement", arg0, arg1, arg2);
        return 0;
    }

    public int getScrollableBlockIncrement(java.awt.Rectangle arg0, int arg1, int arg2) {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getScrollableBlockIncrement", arg0, arg1, arg2);
        return 0;
    }

    public boolean getScrollableTracksViewportWidth() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getScrollableTracksViewportWidth");
        return false;
    }

    public boolean getScrollableTracksViewportHeight() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getScrollableTracksViewportHeight");
        return false;
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getAccessibleContext");
        return null;
    }

    public java.awt.im.InputMethodRequests getInputMethodRequests() {
        vaadinx.EHelper.onUnimplemented("JTextComponent", "getInputMethodRequests");
        return null;
    }

}
