/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

import java.awt.AWTEvent;

/**
 * Surrogate-side port of {@link javax.swing.event.AncestorEvent}. Source
 * type retyped from {@link javax.swing.JComponent} to Vaadin
 * {@link com.vaadin.flow.component.Component}; ancestor / ancestorParent
 * retyped from {@link java.awt.Container} to {@link Component} for the
 * same reason (SD_event_port_stance).
 *
 * <p>Constants ({@link #ANCESTOR_ADDED} / {@link #ANCESTOR_REMOVED} /
 * {@link #ANCESTOR_MOVED}) preserved verbatim from JDK so id-arithmetic
 * carries across.
 */
public class SAncestorEvent extends AWTEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int ANCESTOR_ADDED = javax.swing.event.AncestorEvent.ANCESTOR_ADDED;
    public static final int ANCESTOR_MOVED = javax.swing.event.AncestorEvent.ANCESTOR_MOVED;
    public static final int ANCESTOR_REMOVED = javax.swing.event.AncestorEvent.ANCESTOR_REMOVED;
    // --- end generated constants ---

    private final Component ancestor;
    private final Component ancestorParent;

    /**
     * @param source the component whose ancestor relationship changed
     * @param id one of {@link #ANCESTOR_ADDED} / {@link #ANCESTOR_REMOVED} /
     *           {@link #ANCESTOR_MOVED}
     * @param ancestor the ancestor component that was added / removed /
     *                 moved (typically the source itself for direct
     *                 attach/detach events)
     * @param ancestorParent the ancestor's parent at the moment of the
     *                       event ({@code null} when the source has no
     *                       parent)
     */
    public SAncestorEvent(Component source, int id, Component ancestor, Component ancestorParent) {
        super(source, id);
        this.ancestor = ancestor;
        this.ancestorParent = ancestorParent;
    }

    /** The ancestor whose state changed. */
    public Component getAncestor() {
        return ancestor;
    }

    /** Parent of {@link #getAncestor()} at the time of the event. */
    public Component getAncestorParent() {
        return ancestorParent;
    }

    /** Convenience — same as {@code (Component) getSource()}. */
    public Component getComponent() {
        return (source instanceof Component c) ? c : null;
    }

    @Override
    public String paramString() {
        return switch (id) {
            case ANCESTOR_ADDED   -> "ANCESTOR_ADDED";
            case ANCESTOR_REMOVED -> "ANCESTOR_REMOVED";
            case ANCESTOR_MOVED   -> "ANCESTOR_MOVED";
            default               -> "unknown type";
        };
    }
}
