/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

import java.awt.AWTEvent;

/**
 * Surrogate-side port of {@link java.awt.event.ComponentEvent}. Source type
 * retyped from {@link java.awt.Component} to {@link com.vaadin.flow.component.Component}
 * because our surrogates are Vaadin components, not AWT components (SD_event_port_stance).
 *
 * <p>Constants preserved verbatim so bitmask/ID arithmetic carries across
 * unchanged. Extends JDK {@link AWTEvent} unchanged — its source field is
 * typed as {@code Object}, so reuse is fine (no port needed).
 */
public class SComponentEvent extends AWTEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int COMPONENT_FIRST = java.awt.event.ComponentEvent.COMPONENT_FIRST;
    public static final int COMPONENT_HIDDEN = java.awt.event.ComponentEvent.COMPONENT_HIDDEN;
    public static final int COMPONENT_LAST = java.awt.event.ComponentEvent.COMPONENT_LAST;
    public static final int COMPONENT_MOVED = java.awt.event.ComponentEvent.COMPONENT_MOVED;
    public static final int COMPONENT_RESIZED = java.awt.event.ComponentEvent.COMPONENT_RESIZED;
    public static final int COMPONENT_SHOWN = java.awt.event.ComponentEvent.COMPONENT_SHOWN;
    // --- end generated constants ---

    public SComponentEvent(Component source, int id) {
        super(source, id);
    }

    /** The Vaadin component that originated this event. */
    public Component getComponent() {
        return (source instanceof Component c) ? c : null;
    }

    @Override
    public String paramString() {
        return switch (id) {
            case COMPONENT_MOVED   -> "COMPONENT_MOVED";
            case COMPONENT_RESIZED -> "COMPONENT_RESIZED";
            case COMPONENT_SHOWN   -> "COMPONENT_SHOWN";
            case COMPONENT_HIDDEN  -> "COMPONENT_HIDDEN";
            default                -> "unknown type";
        };
    }
}
