/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

/**
 * Surrogate-side port of {@link java.awt.event.ContainerEvent}. Extends
 * {@link SComponentEvent} (its supertype's port). Constants preserved
 * verbatim. Source and child types retyped to Vaadin
 * {@link com.vaadin.flow.component.Component}.
 *
 * <p>Type exists for callers to construct, but no firing path
 * is wired — see SD_event_port_stance.
 */
public class SContainerEvent extends SComponentEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int COMPONENT_ADDED = java.awt.event.ContainerEvent.COMPONENT_ADDED;
    public static final int COMPONENT_REMOVED = java.awt.event.ContainerEvent.COMPONENT_REMOVED;
    public static final int CONTAINER_FIRST = java.awt.event.ContainerEvent.CONTAINER_FIRST;
    public static final int CONTAINER_LAST = java.awt.event.ContainerEvent.CONTAINER_LAST;
    // --- end generated constants ---

    private final Component child;

    public SContainerEvent(Component source, int id, Component child) {
        super(source, id);
        this.child = child;
    }

    /** Same as {@link #getComponent()} but typed to clarify intent. */
    public Component getContainer() {
        return getComponent();
    }

    public Component getChild() {
        return child;
    }

    @Override
    public String paramString() {
        String typeStr = switch (id) {
            case COMPONENT_ADDED   -> "COMPONENT_ADDED";
            case COMPONENT_REMOVED -> "COMPONENT_REMOVED";
            default                -> "unknown type";
        };
        return typeStr + ",child=" + (child == null ? "null" : child.getClass().getSimpleName());
    }
}
