/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

/**
 * Surrogate-side port of {@link java.awt.event.FocusEvent}. Source type
 * retyped from {@link java.awt.Component} to {@link com.vaadin.flow.component.Component};
 * {@code opposite} likewise (SD_event_port_stance rationale).
 *
 * <p>The {@link java.awt.event.FocusEvent.Cause} enum is deliberately not
 * carried in any constructor overload here — it's a JDK-9+ refinement
 * layered onto an API we already cover with the original two-/three-arg
 * shape. No migration target reads {@code getCause()} today; add when one
 * surfaces.
 */
public class SFocusEvent extends SComponentEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int FOCUS_FIRST = java.awt.event.FocusEvent.FOCUS_FIRST;
    public static final int FOCUS_GAINED = java.awt.event.FocusEvent.FOCUS_GAINED;
    public static final int FOCUS_LAST = java.awt.event.FocusEvent.FOCUS_LAST;
    public static final int FOCUS_LOST = java.awt.event.FocusEvent.FOCUS_LOST;
    // --- end generated constants ---

    private final boolean temporary;
    private final Component opposite;

    public SFocusEvent(Component source, int id) {
        this(source, id, false, null);
    }

    public SFocusEvent(Component source, int id, boolean temporary) {
        this(source, id, temporary, null);
    }

    public SFocusEvent(Component source, int id, boolean temporary, Component opposite) {
        super(source, id);
        this.temporary = temporary;
        this.opposite = opposite;
    }

    /**
     * JDK's {@code FocusEvent.isTemporary} — true for cross-window focus
     * changes the browser considers ephemeral. Our wiring passes
     * {@code false} uniformly; the field is preserved for completeness and
     * for migrated code that reads it through our ported listener.
     */
    public boolean isTemporary() {
        return temporary;
    }

    /**
     * The component losing/gaining focus on the other end of the transition,
     * or {@code null} when unknown (our peer subscriptions don't receive
     * the opposite from Vaadin). Matches JDK's {@code null} contract for
     * unknown opposite.
     */
    public Component getOppositeComponent() {
        return opposite;
    }

    @Override
    public String paramString() {
        String type = switch (id) {
            case FOCUS_GAINED -> "FOCUS_GAINED";
            case FOCUS_LOST   -> "FOCUS_LOST";
            default           -> "unknown type";
        };
        return type + (temporary ? ",temporary" : ",permanent")
                + (opposite != null ? ",opposite=" + opposite : "");
    }
}
