/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

/**
 * Surrogate-side port of {@link java.awt.event.HierarchyEvent}. Source,
 * {@code changed}, and {@code changedParent} all retyped from
 * {@link java.awt.Component} / {@link java.awt.Container} to Vaadin
 * {@link com.vaadin.flow.component.Component} — the surrogate world has
 * no separate Container type (SD_event_port_stance rationale).
 *
 * <p>The change-flag constants <em>are</em> AWT's, by delegation rather than by value, so bitmask
 * arithmetic on {@code getChangeFlags()} results carries across unchanged; the block is emitted by
 * {@code DelegatedConstantsTest} from AWT's public runtime API. Delegation also settles what used
 * to need a comment here: {@code HIERARCHY_LAST} tracks whatever AWT says it is, rather than a
 * literal that would leave {@code ANCESTOR_RESIZED} outside every {@code id <= HIERARCHY_LAST}
 * range check (D_missing_constants).
 */
public class SHierarchyEvent extends SComponentEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int ANCESTOR_MOVED = java.awt.event.HierarchyEvent.ANCESTOR_MOVED;
    public static final int ANCESTOR_RESIZED = java.awt.event.HierarchyEvent.ANCESTOR_RESIZED;
    public static final int DISPLAYABILITY_CHANGED = java.awt.event.HierarchyEvent.DISPLAYABILITY_CHANGED;
    public static final int HIERARCHY_CHANGED = java.awt.event.HierarchyEvent.HIERARCHY_CHANGED;
    public static final int HIERARCHY_FIRST = java.awt.event.HierarchyEvent.HIERARCHY_FIRST;
    public static final int HIERARCHY_LAST = java.awt.event.HierarchyEvent.HIERARCHY_LAST;
    public static final int PARENT_CHANGED = java.awt.event.HierarchyEvent.PARENT_CHANGED;
    public static final int SHOWING_CHANGED = java.awt.event.HierarchyEvent.SHOWING_CHANGED;
    // --- end generated constants ---

    private final Component changed;
    private final Component changedParent;
    private final long changeFlags;

    public SHierarchyEvent(Component source, int id, Component changed, Component changedParent) {
        this(source, id, changed, changedParent, 0);
    }

    public SHierarchyEvent(Component source, int id, Component changed,
                           Component changedParent, long changeFlags) {
        super(source, id);
        this.changed = changed;
        this.changedParent = changedParent;
        this.changeFlags = changeFlags;
    }

    /** The component whose hierarchy state changed (may equal the source). */
    public Component getChanged() {
        return changed;
    }

    /**
     * The parent of {@code changed} at the moment the event fires. For
     * {@link #HIERARCHY_CHANGED} on a newly-attached component this is
     * the new parent; on a detach this is the old parent. JDK's contract
     * is identical — see {@link java.awt.event.HierarchyEvent#getChangedParent()}.
     */
    public Component getChangedParent() {
        return changedParent;
    }

    /**
     * Bit-or of the {@link #PARENT_CHANGED} / {@link #DISPLAYABILITY_CHANGED}
     * / {@link #SHOWING_CHANGED} flags describing what about the hierarchy
     * actually changed. Only meaningful for {@link #HIERARCHY_CHANGED};
     * returns 0 for the ancestor-moved/resized events.
     */
    public long getChangeFlags() {
        return changeFlags;
    }

    @Override
    public String paramString() {
        String type = switch (id) {
            case HIERARCHY_CHANGED -> "HIERARCHY_CHANGED";
            case ANCESTOR_MOVED    -> "ANCESTOR_MOVED";
            case ANCESTOR_RESIZED  -> "ANCESTOR_RESIZED";
            default                -> "unknown type";
        };
        return type + ",changeFlags=" + changeFlags;
    }
}
