/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

/**
 * Surrogate-side port of {@link java.awt.event.InputEvent}. Abstract parent of
 * {@link SKeyEvent} and {@link SMouseEvent}. Source retyped from
 * {@link java.awt.Component} to
 * {@link com.vaadin.flow.component.Component} for the same SD_event_port_stance reason
 * {@link SComponentEvent} needs porting — surrogates are Vaadin components,
 * not AWT components.
 *
 * <p>Every modifier constant below <em>is</em> AWT's, by delegation rather than by value, so bit
 * arithmetic carries across unchanged and stays correct however AWT evolves; the deprecated
 * {@code *_MASK} set is republished for user code that hasn't migrated. Static utilities delegate
 * for the same reason. The block is emitted by {@code DelegatedConstantsTest} from
 * {@link java.awt.event.InputEvent}'s public runtime API — see that test before editing it by hand.
 */
public abstract class SInputEvent extends SComponentEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int ALT_DOWN_MASK = java.awt.event.InputEvent.ALT_DOWN_MASK;
    public static final int ALT_GRAPH_DOWN_MASK = java.awt.event.InputEvent.ALT_GRAPH_DOWN_MASK;
    @Deprecated
    public static final int ALT_GRAPH_MASK = java.awt.event.InputEvent.ALT_GRAPH_MASK;
    @Deprecated
    public static final int ALT_MASK = java.awt.event.InputEvent.ALT_MASK;
    public static final int BUTTON1_DOWN_MASK = java.awt.event.InputEvent.BUTTON1_DOWN_MASK;
    @Deprecated
    public static final int BUTTON1_MASK = java.awt.event.InputEvent.BUTTON1_MASK;
    public static final int BUTTON2_DOWN_MASK = java.awt.event.InputEvent.BUTTON2_DOWN_MASK;
    @Deprecated
    public static final int BUTTON2_MASK = java.awt.event.InputEvent.BUTTON2_MASK;
    public static final int BUTTON3_DOWN_MASK = java.awt.event.InputEvent.BUTTON3_DOWN_MASK;
    @Deprecated
    public static final int BUTTON3_MASK = java.awt.event.InputEvent.BUTTON3_MASK;
    public static final int CTRL_DOWN_MASK = java.awt.event.InputEvent.CTRL_DOWN_MASK;
    @Deprecated
    public static final int CTRL_MASK = java.awt.event.InputEvent.CTRL_MASK;
    public static final int META_DOWN_MASK = java.awt.event.InputEvent.META_DOWN_MASK;
    @Deprecated
    public static final int META_MASK = java.awt.event.InputEvent.META_MASK;
    public static final int SHIFT_DOWN_MASK = java.awt.event.InputEvent.SHIFT_DOWN_MASK;
    @Deprecated
    public static final int SHIFT_MASK = java.awt.event.InputEvent.SHIFT_MASK;
    // --- end generated constants ---

    private final long when;
    private final int modifiers;

    protected SInputEvent(Component source, int id, long when, int modifiers) {
        super(source, id);
        this.when = when;
        this.modifiers = modifiers;
    }

    public long getWhen() {
        return when;
    }

    /**
     * Legacy-modifier accessor; deprecated in AWT. We store only the extended
     * set and return it verbatim — user code checking specific bits should
     * use {@link #getModifiersEx()} with the {@code *_DOWN_MASK} constants.
     */
    @Deprecated
    public int getModifiers() {
        return modifiers;
    }

    public int getModifiersEx() {
        return modifiers;
    }

    public boolean isShiftDown()     { return (modifiers & SHIFT_DOWN_MASK) != 0; }
    public boolean isControlDown()   { return (modifiers & CTRL_DOWN_MASK) != 0; }
    public boolean isMetaDown()      { return (modifiers & META_DOWN_MASK) != 0; }
    public boolean isAltDown()       { return (modifiers & ALT_DOWN_MASK) != 0; }
    public boolean isAltGraphDown()  { return (modifiers & ALT_GRAPH_DOWN_MASK) != 0; }

    /** Delegates to AWT — constants match. */
    public static int getMaskForButton(int button) {
        return java.awt.event.InputEvent.getMaskForButton(button);
    }

    /** Delegates to AWT — constants match and formatting is locale-aware. */
    public static String getModifiersExText(int modifiers) {
        return java.awt.event.InputEvent.getModifiersExText(modifiers);
    }
}
