/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;
import com.vaadin.swingbridge.surrogates.SHelper;

/**
 * Surrogate-side port of {@link java.awt.event.KeyEvent}. Extends
 * {@link SInputEvent} so the full modifier API (isShiftDown, etc.) is
 * available. Source retyped from {@link java.awt.Component} to
 * {@link com.vaadin.flow.component.Component} per SD_event_port_stance.
 *
 * <p>The {@code VK_*} constant surface below <em>is</em> AWT's, by delegation rather than by
 * value: republishing it here means migrated code needs no parallel
 * {@code java.awt.event.KeyEvent} import, while every value remains AWT's own and stays correct
 * however AWT evolves. For the same reason {@link #getKeyText(int)} and {@link #isActionKey()}
 * answer by asking AWT rather than carrying a second copy of its tables. The block is emitted by
 * {@code DelegatedConstantsTest} from AWT's public runtime API — read that test before editing it
 * by hand. Mirrors the emulator-side {@code vaadinx.awt.event.KeyEvent} port, which keeps its own
 * copy (SD_shelper_statics: cross-module reuse is disallowed, so the constants exist twice
 * — accepted).
 */
public class SKeyEvent extends SInputEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final char CHAR_UNDEFINED = java.awt.event.KeyEvent.CHAR_UNDEFINED;
    public static final int KEY_FIRST = java.awt.event.KeyEvent.KEY_FIRST;
    public static final int KEY_LAST = java.awt.event.KeyEvent.KEY_LAST;
    public static final int KEY_LOCATION_LEFT = java.awt.event.KeyEvent.KEY_LOCATION_LEFT;
    public static final int KEY_LOCATION_NUMPAD = java.awt.event.KeyEvent.KEY_LOCATION_NUMPAD;
    public static final int KEY_LOCATION_RIGHT = java.awt.event.KeyEvent.KEY_LOCATION_RIGHT;
    public static final int KEY_LOCATION_STANDARD = java.awt.event.KeyEvent.KEY_LOCATION_STANDARD;
    public static final int KEY_LOCATION_UNKNOWN = java.awt.event.KeyEvent.KEY_LOCATION_UNKNOWN;
    public static final int KEY_PRESSED = java.awt.event.KeyEvent.KEY_PRESSED;
    public static final int KEY_RELEASED = java.awt.event.KeyEvent.KEY_RELEASED;
    public static final int KEY_TYPED = java.awt.event.KeyEvent.KEY_TYPED;
    public static final int VK_0 = java.awt.event.KeyEvent.VK_0;
    public static final int VK_1 = java.awt.event.KeyEvent.VK_1;
    public static final int VK_2 = java.awt.event.KeyEvent.VK_2;
    public static final int VK_3 = java.awt.event.KeyEvent.VK_3;
    public static final int VK_4 = java.awt.event.KeyEvent.VK_4;
    public static final int VK_5 = java.awt.event.KeyEvent.VK_5;
    public static final int VK_6 = java.awt.event.KeyEvent.VK_6;
    public static final int VK_7 = java.awt.event.KeyEvent.VK_7;
    public static final int VK_8 = java.awt.event.KeyEvent.VK_8;
    public static final int VK_9 = java.awt.event.KeyEvent.VK_9;
    public static final int VK_A = java.awt.event.KeyEvent.VK_A;
    public static final int VK_ACCEPT = java.awt.event.KeyEvent.VK_ACCEPT;
    public static final int VK_ADD = java.awt.event.KeyEvent.VK_ADD;
    public static final int VK_AGAIN = java.awt.event.KeyEvent.VK_AGAIN;
    public static final int VK_ALL_CANDIDATES = java.awt.event.KeyEvent.VK_ALL_CANDIDATES;
    public static final int VK_ALPHANUMERIC = java.awt.event.KeyEvent.VK_ALPHANUMERIC;
    public static final int VK_ALT = java.awt.event.KeyEvent.VK_ALT;
    public static final int VK_ALT_GRAPH = java.awt.event.KeyEvent.VK_ALT_GRAPH;
    public static final int VK_AMPERSAND = java.awt.event.KeyEvent.VK_AMPERSAND;
    public static final int VK_ASTERISK = java.awt.event.KeyEvent.VK_ASTERISK;
    public static final int VK_AT = java.awt.event.KeyEvent.VK_AT;
    public static final int VK_B = java.awt.event.KeyEvent.VK_B;
    public static final int VK_BACK_QUOTE = java.awt.event.KeyEvent.VK_BACK_QUOTE;
    public static final int VK_BACK_SLASH = java.awt.event.KeyEvent.VK_BACK_SLASH;
    public static final int VK_BACK_SPACE = java.awt.event.KeyEvent.VK_BACK_SPACE;
    public static final int VK_BEGIN = java.awt.event.KeyEvent.VK_BEGIN;
    public static final int VK_BRACELEFT = java.awt.event.KeyEvent.VK_BRACELEFT;
    public static final int VK_BRACERIGHT = java.awt.event.KeyEvent.VK_BRACERIGHT;
    public static final int VK_C = java.awt.event.KeyEvent.VK_C;
    public static final int VK_CANCEL = java.awt.event.KeyEvent.VK_CANCEL;
    public static final int VK_CAPS_LOCK = java.awt.event.KeyEvent.VK_CAPS_LOCK;
    public static final int VK_CIRCUMFLEX = java.awt.event.KeyEvent.VK_CIRCUMFLEX;
    public static final int VK_CLEAR = java.awt.event.KeyEvent.VK_CLEAR;
    public static final int VK_CLOSE_BRACKET = java.awt.event.KeyEvent.VK_CLOSE_BRACKET;
    public static final int VK_CODE_INPUT = java.awt.event.KeyEvent.VK_CODE_INPUT;
    public static final int VK_COLON = java.awt.event.KeyEvent.VK_COLON;
    public static final int VK_COMMA = java.awt.event.KeyEvent.VK_COMMA;
    public static final int VK_COMPOSE = java.awt.event.KeyEvent.VK_COMPOSE;
    public static final int VK_CONTEXT_MENU = java.awt.event.KeyEvent.VK_CONTEXT_MENU;
    public static final int VK_CONTROL = java.awt.event.KeyEvent.VK_CONTROL;
    public static final int VK_CONVERT = java.awt.event.KeyEvent.VK_CONVERT;
    public static final int VK_COPY = java.awt.event.KeyEvent.VK_COPY;
    public static final int VK_CUT = java.awt.event.KeyEvent.VK_CUT;
    public static final int VK_D = java.awt.event.KeyEvent.VK_D;
    public static final int VK_DEAD_ABOVEDOT = java.awt.event.KeyEvent.VK_DEAD_ABOVEDOT;
    public static final int VK_DEAD_ABOVERING = java.awt.event.KeyEvent.VK_DEAD_ABOVERING;
    public static final int VK_DEAD_ACUTE = java.awt.event.KeyEvent.VK_DEAD_ACUTE;
    public static final int VK_DEAD_BREVE = java.awt.event.KeyEvent.VK_DEAD_BREVE;
    public static final int VK_DEAD_CARON = java.awt.event.KeyEvent.VK_DEAD_CARON;
    public static final int VK_DEAD_CEDILLA = java.awt.event.KeyEvent.VK_DEAD_CEDILLA;
    public static final int VK_DEAD_CIRCUMFLEX = java.awt.event.KeyEvent.VK_DEAD_CIRCUMFLEX;
    public static final int VK_DEAD_DIAERESIS = java.awt.event.KeyEvent.VK_DEAD_DIAERESIS;
    public static final int VK_DEAD_DOUBLEACUTE = java.awt.event.KeyEvent.VK_DEAD_DOUBLEACUTE;
    public static final int VK_DEAD_GRAVE = java.awt.event.KeyEvent.VK_DEAD_GRAVE;
    public static final int VK_DEAD_IOTA = java.awt.event.KeyEvent.VK_DEAD_IOTA;
    public static final int VK_DEAD_MACRON = java.awt.event.KeyEvent.VK_DEAD_MACRON;
    public static final int VK_DEAD_OGONEK = java.awt.event.KeyEvent.VK_DEAD_OGONEK;
    public static final int VK_DEAD_SEMIVOICED_SOUND = java.awt.event.KeyEvent.VK_DEAD_SEMIVOICED_SOUND;
    public static final int VK_DEAD_TILDE = java.awt.event.KeyEvent.VK_DEAD_TILDE;
    public static final int VK_DEAD_VOICED_SOUND = java.awt.event.KeyEvent.VK_DEAD_VOICED_SOUND;
    public static final int VK_DECIMAL = java.awt.event.KeyEvent.VK_DECIMAL;
    public static final int VK_DELETE = java.awt.event.KeyEvent.VK_DELETE;
    public static final int VK_DIVIDE = java.awt.event.KeyEvent.VK_DIVIDE;
    public static final int VK_DOLLAR = java.awt.event.KeyEvent.VK_DOLLAR;
    public static final int VK_DOWN = java.awt.event.KeyEvent.VK_DOWN;
    public static final int VK_E = java.awt.event.KeyEvent.VK_E;
    public static final int VK_END = java.awt.event.KeyEvent.VK_END;
    public static final int VK_ENTER = java.awt.event.KeyEvent.VK_ENTER;
    public static final int VK_EQUALS = java.awt.event.KeyEvent.VK_EQUALS;
    public static final int VK_ESCAPE = java.awt.event.KeyEvent.VK_ESCAPE;
    public static final int VK_EURO_SIGN = java.awt.event.KeyEvent.VK_EURO_SIGN;
    public static final int VK_EXCLAMATION_MARK = java.awt.event.KeyEvent.VK_EXCLAMATION_MARK;
    public static final int VK_F = java.awt.event.KeyEvent.VK_F;
    public static final int VK_F1 = java.awt.event.KeyEvent.VK_F1;
    public static final int VK_F10 = java.awt.event.KeyEvent.VK_F10;
    public static final int VK_F11 = java.awt.event.KeyEvent.VK_F11;
    public static final int VK_F12 = java.awt.event.KeyEvent.VK_F12;
    public static final int VK_F13 = java.awt.event.KeyEvent.VK_F13;
    public static final int VK_F14 = java.awt.event.KeyEvent.VK_F14;
    public static final int VK_F15 = java.awt.event.KeyEvent.VK_F15;
    public static final int VK_F16 = java.awt.event.KeyEvent.VK_F16;
    public static final int VK_F17 = java.awt.event.KeyEvent.VK_F17;
    public static final int VK_F18 = java.awt.event.KeyEvent.VK_F18;
    public static final int VK_F19 = java.awt.event.KeyEvent.VK_F19;
    public static final int VK_F2 = java.awt.event.KeyEvent.VK_F2;
    public static final int VK_F20 = java.awt.event.KeyEvent.VK_F20;
    public static final int VK_F21 = java.awt.event.KeyEvent.VK_F21;
    public static final int VK_F22 = java.awt.event.KeyEvent.VK_F22;
    public static final int VK_F23 = java.awt.event.KeyEvent.VK_F23;
    public static final int VK_F24 = java.awt.event.KeyEvent.VK_F24;
    public static final int VK_F3 = java.awt.event.KeyEvent.VK_F3;
    public static final int VK_F4 = java.awt.event.KeyEvent.VK_F4;
    public static final int VK_F5 = java.awt.event.KeyEvent.VK_F5;
    public static final int VK_F6 = java.awt.event.KeyEvent.VK_F6;
    public static final int VK_F7 = java.awt.event.KeyEvent.VK_F7;
    public static final int VK_F8 = java.awt.event.KeyEvent.VK_F8;
    public static final int VK_F9 = java.awt.event.KeyEvent.VK_F9;
    public static final int VK_FINAL = java.awt.event.KeyEvent.VK_FINAL;
    public static final int VK_FIND = java.awt.event.KeyEvent.VK_FIND;
    public static final int VK_FULL_WIDTH = java.awt.event.KeyEvent.VK_FULL_WIDTH;
    public static final int VK_G = java.awt.event.KeyEvent.VK_G;
    public static final int VK_GREATER = java.awt.event.KeyEvent.VK_GREATER;
    public static final int VK_H = java.awt.event.KeyEvent.VK_H;
    public static final int VK_HALF_WIDTH = java.awt.event.KeyEvent.VK_HALF_WIDTH;
    public static final int VK_HELP = java.awt.event.KeyEvent.VK_HELP;
    public static final int VK_HIRAGANA = java.awt.event.KeyEvent.VK_HIRAGANA;
    public static final int VK_HOME = java.awt.event.KeyEvent.VK_HOME;
    public static final int VK_I = java.awt.event.KeyEvent.VK_I;
    public static final int VK_INPUT_METHOD_ON_OFF = java.awt.event.KeyEvent.VK_INPUT_METHOD_ON_OFF;
    public static final int VK_INSERT = java.awt.event.KeyEvent.VK_INSERT;
    public static final int VK_INVERTED_EXCLAMATION_MARK = java.awt.event.KeyEvent.VK_INVERTED_EXCLAMATION_MARK;
    public static final int VK_J = java.awt.event.KeyEvent.VK_J;
    public static final int VK_JAPANESE_HIRAGANA = java.awt.event.KeyEvent.VK_JAPANESE_HIRAGANA;
    public static final int VK_JAPANESE_KATAKANA = java.awt.event.KeyEvent.VK_JAPANESE_KATAKANA;
    public static final int VK_JAPANESE_ROMAN = java.awt.event.KeyEvent.VK_JAPANESE_ROMAN;
    public static final int VK_K = java.awt.event.KeyEvent.VK_K;
    public static final int VK_KANA = java.awt.event.KeyEvent.VK_KANA;
    public static final int VK_KANA_LOCK = java.awt.event.KeyEvent.VK_KANA_LOCK;
    public static final int VK_KANJI = java.awt.event.KeyEvent.VK_KANJI;
    public static final int VK_KATAKANA = java.awt.event.KeyEvent.VK_KATAKANA;
    public static final int VK_KP_DOWN = java.awt.event.KeyEvent.VK_KP_DOWN;
    public static final int VK_KP_LEFT = java.awt.event.KeyEvent.VK_KP_LEFT;
    public static final int VK_KP_RIGHT = java.awt.event.KeyEvent.VK_KP_RIGHT;
    public static final int VK_KP_UP = java.awt.event.KeyEvent.VK_KP_UP;
    public static final int VK_L = java.awt.event.KeyEvent.VK_L;
    public static final int VK_LEFT = java.awt.event.KeyEvent.VK_LEFT;
    public static final int VK_LEFT_PARENTHESIS = java.awt.event.KeyEvent.VK_LEFT_PARENTHESIS;
    public static final int VK_LESS = java.awt.event.KeyEvent.VK_LESS;
    public static final int VK_M = java.awt.event.KeyEvent.VK_M;
    public static final int VK_META = java.awt.event.KeyEvent.VK_META;
    public static final int VK_MINUS = java.awt.event.KeyEvent.VK_MINUS;
    public static final int VK_MODECHANGE = java.awt.event.KeyEvent.VK_MODECHANGE;
    public static final int VK_MULTIPLY = java.awt.event.KeyEvent.VK_MULTIPLY;
    public static final int VK_N = java.awt.event.KeyEvent.VK_N;
    public static final int VK_NONCONVERT = java.awt.event.KeyEvent.VK_NONCONVERT;
    public static final int VK_NUMBER_SIGN = java.awt.event.KeyEvent.VK_NUMBER_SIGN;
    public static final int VK_NUMPAD0 = java.awt.event.KeyEvent.VK_NUMPAD0;
    public static final int VK_NUMPAD1 = java.awt.event.KeyEvent.VK_NUMPAD1;
    public static final int VK_NUMPAD2 = java.awt.event.KeyEvent.VK_NUMPAD2;
    public static final int VK_NUMPAD3 = java.awt.event.KeyEvent.VK_NUMPAD3;
    public static final int VK_NUMPAD4 = java.awt.event.KeyEvent.VK_NUMPAD4;
    public static final int VK_NUMPAD5 = java.awt.event.KeyEvent.VK_NUMPAD5;
    public static final int VK_NUMPAD6 = java.awt.event.KeyEvent.VK_NUMPAD6;
    public static final int VK_NUMPAD7 = java.awt.event.KeyEvent.VK_NUMPAD7;
    public static final int VK_NUMPAD8 = java.awt.event.KeyEvent.VK_NUMPAD8;
    public static final int VK_NUMPAD9 = java.awt.event.KeyEvent.VK_NUMPAD9;
    public static final int VK_NUM_LOCK = java.awt.event.KeyEvent.VK_NUM_LOCK;
    public static final int VK_O = java.awt.event.KeyEvent.VK_O;
    public static final int VK_OPEN_BRACKET = java.awt.event.KeyEvent.VK_OPEN_BRACKET;
    public static final int VK_P = java.awt.event.KeyEvent.VK_P;
    public static final int VK_PAGE_DOWN = java.awt.event.KeyEvent.VK_PAGE_DOWN;
    public static final int VK_PAGE_UP = java.awt.event.KeyEvent.VK_PAGE_UP;
    public static final int VK_PASTE = java.awt.event.KeyEvent.VK_PASTE;
    public static final int VK_PAUSE = java.awt.event.KeyEvent.VK_PAUSE;
    public static final int VK_PERIOD = java.awt.event.KeyEvent.VK_PERIOD;
    public static final int VK_PLUS = java.awt.event.KeyEvent.VK_PLUS;
    public static final int VK_PREVIOUS_CANDIDATE = java.awt.event.KeyEvent.VK_PREVIOUS_CANDIDATE;
    public static final int VK_PRINTSCREEN = java.awt.event.KeyEvent.VK_PRINTSCREEN;
    public static final int VK_PROPS = java.awt.event.KeyEvent.VK_PROPS;
    public static final int VK_Q = java.awt.event.KeyEvent.VK_Q;
    public static final int VK_QUOTE = java.awt.event.KeyEvent.VK_QUOTE;
    public static final int VK_QUOTEDBL = java.awt.event.KeyEvent.VK_QUOTEDBL;
    public static final int VK_R = java.awt.event.KeyEvent.VK_R;
    public static final int VK_RIGHT = java.awt.event.KeyEvent.VK_RIGHT;
    public static final int VK_RIGHT_PARENTHESIS = java.awt.event.KeyEvent.VK_RIGHT_PARENTHESIS;
    public static final int VK_ROMAN_CHARACTERS = java.awt.event.KeyEvent.VK_ROMAN_CHARACTERS;
    public static final int VK_S = java.awt.event.KeyEvent.VK_S;
    public static final int VK_SCROLL_LOCK = java.awt.event.KeyEvent.VK_SCROLL_LOCK;
    public static final int VK_SEMICOLON = java.awt.event.KeyEvent.VK_SEMICOLON;
    public static final int VK_SEPARATER = java.awt.event.KeyEvent.VK_SEPARATER;
    public static final int VK_SEPARATOR = java.awt.event.KeyEvent.VK_SEPARATOR;
    public static final int VK_SHIFT = java.awt.event.KeyEvent.VK_SHIFT;
    public static final int VK_SLASH = java.awt.event.KeyEvent.VK_SLASH;
    public static final int VK_SPACE = java.awt.event.KeyEvent.VK_SPACE;
    public static final int VK_STOP = java.awt.event.KeyEvent.VK_STOP;
    public static final int VK_SUBTRACT = java.awt.event.KeyEvent.VK_SUBTRACT;
    public static final int VK_T = java.awt.event.KeyEvent.VK_T;
    public static final int VK_TAB = java.awt.event.KeyEvent.VK_TAB;
    public static final int VK_U = java.awt.event.KeyEvent.VK_U;
    public static final int VK_UNDEFINED = java.awt.event.KeyEvent.VK_UNDEFINED;
    public static final int VK_UNDERSCORE = java.awt.event.KeyEvent.VK_UNDERSCORE;
    public static final int VK_UNDO = java.awt.event.KeyEvent.VK_UNDO;
    public static final int VK_UP = java.awt.event.KeyEvent.VK_UP;
    public static final int VK_V = java.awt.event.KeyEvent.VK_V;
    public static final int VK_W = java.awt.event.KeyEvent.VK_W;
    public static final int VK_WINDOWS = java.awt.event.KeyEvent.VK_WINDOWS;
    public static final int VK_X = java.awt.event.KeyEvent.VK_X;
    public static final int VK_Y = java.awt.event.KeyEvent.VK_Y;
    public static final int VK_Z = java.awt.event.KeyEvent.VK_Z;
    // --- end generated constants ---

    private int keyCode;
    private char keyChar;
    private int keyLocation;

    public SKeyEvent(Component source, int id, long when, int modifiers,
                     int keyCode, char keyChar, int keyLocation) {
        super(source, id, when, modifiers);
        if (id == KEY_TYPED && (keyChar == CHAR_UNDEFINED || keyCode != VK_UNDEFINED)) {
            // AWT's own invariant — KEY_TYPED is a character delivery event:
            // it must carry a defined keyChar and no keyCode. D_never_fail_on_gaps: match
            // Swing's failure modes even on programming errors.
            throw new IllegalArgumentException("invalid combination of type, char, and code");
        }
        this.keyCode = keyCode;
        this.keyChar = keyChar;
        this.keyLocation = keyLocation;
    }

    public SKeyEvent(Component source, int id, long when, int modifiers,
                     int keyCode, char keyChar) {
        this(source, id, when, modifiers, keyCode, keyChar, KEY_LOCATION_UNKNOWN);
    }

    public SKeyEvent(Component source, int id, long when, int modifiers, int keyCode) {
        this(source, id, when, modifiers, keyCode, CHAR_UNDEFINED, KEY_LOCATION_UNKNOWN);
    }

    public int getKeyCode()      { return keyCode; }
    public void setKeyCode(int keyCode) { this.keyCode = keyCode; }
    public char getKeyChar()     { return keyChar; }
    public void setKeyChar(char keyChar) { this.keyChar = keyChar; }
    public int getKeyLocation()  { return keyLocation; }

    public void setModifiers(int modifiers) {
        // Deprecated in AWT; our SInputEvent modifiers field is final so this
        // stub preserves the signature for migrated code without actually
        // retargeting. Add when a migration target needs it.
        SHelper.onUnimplemented(this, "setModifiers", modifiers);
    }

    /** Localised key name ("Enter", "Home", …). Delegates to AWT — constants match. */
    public static String getKeyText(int keyCode) {
        return java.awt.event.KeyEvent.getKeyText(keyCode);
    }

    /**
     * Non-null source for the throwaway event in {@link #isActionKey()}. {@code EventObject}
     * rejects a null source and AWT never reads this one; a bare {@link java.awt.Component}
     * subclass is the cheapest thing that constructs headless.
     */
    @SuppressWarnings("serial")
    private static final java.awt.Component ACTION_KEY_PROBE_SOURCE = new java.awt.Component() {};

    /**
     * True for keys that produce no character — F-keys, arrows, navigation, the input-method
     * set ({@code VK_KANA}, {@code VK_KANJI}, …) and the Sun editing set ({@code VK_COPY},
     * {@code VK_UNDO}, …).
     *
     * <p>Answered by {@link java.awt.event.KeyEvent#isActionKey()} on a throwaway event rather
     * than by a list here: our {@code VK_*} values are AWT's, so AWT's own answer is correct by
     * definition and stays correct as it grows keycodes. A local list would have to be
     * maintained against a set the browser cannot produce, so nothing in this project would
     * ever exercise it. The emulator-side {@code vaadinx.awt.event.KeyEvent#isActionKey} does
     * the same, so both layers answer alike.
     */
    public boolean isActionKey() {
        return new java.awt.event.KeyEvent(ACTION_KEY_PROBE_SOURCE,
                java.awt.event.KeyEvent.KEY_PRESSED, 0L, 0, keyCode,
                java.awt.event.KeyEvent.CHAR_UNDEFINED,
                java.awt.event.KeyEvent.KEY_LOCATION_UNKNOWN).isActionKey();
    }

    @Override
    public String paramString() {
        String typeStr = switch (id) {
            case KEY_PRESSED  -> "KEY_PRESSED";
            case KEY_RELEASED -> "KEY_RELEASED";
            case KEY_TYPED    -> "KEY_TYPED";
            default           -> "unknown type";
        };
        return typeStr + ",keyCode=" + keyCode
                + ",keyText=" + getKeyText(keyCode)
                + ",keyChar=" + keyChar;
    }
}
