/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

import java.awt.Point;

/**
 * Surrogate-side port of {@link java.awt.event.MouseEvent}. Source retyped
 * from {@link java.awt.Component} to {@link com.vaadin.flow.component.Component}
 * per SD_event_port_stance — surrogates are Vaadin components, not AWT components, so the JDK
 * type doesn't fit.
 *
 * <p>The {@code MOUSE_*} ID constants and the {@code BUTTON*} button constants
 * have identical values to AWT — bit/value comparisons across the boundary
 * carry verbatim. Mirrors the emulator-side {@code vaadinx.awt.event.MouseEvent}
 * port (SD_shelper_statics: cross-module reuse is disallowed, so the constants exist twice).
 *
 * <p>Today's only producer is {@code ComponentMixin.addMouseListener}'s
 * {@code ClickNotifier}-backed wire, which fires {@code MOUSE_CLICKED}. Other
 * MOUSE_* IDs are surface-only (so migrated listener code that switches on
 * {@code e.getID()} compiles); the press/release/move/drag/wheel firings
 * would need a custom DOM listener stack — out of scope.
 */
public class SMouseEvent extends SInputEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int BUTTON1 = java.awt.event.MouseEvent.BUTTON1;
    public static final int BUTTON2 = java.awt.event.MouseEvent.BUTTON2;
    public static final int BUTTON3 = java.awt.event.MouseEvent.BUTTON3;
    public static final int MOUSE_CLICKED = java.awt.event.MouseEvent.MOUSE_CLICKED;
    public static final int MOUSE_DRAGGED = java.awt.event.MouseEvent.MOUSE_DRAGGED;
    public static final int MOUSE_ENTERED = java.awt.event.MouseEvent.MOUSE_ENTERED;
    public static final int MOUSE_EXITED = java.awt.event.MouseEvent.MOUSE_EXITED;
    public static final int MOUSE_FIRST = java.awt.event.MouseEvent.MOUSE_FIRST;
    public static final int MOUSE_LAST = java.awt.event.MouseEvent.MOUSE_LAST;
    public static final int MOUSE_MOVED = java.awt.event.MouseEvent.MOUSE_MOVED;
    public static final int MOUSE_PRESSED = java.awt.event.MouseEvent.MOUSE_PRESSED;
    public static final int MOUSE_RELEASED = java.awt.event.MouseEvent.MOUSE_RELEASED;
    public static final int MOUSE_WHEEL = java.awt.event.MouseEvent.MOUSE_WHEEL;
    public static final int NOBUTTON = java.awt.event.MouseEvent.NOBUTTON;
    // --- end generated constants ---

    private final int x;
    private final int y;
    private final int xAbs;
    private final int yAbs;
    private final int clickCount;
    private final boolean popupTrigger;
    private final int button;

    public SMouseEvent(Component source, int id, long when, int modifiers,
                       int x, int y, int xAbs, int yAbs,
                       int clickCount, boolean popupTrigger, int button) {
        super(source, id, when, modifiers);
        this.x = x;
        this.y = y;
        this.xAbs = xAbs;
        this.yAbs = yAbs;
        this.clickCount = clickCount;
        this.popupTrigger = popupTrigger;
        this.button = button;
    }

    public SMouseEvent(Component source, int id, long when, int modifiers,
                       int x, int y, int clickCount, boolean popupTrigger, int button) {
        this(source, id, when, modifiers, x, y, x, y, clickCount, popupTrigger, button);
    }

    public SMouseEvent(Component source, int id, long when, int modifiers,
                       int x, int y, int clickCount, boolean popupTrigger) {
        this(source, id, when, modifiers, x, y, clickCount, popupTrigger, NOBUTTON);
    }

    public int getX() { return x; }
    public int getY() { return y; }
    public Point getPoint() { return new Point(x, y); }
    public int getXOnScreen() { return xAbs; }
    public int getYOnScreen() { return yAbs; }
    public Point getLocationOnScreen() { return new Point(xAbs, yAbs); }
    public int getClickCount() { return clickCount; }
    public boolean isPopupTrigger() { return popupTrigger; }
    public int getButton() { return button; }

    @Override
    public String paramString() {
        String typeStr = switch (id) {
            case MOUSE_CLICKED  -> "MOUSE_CLICKED";
            case MOUSE_PRESSED  -> "MOUSE_PRESSED";
            case MOUSE_RELEASED -> "MOUSE_RELEASED";
            case MOUSE_MOVED    -> "MOUSE_MOVED";
            case MOUSE_ENTERED  -> "MOUSE_ENTERED";
            case MOUSE_EXITED   -> "MOUSE_EXITED";
            case MOUSE_DRAGGED  -> "MOUSE_DRAGGED";
            case MOUSE_WHEEL    -> "MOUSE_WHEEL";
            default             -> "unknown type";
        };
        return typeStr + ",(" + x + "," + y + "),button=" + button + ",clickCount=" + clickCount;
    }
}
