/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates.awt.event;

import com.vaadin.flow.component.Component;

/**
 * Surrogate-side port of {@link java.awt.event.WindowEvent}. Source and
 * {@code opposite} retyped from {@link java.awt.Window} to Vaadin
 * {@link com.vaadin.flow.component.Component} per SD_event_port_stance — the surrogates that
 * emit this event (currently {@code SFrame}) extend Dialog directly, so
 * "the other window on the focus transition" is a Vaadin Component, not
 * an AWT Window.
 *
 * <p>Constants preserved verbatim from {@link java.awt.event.WindowEvent}
 * so {@code id} arithmetic carries across unchanged — migrated code that
 * checks {@code e.getID() == WindowEvent.WINDOW_CLOSING} works against
 * either value (same int).
 *
 * <p>Ported eagerly alongside {@code SWindow} per SD_event_port_stance — every id routes
 * through {@code SWindow.processWindowEvent / ...FocusEvent /
 * ...StateEvent}, and splitting the port (fire OPENED / CLOSING but not
 * STATE_CHANGED) would break the id-to-method dispatch switch.
 */
public class SWindowEvent extends SComponentEvent {

    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---
    public static final int WINDOW_ACTIVATED = java.awt.event.WindowEvent.WINDOW_ACTIVATED;
    public static final int WINDOW_CLOSED = java.awt.event.WindowEvent.WINDOW_CLOSED;
    public static final int WINDOW_CLOSING = java.awt.event.WindowEvent.WINDOW_CLOSING;
    public static final int WINDOW_DEACTIVATED = java.awt.event.WindowEvent.WINDOW_DEACTIVATED;
    public static final int WINDOW_DEICONIFIED = java.awt.event.WindowEvent.WINDOW_DEICONIFIED;
    public static final int WINDOW_FIRST = java.awt.event.WindowEvent.WINDOW_FIRST;
    public static final int WINDOW_GAINED_FOCUS = java.awt.event.WindowEvent.WINDOW_GAINED_FOCUS;
    public static final int WINDOW_ICONIFIED = java.awt.event.WindowEvent.WINDOW_ICONIFIED;
    public static final int WINDOW_LAST = java.awt.event.WindowEvent.WINDOW_LAST;
    public static final int WINDOW_LOST_FOCUS = java.awt.event.WindowEvent.WINDOW_LOST_FOCUS;
    public static final int WINDOW_OPENED = java.awt.event.WindowEvent.WINDOW_OPENED;
    public static final int WINDOW_STATE_CHANGED = java.awt.event.WindowEvent.WINDOW_STATE_CHANGED;
    // --- end generated constants ---

    private final Component opposite;
    private final int oldState;
    private final int newState;

    public SWindowEvent(Component source, int id, Component opposite,
                        int oldState, int newState) {
        super(source, id);
        this.opposite = opposite;
        this.oldState = oldState;
        this.newState = newState;
    }

    public SWindowEvent(Component source, int id, Component opposite) {
        this(source, id, opposite, 0, 0);
    }

    public SWindowEvent(Component source, int id, int oldState, int newState) {
        this(source, id, null, oldState, newState);
    }

    public SWindowEvent(Component source, int id) {
        this(source, id, null, 0, 0);
    }

    /** Same as {@link #getComponent()} but typed to match the JDK shape. */
    public Component getWindow() {
        return getComponent();
    }

    /**
     * The focus/activation counterpart on the other end of the transition, or
     * {@code null} when unknown. Our wiring passes {@code null} uniformly —
     * browser window focus transitions don't surface the opposite server-side
     * — so the field is preserved mainly for migrated code that reads it
     * through the ported listener without branching.
     */
    public Component getOppositeWindow() {
        return opposite;
    }

    /**
     * Pre-transition window state for {@code WINDOW_STATE_CHANGED}; zero
     * ({@code NORMAL}) for every other id since we don't model iconify /
     * maximize (no OS window manager concept in a browser tab).
     */
    public int getOldState() {
        return oldState;
    }

    /** Post-transition state; see {@link #getOldState()}. */
    public int getNewState() {
        return newState;
    }

    @Override
    public String paramString() {
        return switch (id) {
            case WINDOW_OPENED        -> "WINDOW_OPENED";
            case WINDOW_CLOSING       -> "WINDOW_CLOSING";
            case WINDOW_CLOSED        -> "WINDOW_CLOSED";
            case WINDOW_ICONIFIED     -> "WINDOW_ICONIFIED";
            case WINDOW_DEICONIFIED   -> "WINDOW_DEICONIFIED";
            case WINDOW_ACTIVATED     -> "WINDOW_ACTIVATED";
            case WINDOW_DEACTIVATED   -> "WINDOW_DEACTIVATED";
            case WINDOW_GAINED_FOCUS  -> "WINDOW_GAINED_FOCUS";
            case WINDOW_LOST_FOCUS    -> "WINDOW_LOST_FOCUS";
            case WINDOW_STATE_CHANGED -> "WINDOW_STATE_CHANGED";
            default                   -> "unknown type";
        };
    }
}
