/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.vaadin.swingbridge.surrogates;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Generates the ten {@code S*Event} classes' public constant surfaces by reflecting over their
 * JDK counterparts, and fails if what is on disk differs. Every constant delegates —
 * {@code VK_A = java.awt.event.KeyEvent.VK_A} — so no constant value is written out in
 * {@code :surrogates} at all.
 *
 * <p>Regenerate with
 * {@code ./mvnw -C -pl surrogates test -Dtest=DelegatedConstantsTest -Dsurrogate.regenerate=true}
 * and commit the diff.
 *
 * <p><b>This test is the provenance record, not a tidiness check.</b> These files carried
 * OpenJDK's constant tables transcribed, in OpenJDK's own order and hex casing, which is what
 * earned them {@code HDR_jdk_derived}. They now carry a table this class emits from the public
 * runtime API, in an order of our choosing, with no value passing through our source — so they are
 * Vaadin-authored rather than JDK-derived, and carry this module's {@code HDR_vaadin_apache}.
 * <b>That is what the module's Apache-2.0 licence rests on</b> ({@code D_licence_lanes}): the
 * boundary a consumer can see is the jar, so one transcribed table coming back would put GPL code
 * inside a permissive artifact. Deleting this test, or hand-editing a generated region, silently
 * un-does that. It is the same golden-file bargain {@code PortedTypesTableTest} strikes,
 * for the same reason: a check that runs every build beats an assertion made once.
 *
 * <p>The emitted set is whatever the JDK class declares — never a list kept here — so the
 * selection is the JDK's own and there is nothing to maintain when it adds a keycode.
 * Every target was verified to declare exactly its counterpart's set, so emitting the
 * counterpart's set widens no public API. It is sorted by name because
 * {@link Class#getDeclaredFields()} has no specified order, and because reproducing the
 * JDK's declaration order is the one thing worth not doing.
 */
class DelegatedConstantsTest {

    private static final Path SRC = Path.of("src/main/java/com/vaadin/swingbridge/surrogates");

    private static final String BEGIN =
            "    // --- constants generated by DelegatedConstantsTest — do not hand-edit ---";
    private static final String END =
            "    // --- end generated constants ---";

    /**
     * One generated region: the surrogate source file, its JDK counterpart, and how many public
     * constants that counterpart is expected to declare.
     *
     * @param expectedCount a tripwire, not a spec: reflection returning far fewer fields than the
     *                      JDK has would otherwise regenerate a near-empty table and pass
     */
    private record Target(String path, Class<?> jdk, int expectedCount) {
    }

    private static final List<Target> TARGETS = List.of(
            new Target("awt/event/SKeyEvent.java", java.awt.event.KeyEvent.class, 200),
            new Target("awt/event/SInputEvent.java", java.awt.event.InputEvent.class, 16),
            new Target("awt/event/SComponentEvent.java", java.awt.event.ComponentEvent.class, 6),
            new Target("awt/event/SContainerEvent.java", java.awt.event.ContainerEvent.class, 4),
            new Target("awt/event/SFocusEvent.java", java.awt.event.FocusEvent.class, 4),
            new Target("awt/event/SHierarchyEvent.java", java.awt.event.HierarchyEvent.class, 8),
            new Target("awt/event/SMouseEvent.java", java.awt.event.MouseEvent.class, 14),
            new Target("awt/event/SWindowEvent.java", java.awt.event.WindowEvent.class, 12),
            new Target("awt/event/SAncestorEvent.java", javax.swing.event.AncestorEvent.class, 3),
            new Target("swing/event/SInternalFrameEvent.java",
                    javax.swing.event.InternalFrameEvent.class, 9));

    /**
     * Bootstraps every region from the command line, for the one case surefire cannot reach: an
     * empty or missing region leaves {@code :surrogates} uncompilable, so the test never runs to
     * fill it. Compile this one file against {@code junit-jupiter-api} and run it from the module
     * directory. Ordinary regeneration — the JDK gaining a constant — goes through
     * {@code -Dsurrogate.regenerate=true}, since the module still compiles in that case.
     */
    public static void main(String[] args) throws IOException {
        System.setProperty("surrogate.regenerate", "true");
        new DelegatedConstantsTest().constantsAreGenerated();
    }

    @Test
    @DisplayName("every S*Event's constants are what reflection over its JDK counterpart emits")
    void constantsAreGenerated() throws IOException {
        for (Target target : TARGETS) {
            check(target);
        }
    }

    private void check(Target target) throws IOException {
        Class<?> awt = target.jdk();
        String fileName = target.path();
        Path file = SRC.resolve(fileName);
        assertTrue(Files.exists(file), file.toAbsolutePath() + " is missing");

        List<Field> fields = constantsOf(awt);
        assertEquals(target.expectedCount(), fields.size(), awt.getName()
                + " declares " + fields.size() + " public constants, expected "
                + target.expectedCount()
                + " — if the JDK genuinely changed, update the tripwire and regenerate");

        String generated = render(awt, fields);
        String source = Files.readString(file, StandardCharsets.UTF_8).replace("\r\n", "\n");
        int from = source.indexOf(BEGIN);
        int to = source.indexOf(END);
        if (from < 0 || to < 0 || to < from) {
            fail(fileName + " has no generated-constants region. Expected a line\n  " + BEGIN
                    + "\nand a closing\n  " + END);
        }
        String onDisk = source.substring(from + BEGIN.length(), to);

        if (Boolean.getBoolean("surrogate.regenerate")) {
            Files.writeString(file,
                    source.substring(0, from + BEGIN.length()) + generated + source.substring(to),
                    StandardCharsets.UTF_8);
            System.out.println("regenerated " + file.toAbsolutePath() + " — commit the diff");
            return;
        }
        if (!onDisk.equals(generated)) {
            fail(fileName + "'s constants differ from what reflecting over " + awt.getName()
                    + " emits:\n\n" + diff(onDisk, generated)
                    + "\n\nRegenerate with -Dsurrogate.regenerate=true and commit the diff.");
        }
    }

    /** AWT's own declared public constants, sorted by name. Inherited ones belong to the superclass's file. */
    private static List<Field> constantsOf(Class<?> awt) {
        List<Field> out = new ArrayList<>();
        for (Field f : awt.getDeclaredFields()) {
            int m = f.getModifiers();
            if (Modifier.isPublic(m) && Modifier.isStatic(m) && Modifier.isFinal(m)) {
                out.add(f);
            }
        }
        out.sort(Comparator.comparing(Field::getName));
        return out;
    }

    /**
     * One delegating declaration per constant. {@code @Deprecated} is carried across both because
     * migrated code should see the same deprecation it saw on the desktop and because javac then
     * stops warning about the initializer's own reference to a deprecated AWT field.
     */
    private static String render(Class<?> awt, List<Field> fields) {
        StringBuilder sb = new StringBuilder("\n");
        for (Field f : fields) {
            if (f.isAnnotationPresent(Deprecated.class)) {
                sb.append("    @Deprecated\n");
            }
            sb.append("    public static final ").append(f.getType().getName()).append(' ')
                    .append(f.getName()).append(" = ").append(awt.getName()).append('.')
                    .append(f.getName()).append(";\n");
        }
        return sb.toString();
    }

    /** Names the constants that moved, so a red build is readable rather than a 200-line dump. */
    private static String diff(String onDisk, String generated) {
        List<String> was = onDisk.lines().filter(l -> !l.isBlank()).toList();
        List<String> now = generated.lines().filter(l -> !l.isBlank()).toList();
        List<String> out = new ArrayList<>();
        now.stream().filter(l -> !was.contains(l)).limit(20).forEach(l -> out.add("    + " + l.strip()));
        was.stream().filter(l -> !now.contains(l)).limit(20).forEach(l -> out.add("    - " + l.strip()));
        return out.isEmpty() ? "    (whitespace only)" : String.join("\n", out);
    }
}
