/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.AbstractButton
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.AbstractButton, then hand-finished.

/** Emulator for {@link javax.swing.AbstractButton}. */
public abstract class AbstractButton extends vaadinx.swing.JComponent implements java.awt.ItemSelectable, javax.swing.SwingConstants {

    // The JDK's bound-property name constants. Present as API, not decoration:
    // migrated code writes addPropertyChangeListener(AbstractButton
    // .TEXT_CHANGED_PROPERTY, l) and would not compile without them. Every name
    // matches javax.swing.AbstractButton's value exactly (D_owed_events).
    public static final java.lang.String MODEL_CHANGED_PROPERTY = "model";
    public static final java.lang.String TEXT_CHANGED_PROPERTY = "text";
    public static final java.lang.String MNEMONIC_CHANGED_PROPERTY = "mnemonic";
    public static final java.lang.String MARGIN_CHANGED_PROPERTY = "margin";
    public static final java.lang.String VERTICAL_ALIGNMENT_CHANGED_PROPERTY = "verticalAlignment";
    public static final java.lang.String HORIZONTAL_ALIGNMENT_CHANGED_PROPERTY = "horizontalAlignment";
    public static final java.lang.String VERTICAL_TEXT_POSITION_CHANGED_PROPERTY = "verticalTextPosition";
    public static final java.lang.String HORIZONTAL_TEXT_POSITION_CHANGED_PROPERTY = "horizontalTextPosition";
    public static final java.lang.String BORDER_PAINTED_CHANGED_PROPERTY = "borderPainted";
    public static final java.lang.String FOCUS_PAINTED_CHANGED_PROPERTY = "focusPainted";
    public static final java.lang.String ROLLOVER_ENABLED_CHANGED_PROPERTY = "rolloverEnabled";
    public static final java.lang.String CONTENT_AREA_FILLED_CHANGED_PROPERTY = "contentAreaFilled";
    public static final java.lang.String ICON_CHANGED_PROPERTY = "icon";
    public static final java.lang.String PRESSED_ICON_CHANGED_PROPERTY = "pressedIcon";
    public static final java.lang.String SELECTED_ICON_CHANGED_PROPERTY = "selectedIcon";
    public static final java.lang.String ROLLOVER_ICON_CHANGED_PROPERTY = "rolloverIcon";
    public static final java.lang.String ROLLOVER_SELECTED_ICON_CHANGED_PROPERTY = "rolloverSelectedIcon";
    public static final java.lang.String DISABLED_ICON_CHANGED_PROPERTY = "disabledIcon";
    public static final java.lang.String DISABLED_SELECTED_ICON_CHANGED_PROPERTY = "disabledSelectedIcon";

    // AWT's AbstractButton stores text independently of the peer so a null
    // setText round-trips; getText matches what user code set, not the
    // peer's rendering. Default is null (AWT's post-construction value),
    // which becomes "" at the peer write so a Vaadin Button doesn't NPE.
    private java.lang.String text;

    /**
     * The button's state machine — armed, pressed, selected, enabled, rollover — and its action
     * command, as in the JDK. The emulator builds it and listens to it; the surrogate is handed
     * the same instance, so a browser click pulses this model and the surrogate renders its
     * selection.
     */
    protected javax.swing.ButtonModel model = null;

    /** The model's {@code ChangeListener}, {@link #createChangeListener}'s result. */
    protected javax.swing.event.ChangeListener changeListener = null;

    /** The model's {@code ActionListener}, {@link #createActionListener}'s result. */
    protected java.awt.event.ActionListener actionListener = null;

    /** The model's {@code ItemListener}, {@link #createItemListener}'s result. */
    protected java.awt.event.ItemListener itemListener = null;

    /** Only one {@code ChangeEvent} is needed per button, as its sole state is the source. */
    protected transient javax.swing.event.ChangeEvent changeEvent;

    private Handler handler;

    // Icon fields — the Swing-side state; setIcon pushes an ImageIcon to the peer
    // as a Vaadin Image and WARNs for other Icon implementations.
    // Storing the fields lets user code read back what it set and keeps ctors
    // from firing onUnimplemented WARNs on every button construction.
    private vaadinx.swing.Icon icon;
    private vaadinx.swing.Icon pressedIcon;
    private vaadinx.swing.Icon selectedIcon;
    private vaadinx.swing.Icon disabledIcon;
    private vaadinx.swing.Icon disabledSelectedIcon;
    private vaadinx.swing.Icon rolloverIcon;
    private vaadinx.swing.Icon rolloverSelectedIcon;

    // Visual flags — Swing defaults. No peer semantics today (Vaadin's
    // Button doesn't expose border/content-area/focus toggles), but
    // round-trip storage keeps user code that reads these back honest.
    private boolean borderPainted = true;
    private boolean contentAreaFilled = true;
    private boolean focusPainted = true;
    private boolean rolloverEnabled = false;

    // Layout/interaction fields with Swing defaults.
    private int iconTextGap = 4;
    private long multiClickThreshhold = 0;
    private boolean hideActionText = false;
    private java.awt.Insets margin;

    // Mnemonic state. Swing stores mnemonic in the ButtonModel too; here it is
    // the button's own field, so model.getMnemonic() does not see it. displayedMnemonicIndex
    // defaults to -1 per javadoc ("no mnemonic character displayed").
    private int mnemonic = 0;
    private int displayedMnemonicIndex = -1;

    // Alignment state — SwingConstants values. Field-only round-trip: the
    // Vaadin Button peer doesn't expose text/icon alignment in a way that
    // maps cleanly, so these stay advisory for user code that reads them
    // back. Defaults match JDK AbstractButton (CENTER / CENTER / TRAILING /
    // CENTER). Constants are inherited via SwingConstants.
    private int horizontalAlignment = CENTER;
    private int verticalAlignment = CENTER;
    private int horizontalTextPosition = TRAILING;
    private int verticalTextPosition = CENTER;

    // Action currently installed via setAction. Null until user code calls
    // setAction(a) with a non-null Action. Held strong-ref (PCL below also
    // strong-refs back) since our button/peer lifecycle is session-scoped —
    // a long-lived static Action shared across buttons would leak, but that
    // pattern hasn't surfaced yet. Switch to WeakReference if it does.
    private javax.swing.Action action;
    // Listener installed on the Action so user mutations
    // (action.setEnabled, action.putValue(NAME, …)) propagate to the
    // button. Recreated on every setAction call — the Action holds it,
    // and we hand its reference back when tearing down so the old Action
    // can detach cleanly.
    private java.beans.PropertyChangeListener actionPropertyChangeListener;

    protected AbstractButton() {
        // Can't pick a peer without a concrete subclass ctor providing
        // one; this no-arg path only exists because AWT has it. Div keeps
        // us compilable; concrete subclasses (JButton, JToggleButton, ...)
        // always route through the peer-taking ctor below, so user code
        // never hits this path in practice.
        this(new com.vaadin.flow.component.html.Div() /* placeholder peer of the generated fallback ctor; every real ctor passes its own */);
        vaadinx.EHelper.onUnimplemented("AbstractButton", "<init>");
    }

    /**
     * Peers on {@code peer}, built by the caller. Installs no model: as in the JDK, the concrete
     * subclass's constructor does ({@link #setModel}).
     */
    protected AbstractButton(com.vaadin.flow.component.Component peer) {
        super(peer);
        installClickBridge();
    }

    /** The lazy form: see {@link vaadinx.awt.Component#Component(Class, java.util.function.Supplier)}. */
    protected <P extends com.vaadin.flow.component.Component> AbstractButton(Class<P> peerType,
            java.util.function.Supplier<? extends P> peerFactory) {
        super(peerType, peerFactory);
        installClickBridge();
    }

    /**
     * A surrogate peer pulses the model it is handed ({@link #setModel}) on a browser click, and
     * the model's events reach this button through {@link Handler}. Any other clickable peer gets
     * the same pulse from here, funnelled through {@code callSwing} per R_callswing_envelope.
     */
    private void installClickBridge() {
        withPeer(p -> {
            if (!(p instanceof com.vaadin.swingbridge.surrogates.swing.AbstractButtonMixin)
                    && p instanceof com.vaadin.flow.component.ClickNotifier<?> cn) {
                cn.addClickListener(e -> vaadinx.EHelper.callSwing(this::pulseModel));
            }
        });
    }

    /** A click's model transitions, as the JDK's button listener and {@link #doClick} drive them. */
    private void pulseModel() {
        model.setArmed(true);
        model.setPressed(true);
        model.setPressed(false);
        model.setArmed(false);
    }

    protected void init(java.lang.String text, vaadinx.swing.Icon icon) {
        // JDK funnels every AbstractButton ctor through init() so subclasses
        // that override it get exactly one post-construction hook. Our JButton
        // ctors route here too (see JButton.java) — preserving that contract
        // means a user subclass overriding init() still fires once per button.
        // The null-guards are JDK-verbatim: setText(null) and setIcon(null)
        // are no-ops in AWT, so init() skips them to avoid writing "" to the
        // peer on an icon-only button. UI install / keymap lookup are L&F
        // concerns we don't model (see updateUI).
        if (text != null) {
            setText(text);
        }
        if (icon != null) {
            setIcon(icon);
        }
        // The JDK's init closes with these two, so a button answers 0.0f / 0.5f where
        // an untouched JComponent answers Component's 0.5f for both.
        setAlignmentX(LEFT_ALIGNMENT);
        setAlignmentY(CENTER_ALIGNMENT);
    }

    protected java.lang.String paramString() {
        // Chain up per the AWT pattern, then append the subset of
        // AbstractButton state we actually track. JDK also lists all seven
        // icon fields; we skip icons whose values are null (the common case)
        // to keep output readable. Names ("paintBorder", "paintFocus") match
        // JDK's paramString, not our field names, so tooling that greps
        // toString output sees the canonical Swing shape.
        java.lang.String s = super.paramString();
        if (text != null) s = s + ",text=" + text;
        if (margin != null) s = s + ",margin=" + margin;
        return s + ",paintBorder=" + borderPainted
                + ",paintFocus=" + focusPainted
                + ",rolloverEnabled=" + rolloverEnabled
                + ",contentAreaFilled=" + contentAreaFilled;
    }

    public java.lang.String getLabel() {
        // Deprecated 1.0 alias for getText. Delegates so a user override
        // of getText is honored when the old accessor is called.
        return getText();
    }

    public java.lang.String getText() {
        // AWT: returns the field verbatim — null if never set.
        return text;
    }

    protected void paintBorder(java.awt.Graphics arg0) {
        vaadinx.EHelper.onUnimplemented("AbstractButton", "paintBorder", arg0);
    }

    @Override
    public void setLayout(vaadinx.awt.LayoutManager mgr) {
        // Swing's AbstractButton doesn't override setLayout — the generator
        // over-collected from inherited methods (same artifact as addImpl
        // below). Delegating to Container.setLayout restores the standard
        // path; override kept (rather than deleted) so the hand-finish intent
        // survives re-generation.
        super.setLayout(mgr);
    }

    public javax.swing.Action getAction() {
        return action;
    }

    public int getMnemonic() {
        return mnemonic;
    }

    public boolean isSelected() {
        return model.isSelected();
    }

    /**
     * Hands the flag to the model, which fires on an actual change: {@code ItemEvent} then
     * {@code ChangeEvent} from a {@code DefaultButtonModel}, the reverse from a
     * {@link JToggleButton.ToggleButtonModel}, which also consults its {@link ButtonGroup}.
     *
     * <p>A plain {@code JButton} has the selection <em>state</em> but no rendering of it: only
     * the effect is missing, the half R_decline_effect_only permits dropping.
     */
    public void setSelected(boolean b) {
        model.setSelected(b);
    }

    public void doClick() {
        doClick(68);
    }

    /**
     * Pulses the model as a press and release would, so a disabled button does nothing and a
     * toggle button flips. The JDK paints the pressed state and sleeps {@code pressTime} between
     * press and release; nothing paints here, so neither happens.
     */
    public void doClick(int pressTime) {
        pulseModel();
    }

    public javax.swing.ButtonModel getModel() {
        return model;
    }

    public void setRolloverEnabled(boolean rolloverEnabled) {
        // Swing fires "rolloverEnabled" PCE. No peer semantics: Vaadin
        // Button owns its hover styling, so the flag is advisory here.
        boolean old = this.rolloverEnabled;
        this.rolloverEnabled = rolloverEnabled;
        firePropertyChange("rolloverEnabled", old, rolloverEnabled);
    }

    public vaadinx.swing.Icon getIcon() {
        return icon;
    }

    public vaadinx.swing.Icon getDisabledIcon() {
        // Swing: if no disabledIcon is set but a grayscale default can be
        // synthesized from the main icon, it's lazily created and cached.
        // We skip the synthesis (no paint pipeline) and return null, which
        // still matches Swing when the button was constructed without a
        // disabled icon AND the main icon isn't an ImageIcon.
        return disabledIcon;
    }

    public vaadinx.swing.Icon getSelectedIcon() {
        return selectedIcon;
    }

    public vaadinx.swing.Icon getDisabledSelectedIcon() {
        return disabledSelectedIcon;
    }

    protected int checkVerticalKey(int key, java.lang.String exception) {
        // JDK validator: SwingConstants vertical keys only. Per R_match_swing_errors we
        // throw the same IAE so bad keys still surface the programming
        // error instead of silently coercing.
        if (key == TOP || key == CENTER || key == BOTTOM) {
            return key;
        }
        throw new java.lang.IllegalArgumentException(exception);
    }

    protected int checkHorizontalKey(int key, java.lang.String exception) {
        if (key == LEFT || key == CENTER || key == RIGHT
                || key == LEADING || key == TRAILING) {
            return key;
        }
        throw new java.lang.IllegalArgumentException(exception);
    }

    public void removeNotify() {
        // JDK AbstractButton.removeNotify unregisters this button from
        // ToolTipManager. No ToolTipManager here, so Component's onNoop
        // super is the honest answer. Override kept (rather than deleted)
        // per the "don't drop; call super, explain why" convention so the
        // rationale survives regeneration.
        super.removeNotify();
    }

    public boolean isRolloverEnabled() {
        return rolloverEnabled;
    }

    public void setActionCommand(java.lang.String command) {
        // No PropertyChangeEvent: neither this nor DefaultButtonModel fires anything bound.
        // The command is read back at ActionEvent-construction time, which is the whole
        // notification (D_property_fanout_audit).
        getModel().setActionCommand(command);
    }

    /** @return the model's command, or the button's text when the model has none */
    public java.lang.String getActionCommand() {
        java.lang.String ac = getModel().getActionCommand();
        if (ac == null) {
            ac = getText();
        }
        return ac;
    }

    public void removeActionListener(java.awt.event.ActionListener l) {
        // EventListenerList.remove is null-safe; matches AWT's silent
        // no-op for an unregistered / null listener.
        listenerList.remove(java.awt.event.ActionListener.class, l);
    }

    protected void configurePropertiesFromAction(javax.swing.Action a) {
        // JDK's shape: copy every Action value the button cares about into
        // the matching field/peer state. Factored into per-property helpers
        // so actionPropertyChanged below can call the same method when a
        // single key changes later (e.g. Action.setEnabled fires PCE for
        // "enabled"; we re-read just that property, not all of them).
        setTextFromAction(a, false);
        setActionCommandFromAction(a);
        setIconFromAction(a);
        setMnemonicFromAction(a);
        setDisplayedMnemonicIndexFromAction(a);
        setToolTipTextFromAction(a);
        // JDK: setEnabled(a == null || a.isEnabled()). A null action clears
        // Action-driven enablement — the button goes back to its own
        // "enabled" state (true by default). Matches migrated-app expectations.
        setEnabled(a == null || a.isEnabled());
    }

    /**
     * Action.NAME → button text, in the JDK's two shapes.
     *
     * <p>Named and split as {@code javax.swing.AbstractButton.setTextFromAction}
     * is, because collapsing the two branches into the {@code propertyChange}
     * one — as this did — makes a full reconfigure decline to *clear* stale text
     * instead of clearing it. {@code hideActionText} is the toolbar idiom: show
     * the Action's name as the tooltip, not as the visible label.
     *
     * @param propertyChange {@code true} when responding to the Action's own NAME
     *     property changing (leave the text alone while hidden), {@code false} for
     *     a full reconfigure (null the text while hidden).
     */
    private void setTextFromAction(javax.swing.Action a, boolean propertyChange) {
        boolean hideText = getHideActionText();
        if (!propertyChange) {
            setText(a != null && !hideText ? (String) a.getValue(javax.swing.Action.NAME) : null);
        } else if (!hideText) {
            setText((String) a.getValue(javax.swing.Action.NAME));
        }
    }

    private void setActionCommandFromAction(javax.swing.Action a) {
        // Action.ACTION_COMMAND_KEY → setActionCommand. Null Action clears
        // the command; getActionCommand's own fallback to getText() then
        // kicks back in.
        setActionCommand(a == null ? null : (String) a.getValue(javax.swing.Action.ACTION_COMMAND_KEY));
    }

    private void setIconFromAction(javax.swing.Action a) {
        // Action carries icons under LARGE_ICON_KEY (preferred by JDK)
        // with SMALL_ICON as fallback. Action's type is javax.swing.Icon —
        // our setIcon takes vaadinx.swing.Icon. Migrated code using the
        // JDK type can't project into our hierarchy without the icon-
        // rendering work. For now: pass
        // through when the value already happens to be our Icon (rare but
        // possible if user code was already rewritten to vaadinx.swing.Icon);
        // otherwise log the drop so migration surfaces it.
        if (a == null) {
            setIcon(null);
            return;
        }
        Object iconObj = a.getValue(javax.swing.Action.LARGE_ICON_KEY);
        if (iconObj == null) {
            iconObj = a.getValue(javax.swing.Action.SMALL_ICON);
        }
        if (iconObj == null) {
            setIcon(null);
            return;
        }
        if (iconObj instanceof vaadinx.swing.Icon ours) {
            setIcon(ours);
            return;
        }
        // javax.swing.Icon or something else — can't render it today. WARN
        // so migrators know the icon was dropped; the action still works.
        vaadinx.EHelper.onUnimplemented("AbstractButton", "setIconFromAction", iconObj);
    }

    private void setMnemonicFromAction(javax.swing.Action a) {
        // Action.MNEMONIC_KEY → setMnemonic(int). Null / missing key → 0
        // ("no mnemonic"), matching JDK's "clear on absent key" contract
        // so a no-mnemonic Action doesn't inherit a previous one.
        Integer n = (a == null) ? null : (Integer) a.getValue(javax.swing.Action.MNEMONIC_KEY);
        setMnemonic(n == null ? 0 : n);
    }

    private void setDisplayedMnemonicIndexFromAction(javax.swing.Action a) {
        // JDK clamps to -1 if the text isn't set or the index is out of
        // range, then calls setDisplayedMnemonicIndex. Our setter throws
        // IAE on out-of-range indices (R_match_swing_errors / D_never_fail_on_gaps), so the pre-clamp here is
        // load-bearing: a freshly-attached Action must not throw just
        // because we set the mnemonic index before the text landed.
        Integer index = (a == null) ? null : (Integer) a.getValue(javax.swing.Action.DISPLAYED_MNEMONIC_INDEX_KEY);
        int normalised;
        if (index == null) {
            normalised = -1;
        } else {
            java.lang.String t = getText();
            if (index < -1 || t == null || index >= t.length()) {
                normalised = -1;
            } else {
                normalised = index;
            }
        }
        setDisplayedMnemonicIndex(normalised);
    }

    private void setToolTipTextFromAction(javax.swing.Action a) {
        // Action.SHORT_DESCRIPTION → setToolTipText. JComponent.setToolTipText
        // drives the peer via HasTooltip; null clears. JDK's shape calls
        // setToolTipText unconditionally, including with null when no
        // description is set — we match so removing SHORT_DESCRIPTION
        // from an attached Action clears the button's tooltip.
        setToolTipText(a == null ? null : (String) a.getValue(javax.swing.Action.SHORT_DESCRIPTION));
    }

    public void addActionListener(java.awt.event.ActionListener l) {
        // Stored in Component.listenerList (shared EventListenerList for
        // every AWT listener type). Null is silently dropped, matching
        // AWT's contract and EventListenerList.add semantics.
        listenerList.add(java.awt.event.ActionListener.class, l);
    }

    protected java.beans.PropertyChangeListener createActionPropertyChangeListener(javax.swing.Action a) {
        // JDK uses a WeakReference-backed PCL (ButtonActionPropertyChangeListener)
        // so a long-lived Action can't keep a stale button alive. We use a
        // plain strong-ref listener: peer/emulator lifecycle is session-scoped
        // (attach/detach fires per UI reload), so leak risk is bounded to
        // session duration. Revisit if app-scoped singleton Actions turn out
        // to hold many historical buttons.
        return new ButtonActionPropertyChangeListener(this, a);
    }

    private static final class ButtonActionPropertyChangeListener
            implements java.beans.PropertyChangeListener, java.io.Serializable {
        private final AbstractButton button;
        private final javax.swing.Action action;

        ButtonActionPropertyChangeListener(AbstractButton button, javax.swing.Action action) {
            this.button = button;
            this.action = action;
        }

        @Override
        public void propertyChange(java.beans.PropertyChangeEvent e) {
            button.actionPropertyChanged(action, e.getPropertyName());
        }
    }

    public boolean getHideActionText() {
        return hideActionText;
    }

    public void setHideActionText(boolean hideActionText) {
        // Guarded on change, as the JDK is — and the guard is load-bearing here
        // rather than an optimisation, because it also gates the text resync
        // below. The JDK derives its old value by negation inside the guard
        // (`!hideActionText`), which is the real old value precisely because the
        // guard already established they differ.
        if (hideActionText != this.hideActionText) {
            this.hideActionText = hideActionText;
            // The reconfigure is deliverable: setTextFromAction reads this flag,
            // so toggling it shows or hides an installed Action's NAME as the
            // label — the toolbar idiom the property exists for. The `false`
            // matters: this is a full reconfigure, so hiding must *clear* the
            // stale text rather than merely decline to rewrite it.
            if (getAction() != null) {
                setTextFromAction(getAction(), false);
            }
            firePropertyChange("hideActionText", !hideActionText, hideActionText);
        }
    }

    public void setDisplayedMnemonicIndex(int index) throws java.lang.IllegalArgumentException {
        // JDK validates: -1 is sentinel ("none"), otherwise must be a
        // valid index into the button's text. Per R_match_swing_errors we replicate the
        // throw so user code catches the same programming error it
        // would under real Swing.
        java.lang.String text = getText();
        if (index < -1
                || (text == null && index != -1)
                || (text != null && index >= text.length())) {
            throw new java.lang.IllegalArgumentException(
                    "Invalid mnemonic index: " + index);
        }
        int old = this.displayedMnemonicIndex;
        this.displayedMnemonicIndex = index;
        firePropertyChange("displayedMnemonicIndex", old, index);
    }

    public void setMnemonic(char mnemonic) {
        // JDK source verbatim: lowercase-to-uppercase via ASCII delta,
        // then hand off to the int variant. Non-ASCII chars pass through.
        int vk = (int) mnemonic;
        if (vk >= 'a' && vk <= 'z') {
            vk -= ('a' - 'A');
        }
        setMnemonic(vk);
    }

    public void setMnemonic(int mnemonic) {
        // Swing stores mnemonic in ButtonModel and fires "mnemonic" PCE
        // AND registers an Alt+<key> WHEN_IN_FOCUSED_WINDOW accelerator
        // that invokes doClick. We keep the mnemonic on the button, not the
        // model, and keep the accelerator wiring: the whole point of a mnemonic in
        // a form is that Alt+S submits. Reuses JComponent's
        // registerKeyboardAction → Vaadin Shortcuts plumbing.
        int old = this.mnemonic;
        if (old == mnemonic) return;
        this.mnemonic = mnemonic;
        // Swap the Vaadin shortcut to match the new mnemonic.
        if (old != 0) {
            unregisterKeyboardAction(
                    javax.swing.KeyStroke.getKeyStroke(old, java.awt.event.InputEvent.ALT_DOWN_MASK));
        }
        if (mnemonic != 0) {
            // doClick pulses the model, as real Swing's mnemonic binding does.
            registerKeyboardAction(
                    e -> doClick(),
                    javax.swing.KeyStroke.getKeyStroke(mnemonic, java.awt.event.InputEvent.ALT_DOWN_MASK),
                    WHEN_IN_FOCUSED_WINDOW);
        }
        firePropertyChange("mnemonic", old, mnemonic);
    }

    public void setText(java.lang.String newText) {
        // AWT stores the value verbatim (null is legal). The peer gets ""
        // when newText is null — Vaadin's setText NPEs on null, and a
        // textless Button rendering blank is what the user asked for
        // anyway. firePropertyChange dedups equal values, so a no-op
        // setText doesn't re-fire.
        java.lang.String old = this.text;
        this.text = newText;
        withPeer(p -> {
            if (p instanceof com.vaadin.flow.component.HasText ht) ht.setText(newText != null ? newText : "");
        });
        firePropertyChange("text", old, newText);
    }

    public void setIcon(vaadinx.swing.Icon icon) {
        // R_swing_is_truth: store Swing-side field, push to peer, fire PCE. Path 1 of
        // the icon-rendering plan: when
        // the icon is a vaadinx.swing.ImageIcon, the bridge encodes its
        // raster as PNG and pushes a Vaadin Image to Button.setIcon. Other
        // Icon impls log via EHelper.onUnimplemented and clear the slot
        // (Path 2 / Path 3 deferred). Mnemonic-index refresh + revalidate
        // are L&F concerns we don't model.
        vaadinx.swing.Icon old = this.icon;
        this.icon = icon;
        // On the live UI rather than the peer's: an ImageIcon becomes a Vaadin Image,
        // whose ctor resolves a resource URL and so needs a current UI even while
        // the button is detached — JLabel.setIcon's case.
        withPeerOnLiveUI(false, p -> {
            if (p instanceof com.vaadin.flow.component.button.Button btn) {
                btn.setIcon(vaadinx.EHelper.toVaadinIconComponent("AbstractButton", icon));
            }
        });
        firePropertyChange("icon", old, icon);
    }

    public boolean isBorderPainted() {
        return borderPainted;
    }

    public void removeChangeListener(javax.swing.event.ChangeListener l) {
        // Mirrors removeActionListener above: EventListenerList.remove is
        // null-safe and a silent no-op for an unregistered listener.
        listenerList.remove(javax.swing.event.ChangeListener.class, l);
    }

    public void removeItemListener(java.awt.event.ItemListener l) {
        listenerList.remove(java.awt.event.ItemListener.class, l);
    }

    /** @return the listener {@link #setModel} installs on the model; shared with the other two */
    protected javax.swing.event.ChangeListener createChangeListener() {
        return getHandler();
    }

    /** @return the listener {@link #setModel} installs on the model; shared with the other two */
    protected java.awt.event.ActionListener createActionListener() {
        return getHandler();
    }

    /** @return the listener {@link #setModel} installs on the model; shared with the other two */
    protected java.awt.event.ItemListener createItemListener() {
        return getHandler();
    }

    private Handler getHandler() {
        if (handler == null) {
            handler = new Handler();
        }
        return handler;
    }

    /**
     * Re-fires the model's events as this button's, which is the whole of the button's event
     * fan-out: a click, {@link #doClick} and {@link #setSelected} all reach the listeners only
     * through the model. The JDK's mnemonic resync and repaint on a state change are not
     * reproduced — the mnemonic lives on the button here, and nothing paints.
     *
     * <p>Each event is relayed rather than run in place: a browser click fires it on the
     * request thread, where R_callswing_envelope's envelope applies, and a model mutated off the
     * UI thread fires it on that thread (SD_background_model_hop).
     */
    class Handler implements java.awt.event.ActionListener, javax.swing.event.ChangeListener,
            java.awt.event.ItemListener, java.io.Serializable {

        @Override
        public void stateChanged(javax.swing.event.ChangeEvent e) {
            vaadinx.EHelper.relayModelEvent(AbstractButton.this::fireStateChanged);
        }

        @Override
        public void actionPerformed(java.awt.event.ActionEvent event) {
            vaadinx.EHelper.relayModelEvent(() -> fireActionPerformed(event));
        }

        @Override
        public void itemStateChanged(java.awt.event.ItemEvent event) {
            vaadinx.EHelper.relayModelEvent(() -> {
                fireItemStateChanged(event);
                modelSelectionChanged();
            });
        }
    }

    /** Runs after the model's selection change reached the listeners; a menu item re-renders. */
    void modelSelectionChanged() {
    }

    public void addChangeListener(javax.swing.event.ChangeListener l) {
        // Mirrors addActionListener above. Notified on every model state transition
        // (armed / pressed / selected / enabled) through the Handler.
        listenerList.add(javax.swing.event.ChangeListener.class, l);
    }

    public void addItemListener(java.awt.event.ItemListener l) {
        // Symmetric to addChangeListener; notified on the model's selection changes.
        listenerList.add(java.awt.event.ItemListener.class, l);
    }

    /** Enables the component and its model, which is what gates {@link #doClick} and a click. */
    @Override
    public void setEnabled(boolean b) {
        if (!b && model.isRollover()) {
            model.setRollover(false);
        }
        super.setEnabled(b);
        model.setEnabled(b);
    }

    public void setUI(javax.swing.plaf.ButtonUI arg0) {
        vaadinx.EHelper.onUnimplemented("AbstractButton", "setUI", arg0);
    }

    public void setDisabledIcon(vaadinx.swing.Icon disabledIcon) {
        vaadinx.swing.Icon old = this.disabledIcon;
        this.disabledIcon = disabledIcon;
        firePropertyChange("disabledIcon", old, disabledIcon);
    }

    public void setDisabledSelectedIcon(vaadinx.swing.Icon disabledSelectedIcon) {
        vaadinx.swing.Icon old = this.disabledSelectedIcon;
        this.disabledSelectedIcon = disabledSelectedIcon;
        firePropertyChange("disabledSelectedIcon", old, disabledSelectedIcon);
    }

    @Override
    protected void addImpl(vaadinx.awt.Component comp, java.lang.Object constraints, int index) {
        // Swing's AbstractButton doesn't actually override addImpl — the
        // generator over-collected from inherited methods. Delegating to
        // Container.addImpl restores the standard add path. Keeping the
        // override (rather than deleting) makes the hand-finish intent
        // explicit and survives re-generation.
        super.addImpl(comp, constraints, index);
    }

    public void setAction(javax.swing.Action a) {
        // JDK's exact sequence: install only if the Action actually
        // changed (equals-based, so an Action equal to itself is a
        // no-op), tear down the old listener pair, seed properties,
        // wire the new listener pair, fire the "action" PCE.
        javax.swing.Action oldValue = this.action;
        if (oldValue == null ? a == null : oldValue.equals(a)) return;
        this.action = a;
        if (oldValue != null) {
            // Uninstall old: remove it as a click listener (added below
            // when it was installed) and detach our PCL from it so
            // mutations on the old Action no longer reach this button.
            removeActionListener(oldValue);
            if (actionPropertyChangeListener != null) {
                oldValue.removePropertyChangeListener(actionPropertyChangeListener);
                actionPropertyChangeListener = null;
            }
        }
        configurePropertiesFromAction(a);
        if (a != null) {
            // Don't double-register: if user code already called
            // addActionListener(action) before setAction(action), adding
            // again would dispatch twice on every click. isActionListener
            // is a linear scan — our listener lists stay small.
            if (!isActionListener(a)) {
                addActionListener(a);
            }
            actionPropertyChangeListener = createActionPropertyChangeListener(a);
            a.addPropertyChangeListener(actionPropertyChangeListener);
        }
        firePropertyChange("action", oldValue, a);
    }

    private boolean isActionListener(java.awt.event.ActionListener a) {
        for (java.awt.event.ActionListener l : listenerList.getListeners(java.awt.event.ActionListener.class)) {
            if (l == a) return true;
        }
        return false;
    }

    public void updateUI() {
        // L&F swap — no-op, same rationale as JButton.updateUI: our "UI"
        // is the Vaadin peer, which isn't pluggable.
    }

    public vaadinx.swing.Icon getPressedIcon() {
        return pressedIcon;
    }

    public vaadinx.swing.Icon getRolloverSelectedIcon() {
        return rolloverSelectedIcon;
    }

    public vaadinx.swing.Icon getRolloverIcon() {
        return rolloverIcon;
    }

    public boolean imageUpdate(java.awt.Image arg0, int arg1, int arg2, int arg3, int arg4, int arg5) {
        vaadinx.EHelper.onUnimplemented("AbstractButton", "imageUpdate", arg0, arg1, arg2, arg3, arg4, arg5);
        return false;
    }

    public void setBorderPainted(boolean borderPainted) {
        // Swing fires "borderPainted" PCE + repaint. Repaint is irrelevant
        // (Vaadin owns the DOM), PCE is what user MVC code listens for.
        boolean old = this.borderPainted;
        this.borderPainted = borderPainted;
        firePropertyChange("borderPainted", old, borderPainted);
    }

    public void setIconTextGap(int iconTextGap) {
        // Swing fires "iconTextGap" PCE; no bounds check in JDK source,
        // negatives are legal (just visually weird). Match behavior.
        int old = this.iconTextGap;
        this.iconTextGap = iconTextGap;
        firePropertyChange("iconTextGap", old, iconTextGap);
    }

    public void setContentAreaFilled(boolean contentAreaFilled) {
        boolean old = this.contentAreaFilled;
        this.contentAreaFilled = contentAreaFilled;
        firePropertyChange("contentAreaFilled", old, contentAreaFilled);
    }

    public javax.swing.plaf.ButtonUI getUI() {
        vaadinx.EHelper.onUnimplemented("AbstractButton", "getUI");
        return null;
    }

    public void setMargin(java.awt.Insets margin) {
        // Swing fires "margin" PCE + repaint. Repaint irrelevant here.
        // No defensive copy in JDK; callers owning the Insets and mutating
        // it after the set mutates our field too — matches JDK behavior.
        java.awt.Insets old = this.margin;
        this.margin = margin;
        firePropertyChange("margin", old, margin);
    }

    public java.awt.Insets getMargin() {
        return margin;
    }

    public void setPressedIcon(vaadinx.swing.Icon pressedIcon) {
        vaadinx.swing.Icon old = this.pressedIcon;
        this.pressedIcon = pressedIcon;
        firePropertyChange("pressedIcon", old, pressedIcon);
    }

    public void setSelectedIcon(vaadinx.swing.Icon selectedIcon) {
        vaadinx.swing.Icon old = this.selectedIcon;
        this.selectedIcon = selectedIcon;
        firePropertyChange("selectedIcon", old, selectedIcon);
    }

    public void setRolloverIcon(vaadinx.swing.Icon rolloverIcon) {
        vaadinx.swing.Icon old = this.rolloverIcon;
        this.rolloverIcon = rolloverIcon;
        firePropertyChange("rolloverIcon", old, rolloverIcon);
    }

    public void setRolloverSelectedIcon(vaadinx.swing.Icon rolloverSelectedIcon) {
        vaadinx.swing.Icon old = this.rolloverSelectedIcon;
        this.rolloverSelectedIcon = rolloverSelectedIcon;
        firePropertyChange("rolloverSelectedIcon", old, rolloverSelectedIcon);
    }

    public int getVerticalAlignment() {
        return verticalAlignment;
    }

    public void setVerticalAlignment(int alignment) {
        // JDK validates then stores; we mirror (IAE via checkVerticalKey
        // per R_match_swing_errors). No peer semantics — Vaadin Button owns its layout —
        // but the PCE still fires so user MVC wiring sees the change.
        // firePropertyChange dedups equal values.
        int old = this.verticalAlignment;
        this.verticalAlignment = checkVerticalKey(alignment, "verticalAlignment");
        firePropertyChange("verticalAlignment", old, verticalAlignment);
    }

    public int getHorizontalAlignment() {
        return horizontalAlignment;
    }

    public void setHorizontalAlignment(int alignment) {
        int old = this.horizontalAlignment;
        this.horizontalAlignment = checkHorizontalKey(alignment, "horizontalAlignment");
        firePropertyChange("horizontalAlignment", old, horizontalAlignment);
    }

    public int getVerticalTextPosition() {
        return verticalTextPosition;
    }

    public void setVerticalTextPosition(int textPosition) {
        int old = this.verticalTextPosition;
        this.verticalTextPosition = checkVerticalKey(textPosition, "verticalTextPosition");
        firePropertyChange("verticalTextPosition", old, verticalTextPosition);
    }

    public int getHorizontalTextPosition() {
        return horizontalTextPosition;
    }

    public void setHorizontalTextPosition(int textPosition) {
        int old = this.horizontalTextPosition;
        this.horizontalTextPosition = checkHorizontalKey(textPosition, "horizontalTextPosition");
        firePropertyChange("horizontalTextPosition", old, horizontalTextPosition);
    }

    public int getIconTextGap() {
        return iconTextGap;
    }

    protected void actionPropertyChanged(javax.swing.Action a, java.lang.String propertyName) {
        // Route per-property updates back through the same helpers
        // configurePropertiesFromAction uses. JDK passes interned strings
        // for the keys (Action.NAME, "enabled", …) so identity comparison
        // is safe and saves the equals cost on the hot path.
        if (propertyName == javax.swing.Action.NAME) {
            setTextFromAction(a, true);
        } else if ("enabled".equals(propertyName)) {
            setEnabled(a.isEnabled());
        } else if (propertyName == javax.swing.Action.SHORT_DESCRIPTION) {
            setToolTipTextFromAction(a);
        } else if (propertyName == javax.swing.Action.SMALL_ICON
                || propertyName == javax.swing.Action.LARGE_ICON_KEY) {
            setIconFromAction(a);
        } else if (propertyName == javax.swing.Action.ACTION_COMMAND_KEY) {
            setActionCommandFromAction(a);
        } else if (propertyName == javax.swing.Action.MNEMONIC_KEY) {
            setMnemonicFromAction(a);
            // Mnemonic index may clamp on the new text length; re-evaluate
            // so a mnemonic change doesn't leave stale index state.
            setDisplayedMnemonicIndexFromAction(a);
        } else if (propertyName == javax.swing.Action.DISPLAYED_MNEMONIC_INDEX_KEY) {
            setDisplayedMnemonicIndexFromAction(a);
        }
        // Unknown keys: JDK silently drops. We follow — user code adding
        // arbitrary Action.putValue("foo", bar) entries has no button
        // semantic and shouldn't trip a WARN.
    }

    public boolean isFocusPainted() {
        return focusPainted;
    }

    public void setFocusPainted(boolean focusPainted) {
        boolean old = this.focusPainted;
        this.focusPainted = focusPainted;
        firePropertyChange("focusPainted", old, focusPainted);
    }

    public boolean isContentAreaFilled() {
        return contentAreaFilled;
    }

    public int getDisplayedMnemonicIndex() {
        return displayedMnemonicIndex;
    }

    public void setMultiClickThreshhold(long threshhold) {
        // Swing throws IAE on negative; no PCE fired. Match both.
        if (threshhold < 0) {
            throw new java.lang.IllegalArgumentException("threshhold must be >= 0");
        }
        this.multiClickThreshhold = threshhold;
    }

    public long getMultiClickThreshhold() {
        return multiClickThreshhold;
    }

    /**
     * Moves the button's listeners from the old model to {@code newModel}, takes its enabled
     * state, hands it to the surrogate to render, and fires {@code "model"}. A {@code null}
     * model is legal, as in the JDK, and leaves a button whose state accessors throw.
     *
     * <p>The JDK's mnemonic resync from the new model is not reproduced: the mnemonic is the
     * button's own field here, not the model's.
     */
    public void setModel(javax.swing.ButtonModel newModel) {
        javax.swing.ButtonModel oldModel = getModel();
        if (oldModel != null) {
            oldModel.removeChangeListener(changeListener);
            oldModel.removeActionListener(actionListener);
            oldModel.removeItemListener(itemListener);
            changeListener = null;
            actionListener = null;
            itemListener = null;
        }
        model = newModel;
        if (newModel != null) {
            changeListener = createChangeListener();
            actionListener = createActionListener();
            itemListener = createItemListener();
            newModel.addChangeListener(changeListener);
            newModel.addActionListener(actionListener);
            newModel.addItemListener(itemListener);
            // JComponent's, past this class's override, as the JDK does: setModel can run from
            // a constructor before the button is initialised.
            super.setEnabled(newModel.isEnabled());
        }
        withPeer(p -> {
            if (p instanceof com.vaadin.swingbridge.surrogates.swing.AbstractButtonMixin abm) abm.setModel(newModel);
        });
        firePropertyChange(MODEL_CHANGED_PROPERTY, oldModel, newModel);
    }

    public javax.swing.event.ChangeListener[] getChangeListeners() {
        return listenerList.getListeners(javax.swing.event.ChangeListener.class);
    }

    protected void fireStateChanged() {
        // One ChangeEvent per button, allocated on first use, as the JDK does: its only state is
        // the source. getListeners copies, so a listener removing itself mid-dispatch is safe.
        for (javax.swing.event.ChangeListener l :
                listenerList.getListeners(javax.swing.event.ChangeListener.class)) {
            if (changeEvent == null) {
                changeEvent = new javax.swing.event.ChangeEvent(this);
            }
            l.stateChanged(changeEvent);
        }
    }

    public java.awt.event.ActionListener[] getActionListeners() {
        // Empty array, never null — AWT contract; EventListenerList.getListeners
        // allocates a fresh array on each call so callers can iterate
        // without worrying about live snapshots.
        return listenerList.getListeners(java.awt.event.ActionListener.class);
    }

    /**
     * Delivers {@code event} with this button as its source, as the JDK does; a model's event
     * carries no command when the model has none, and the button's {@link #getActionCommand}
     * stands in.
     */
    protected void fireActionPerformed(java.awt.event.ActionEvent event) {
        // Null-guard for parity with Component's process* family — a misuse here shouldn't
        // crash a smoke test.
        if (event == null) return;
        java.awt.event.ActionEvent e = null;
        for (java.awt.event.ActionListener l :
                listenerList.getListeners(java.awt.event.ActionListener.class)) {
            if (e == null) {
                java.lang.String actionCommand = event.getActionCommand();
                if (actionCommand == null) {
                    actionCommand = getActionCommand();
                }
                e = new java.awt.event.ActionEvent(this, java.awt.event.ActionEvent.ACTION_PERFORMED,
                        actionCommand, event.getWhen(), event.getModifiers());
            }
            l.actionPerformed(e);
        }
    }

    /** Delivers {@code event} with this button as both source and item, as the JDK does. */
    protected void fireItemStateChanged(java.awt.event.ItemEvent event) {
        if (event == null) return;
        java.awt.event.ItemEvent e = null;
        for (java.awt.event.ItemListener l :
                listenerList.getListeners(java.awt.event.ItemListener.class)) {
            if (e == null) {
                e = new java.awt.event.ItemEvent(this, java.awt.event.ItemEvent.ITEM_STATE_CHANGED,
                        this, event.getStateChange());
            }
            l.itemStateChanged(e);
        }
    }

    public void setLabel(java.lang.String label) {
        // Deprecated 1.0 alias for setText. Route through the public
        // setter so user overrides on setText still fire.
        setText(label);
    }

    public java.awt.event.ItemListener[] getItemListeners() {
        return listenerList.getListeners(java.awt.event.ItemListener.class);
    }

    /** @return the button's text while it is selected, {@code null} otherwise */
    public java.lang.Object[] getSelectedObjects() {
        if (isSelected() == false) {
            return null;
        }
        java.lang.Object[] selectedObjects = new java.lang.Object[1];
        selectedObjects[0] = getText();
        return selectedObjects;
    }

}
