/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JCheckBox
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JCheckBox
// Hand-finished. Subclass of JToggleButton, which carries all of the
// model-side logic (the emulator-owned ToggleButtonModel, its ItemEvent /
// ChangeEvent fan-out, the peer it hands the model to). JCheckBox itself is
// the set of constructors plus the "paint flat" toggle — everything else is
// inherited. Its peer is SJCheckBox, a Vaadin Checkbox; a bare JToggleButton
// renders as a stays-pressed Button instead (SD_sjtogglebutton_button_peer).

/** Emulator for {@link javax.swing.JCheckBox}. */
public class JCheckBox extends vaadinx.swing.JToggleButton implements javax.accessibility.Accessible {

    /** Bound-property name fired by {@link #setBorderPaintedFlat}. */
    public static final String BORDER_PAINTED_FLAT_CHANGED_PROPERTY = "borderPaintedFlat";

    // Swing default is false: checkboxes render their border only when
    // inside a toolbar. Round-trip the field so user code reading back
    // the value stays honest; no peer semantics since Vaadin Checkbox
    // manages its own chrome.
    private boolean borderPaintedFlat;

    public JCheckBox() {
        this(null, null, false);
    }

    public JCheckBox(vaadinx.swing.Icon icon) {
        this(null, icon, false);
    }

    public JCheckBox(vaadinx.swing.Icon icon, boolean selected) {
        this(null, icon, selected);
    }

    public JCheckBox(java.lang.String text) {
        this(text, null, false);
    }

    public JCheckBox(java.lang.String text, boolean selected) {
        this(text, null, selected);
    }

    public JCheckBox(java.lang.String text, vaadinx.swing.Icon icon) {
        this(text, icon, false);
    }

    public JCheckBox(javax.swing.Action action) {
        this();
        setAction(action);
    }

    public JCheckBox(java.lang.String text, vaadinx.swing.Icon icon, boolean selected) {
        // Root ctor — the peer is an SJCheckBox surrogate (SD_toggle_checkbox_first_cut), rendering
        // the ToggleButtonModel JToggleButton's ctor installs; the surrogate IS-A Checkbox, so
        // test code locating by Checkbox.class still resolves.
        super(com.vaadin.swingbridge.surrogates.SJCheckBox.class, com.vaadin.swingbridge.surrogates.SJCheckBox::new);
        initToggle(text, icon, selected);
    }

    public boolean isBorderPaintedFlat() {
        return borderPaintedFlat;
    }

    public void setBorderPaintedFlat(boolean b) {
        // Swing fires "borderPaintedFlat" PCE. No peer semantics; the
        // field is advisory.
        boolean old = this.borderPaintedFlat;
        this.borderPaintedFlat = b;
        firePropertyChange(BORDER_PAINTED_FLAT_CHANGED_PROPERTY, old, b);
    }

    public java.lang.String getUIClassID() {
        return "CheckBoxUI";
    }

    public void updateUI() {
        // L&F swap — same rationale as JToggleButton.updateUI.
    }

    protected java.lang.String paramString() {
        return super.paramString() + ",borderPaintedFlat=" + borderPaintedFlat;
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JCheckBox", "getAccessibleContext");
        return null;
    }
}
