/*
 * Copyright (c) 1997, 2024, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JComponent
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JComponent, then hand-finished.

/** Emulator for {@link javax.swing.JComponent}. */
public abstract class JComponent extends vaadinx.awt.Container implements java.io.Serializable {

    public JComponent() {
        this(new com.vaadin.flow.component.html.Div() /* placeholder peer of the generated fallback ctor; every real ctor passes its own */);
        vaadinx.EHelper.onUnimplemented("JComponent", "<init>");
    }

    protected JComponent(com.vaadin.flow.component.Component peer) {
        super(peer);
        installDefaults();
    }

    /**
     * Install this class's L&amp;F colours and {@code opaque} flag, as
     * {@code LookAndFeel.installColorsAndFont} does from the UI delegate the JDK
     * would have attached — see
     * <a href="../../../../../../emulators/decisions.md#D_theme_is_lookandfeel">D_theme_is_lookandfeel</a>.
     *
     * <p>Runs from the constructor, before any subclass body, so a subclass or
     * migrated user code that sets its own colour overwrites the default rather
     * than racing it — the JDK's ordering, where {@code updateUI()} installs and
     * the app then overrides.
     *
     * <p>The values land as {@code ColorUIResource}, which is what keeps
     * {@code getBackground()} non-null (so {@code getBackground().darker()}
     * cannot NPE) while still rendering as the theme's colour rather than as
     * Metal's literal grey.
     *
     * <p>{@link LookAndFeelDefaults#prefixFor} walks up the hierarchy, so a
     * migrator's {@code class MyPanel extends JPanel} installs {@code Panel}'s
     * defaults. A class with nothing in its chain installs nothing and keeps
     * AWT's walk-to-parent behaviour.
     */
    private void installDefaults() {
        java.awt.Color bg = LookAndFeelDefaults.background(getClass());
        if (bg != null) setBackground(bg);
        java.awt.Color fg = LookAndFeelDefaults.foreground(getClass());
        if (fg != null) setForeground(fg);
        if (LookAndFeelDefaults.opaque(getClass())) setOpaque(true);
    }

    // Keybinding-condition constants, identical values to javax.swing.JComponent.
    // Generator dropped these (public static final ints — not method
    // signatures). Migrated code that passes JComponent.WHEN_IN_FOCUSED_WINDOW
    // to registerKeyboardAction/getInputMap/setInputMap needs them back.
    public static final int WHEN_FOCUSED = 0;
    public static final int WHEN_ANCESTOR_OF_FOCUSED_COMPONENT = 1;
    public static final int WHEN_IN_FOCUSED_WINDOW = 2;

    // Undefined condition returned by getConditionForKeyStroke when the
    // stroke isn't bound in any InputMap. Matches JDK's sentinel.
    public static final int UNDEFINED_CONDITION = -1;

    // Swing's JComponent default is false (transparent); AWT's Component is true.
    // Tracked locally so isOpaque reflects setOpaque calls rather than the
    // inherited AWT truthy default — and so paramString can report it.
    private boolean opaque = false;

    // Swing default false — popup menus are per-component unless the app opts
    // in. Stored though the inheritance is not modelled: R_decline_effect_only (D_owed_events).
    private boolean inheritsPopupMenu = false;

    // Swing default true. Stored though the traversal gate is not modelled.
    private boolean verifyInputWhenFocusTarget = true;

    // Lazy so the common "JComponent created but never tagged" case adds no
    // field allocation. Created on first putClientProperty; shared between
    // put and get so null values round-trip as absence (Swing contract).
    private java.util.Map<java.lang.Object, java.lang.Object> clientProperties;

    // The JDK's alignment pair is a value plus an is-set flag, and the flag is
    // load-bearing: unset reads fall through to Component's 0.5f, and JLabel's
    // ctor sets X to 0.0f, so a plain field would answer 0.5f where real Swing
    // answers 0.0f. R_decline_effect_only — the paint-time effect is what drops.
    private float alignmentX;
    private float alignmentY;
    private boolean alignmentXSet;
    private boolean alignmentYSet;

    // Swing defaults: autoscrolls false, requestFocusEnabled true (the JDK
    // stores the latter inverted, as a REQUEST_FOCUS_DISABLED flag), double
    // buffering off until a ctor turns it on (JPanel and JRootPane do).
    private boolean autoscrolls;
    private boolean requestFocusEnabled = true;
    private boolean doubleBuffered;

    // DebugGraphics keeps this in an AppContext-wide Hashtable keyed by
    // component, which is a field by another name.
    private int debugGraphicsOptions;

    /**
     * Client-property key the tooltip text is stored under, as in the JDK —
     * which is also why {@code "ToolTipText"} is the bound-property name
     * {@link #setToolTipText} fires: it fires because
     * {@link #putClientProperty} fires, not on its own account (D_property_fanout_audit).
     */
    public static final java.lang.String TOOL_TIP_TEXT_KEY = "ToolTipText";

    // Installed border, if any. Null until setBorder lands a value. When
    // it's an AbstractBorder, setBorder dispatches through its applyCss
    // hook to write the CSS onto the peer; getInsets reads through the
    // stored border so migrated layout code sees the right spacing.
    private vaadinx.swing.border.Border border;

    // Installed InputVerifier, if any. Null until setInputVerifier lands
    // a value. Paired with blurListenerRegistration so we can uninstall
    // the peer-side blur listener when the verifier is replaced/cleared.
    private vaadinx.swing.InputVerifier inputVerifier;
    private com.vaadin.flow.shared.Registration blurListenerRegistration;

    // Keybinding storage. Lazily allocated — a JComponent that never
    // installs a keybinding pays no field cost. InputMaps split by
    // condition per the JDK contract (different conditions can bind the
    // same KeyStroke to different action keys).
    private javax.swing.InputMap focusedInputMap;
    private javax.swing.InputMap ancestorInputMap;
    private javax.swing.InputMap windowInputMap;
    private javax.swing.ActionMap actionMap;

    // Vaadin shortcut registrations we've installed on behalf of the
    // InputMap/ActionMap — keyed by (condition, KeyStroke) so
    // unregisterKeyboardAction and setInputMap replacement can remove them.
    // Lazily allocated; null when no keybinding has ever been installed.
    private java.util.Map<ShortcutKey, com.vaadin.flow.component.ShortcutRegistration> installedShortcuts;

    // Vetoable change support (JComponent's JavaBean-spec listener family,
    // separate from Component's PropertyChangeSupport). Lazily created —
    // most JComponents never install a vetoable listener.
    private java.beans.VetoableChangeSupport vetoableChangeSupport;

    private java.beans.VetoableChangeSupport vetoableChangeSupport() {
        if (vetoableChangeSupport == null) {
            vetoableChangeSupport = new java.beans.VetoableChangeSupport(this);
        }
        return vetoableChangeSupport;
    }

    /**
     * Identity key for a (condition, KeyStroke) pair. Plain record because
     * ShortcutRegistration is tied to both — removing the stroke under one
     * condition must leave the same stroke under another condition alone.
     */
    private record ShortcutKey(int condition, javax.swing.KeyStroke keyStroke) {}

    public void update(java.awt.Graphics arg0) {
        // Real Swing's JComponent.update delegates to paint (skipping AWT's
        // background-clear optimization). Container.update already chains
        // into paint, which recurses into children; that matches the Swing
        // dispatch shape under R_layouts_close_enough (no real painting, but children still
        // walked so user paint overrides on leaves fire — R_swing_is_truth).
        super.update(arg0);
    }

    public boolean contains(int arg0, int arg1) {
        // AWT's Component.contains is the rectangle hit-test; real Swing
        // extends it to ask the UI delegate first. We have no UI delegate
        // (R_layouts_close_enough — the browser owns hit-testing), so the AWT rectangle test is
        // the closest honest answer.
        return super.contains(arg0, arg1);
    }

    public java.awt.Rectangle getBounds(java.awt.Rectangle arg0) {
        // AWT fills the caller-provided Rectangle from getBounds() to avoid
        // an allocation. Component.getBounds(Rectangle) already does that;
        // JComponent adds no semantics on top.
        return super.getBounds(arg0);
    }

    public java.awt.Point getLocation(java.awt.Point arg0) {
        // AWT fill-the-arg variant of getLocation(). Component handles both.
        return super.getLocation(arg0);
    }

    public void print(java.awt.Graphics arg0) {
        // Container.print walks children so user overrides fire (R_swing_is_truth). Paint
        // itself is R_layouts_close_enough — no pixels reach the browser — but the dispatch
        // shape matters for user code that overrides printComponent et al.
        super.print(arg0);
    }

    public java.awt.Dimension getSize(java.awt.Dimension arg0) {
        // AWT fill-the-arg variant; Component handles both (and respects
        // explicit setSize).
        return super.getSize(arg0);
    }

    public void setOpaque(boolean arg0) {
        // Opacity is half of a colour intent, not an independent flag: a Swing
        // app says "paint me red" with the pair setOpaque(true) +
        // setBackground(red), so neither setter can be the only one that
        // evaluates the rule. Both funnel through applyBackgroundToPeer, which
        // is what makes the gate two-directional — the one-shot version this
        // replaced let a later setBackground write through a non-opaque
        // component, silently "fixing" Swing's paper cut that a JLabel with a
        // background set paints nothing (R_no_silent_improvements).
        //
        // Field shadow round-trips so isOpaque() reports what callers set;
        // "opaque" PCE fires so migrated MVC sees transitions.
        boolean old = this.opaque;
        if (old == arg0) return;
        this.opaque = arg0;
        applyBackgroundToPeer();
        firePropertyChange("opaque", old, arg0);
    }

    protected java.lang.String paramString() {
        // AWT pattern: chain to super, then append JComponent's own fields.
        // Swing appends a handful of booleans — opaque and doubleBuffered
        // cover the ones we track; the rest (autoscrolls, verifier, etc.)
        // aren't yet honored so listing them would be misleading.
        java.lang.String s = super.paramString();
        return s + ",opaque=" + opaque + ",doubleBuffered=" + isDoubleBuffered();
    }

    public boolean isOpaque() {
        // Swing default is false (flipped from AWT's true — see Component's
        // isOpaque comment). Backed by setOpaque so the value round-trips.
        return opaque;
    }

    public void enable() {
        // Deprecated AWT 1.0 alias; Component's override already routes to
        // setEnabled(true).
        super.enable();
    }

    public java.awt.Graphics getGraphics() {
        // Component returns a Graphics backed by a 1x1 off-screen
        // BufferedImage so every method works (drawRect, setColor,
        // getFontMetrics, …) and just paints into nowhere visible —
        // beats null-and-NPE for R_layouts_close_enough.
        return super.getGraphics();
    }

    public vaadinx.swing.JRootPane getRootPane() {
        // Walk up getParent() until we hit a JFrame ancestor
        // and return its root pane. JDK does the same — SwingUtilities
        // .getRootPane iterates parents. Null when the component isn't
        // attached to a JFrame yet; user code that reads getRootPane
        // from a ctor before attach sees null, matching Swing.
        for (vaadinx.awt.Container p = getParent(); p != null; p = p.getParent()) {
            if (p instanceof vaadinx.swing.JFrame frame) {
                return frame.getRootPane();
            }
        }
        return null;
    }

    public void firePropertyChange(java.lang.String arg0, boolean arg1, boolean arg2) {
        // Swing's JComponent widens visibility from protected (Component)
        // to public. Delegation is the entire override body — no new
        // behavior, just API surface.
        super.firePropertyChange(arg0, arg1, arg2);
    }

    public void firePropertyChange(java.lang.String arg0, char arg1, char arg2) {
        // Component's char overload is already public; this override is
        // redundant but we keep it to mirror Swing's API shape and give
        // JComponent's javadoc something to bind to.
        super.firePropertyChange(arg0, arg1, arg2);
    }

    public void firePropertyChange(java.lang.String arg0, int arg1, int arg2) {
        // Widens visibility from protected (Component) to public — see the
        // boolean overload's rationale.
        super.firePropertyChange(arg0, arg1, arg2);
    }

    /**
     * @return what {@link #setInheritsPopupMenu} stored; Swing's default is
     *     {@code false}. Reports the request faithfully even though the
     *     inheritance has no effect — see the setter.
     */
    public boolean getInheritsPopupMenu() {
        return inheritsPopupMenu;
    }

    /** Installed component popup, or null until {@link #setComponentPopupMenu} lands one (D_jpopupmenu). */
    private vaadinx.swing.JPopupMenu componentPopup;

    public vaadinx.swing.JPopupMenu getComponentPopupMenu() {
        // D_jpopupmenu: ported from the javax.swing.JPopupMenu stub to the emulator
        // type. Null until setComponentPopupMenu installs one.
        return componentPopup;
    }

    public boolean isManagingFocus() {
        // Deprecated since Swing 1.4, replaced by the focus-traversal
        // keys API we don't model either (R_infra_not_surface). Swing default is false.
        return false;
    }

    /**
     * The locale every {@code JFrame} / {@code JDialog} / {@code JWindow} is
     * born with — their {@code frameInit} / {@code dialogInit} /
     * {@code windowInit} all open by calling
     * {@code setLocale(JComponent.getDefaultLocale())}, as the JDK's do.
     *
     * <p>Real Swing scopes this to an {@code AppContext} — per *app*,
     * not per JVM — so answering per-UI is that scoping reproduced
     * rather than invented (same reasoning as D_window_registry's tab
     * scope). The JVM default would name the *server's* locale, making
     * every user of a multi-user app see whatever the host happens to
     * run under.
     *
     * @return what {@link #setDefaultLocale} last stored on this UI; failing that the
     *         browser's locale (Accept-Language, via the current UI), and outside a
     *         Vaadin request the JVM default
     */
    public static java.util.Locale getDefaultLocale() {
        com.vaadin.flow.component.UI ui = com.vaadin.flow.component.UI.getCurrent();
        if (ui == null) {
            return java.util.Locale.getDefault();
        }
        DefaultLocale set = com.vaadin.flow.component.ComponentUtil.getData(ui, DefaultLocale.class);
        return set != null && set.value != null ? set.value : ui.getLocale();
    }

    /** Holder for {@link #setDefaultLocale}'s per-UI value — {@code null} means "unset". */
    private static final class DefaultLocale {
        private java.util.Locale value;
    }

    public void revalidate() {
        // Component.revalidate implements the real tree walk — find the
        // nearest validate-root ancestor, call validate on it. Same shape
        // Swing expects; no JComponent-specific extras in our model.
        super.revalidate();
    }

    public void repaint(java.awt.Rectangle arg0) {
        // Component has (int,int,int,int) but not the Rectangle overload;
        // route through the int form so both repaint paths land in the
        // same Component.repaint no-op family. Null-guard matches Swing's
        // own tolerance — real JComponent treats null as "whole component".
        if (arg0 == null) {
            super.repaint();
        } else {
            super.repaint(arg0.x, arg0.y, arg0.width, arg0.height);
        }
    }

    public void repaint(long arg0, int arg1, int arg2, int arg3, int arg4) {
        // Real Swing routes through the RepaintManager; we don't have one
        // (R_layouts_close_enough — the browser repaints on DOM change). Component's 5-arg
        // repaint is in the no-op family already.
        super.repaint(arg0, arg1, arg2, arg3, arg4);
    }

    public final void putClientProperty(java.lang.Object arg0, java.lang.Object arg1) {
        // Swing contract: a null value removes the mapping (so
        // getClientProperty reports "unset" again). Fires a
        // PropertyChangeEvent named after the key — toString() is what real
        // Swing uses; null keys aren't meaningful here either (Swing NPEs
        // on null keys; we match to surface programming errors, per D_never_fail_on_gaps).
        java.util.Objects.requireNonNull(arg0, "key");
        java.lang.Object old = clientProperties == null ? null : clientProperties.get(arg0);
        if (java.util.Objects.equals(old, arg1)) return;
        if (arg1 == null) {
            if (clientProperties != null) clientProperties.remove(arg0);
        } else {
            if (clientProperties == null) clientProperties = new java.util.HashMap<>();
            clientProperties.put(arg0, arg1);
        }
        // Swing fires on Object.toString() of the key — a String key is by
        // far the common case, so listeners registered for a property name
        // pick up the change the way they expect.
        firePropertyChange(arg0.toString(), old, arg1);
    }

    public void setFont(java.awt.Font arg0) {
        // Component.setFont writes CSS font-family / size / style to the
        // peer and fires a PropertyChangeEvent. Swing's JComponent adds
        // nothing beyond invalidating cached text metrics we don't cache.
        super.setFont(arg0);
    }

    public boolean isOptimizedDrawingEnabled() {
        // Swing default is true — "children don't overlap, so a dirty
        // child doesn't require repainting its siblings." We don't paint
        // at all (R_layouts_close_enough), so the flag has no observable effect; true keeps
        // any optimization-aware code path running at full speed.
        return true;
    }

    public int getWidth() {
        // Component.getWidth is a stub returning 0 until layout-side
        // numbers land (layout dispatch model). Chain up so the
        // fix lands in one place when we implement it.
        return super.getWidth();
    }

    public int getHeight() {
        // See getWidth — Component-level stub, chain is preparation.
        return super.getHeight();
    }

    public static boolean isLightweightComponent(vaadinx.awt.Component arg0) {
        // Real Swing: any Component that isn't a Window is lightweight.
        // Our Components follow the same dichotomy — Windows back onto
        // Dialog peers, everything else paints into a parent's element.
        // Null gets Swing's own NPE (Component arg isn't expected null).
        return !(arg0 instanceof vaadinx.awt.Window);
    }

    public void paint(java.awt.Graphics arg0) {
        // Real Swing's paint calls paintComponent + paintBorder +
        // paintChildren. We skip that dispatch (R_layouts_close_enough/R_swing_is_truth — painting is
        // exempt from the R_swing_is_truth "reproduce Swing's dispatch" rule) and lean
        // on Container.paint, which walks children so user paint overrides
        // on leaves still fire.
        super.paint(arg0);
    }

    public void printAll(java.awt.Graphics arg0) {
        // Component.printAll is in the paint no-op family. Chain up so
        // we participate when a later slice wires print.
        super.printAll(arg0);
    }

    public vaadinx.swing.border.Border getBorder() {
        // Returns the installed border, or null when none. Field-backed —
        // AbstractBorder concrete subclasses drive CSS
        // on the peer via applyCss, while custom user borders store the
        // reference without any CSS side-effect.
        return border;
    }

    protected void paintBorder(java.awt.Graphics arg0) {
        // Paint pipeline is permanent sub-bucket (b) per
        // R_match_swing_errors — `Graphics`-based painting has no Vaadin counterpart and won't
        // graduate. Bucket B onNoop instead of WARN: user code calling
        // paintBorder directly is exercising a hook our paint chain doesn't
        // reach (R_layouts_close_enough/R_swing_is_truth-paint-exempt), but there's no missing-stub signal to
        // surface.
        vaadinx.EHelper.onNoop("JComponent", "paintBorder");
    }

    protected java.awt.Graphics getComponentGraphics(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "getComponentGraphics");
        return null;
    }

    public boolean isDoubleBuffered() {
        return doubleBuffered;
    }

    protected void paintComponent(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "paintComponent");
    }

    protected void printComponent(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "printComponent");
    }

    protected void printBorder(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "printBorder");
    }

    protected void paintChildren(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "paintChildren");
    }

    protected void printChildren(java.awt.Graphics arg0) {
        // Bucket B onNoop — see paintBorder.
        vaadinx.EHelper.onNoop("JComponent", "printChildren");
    }

    @Deprecated
    public vaadinx.awt.Component getNextFocusableComponent() {
        return (vaadinx.awt.Component) getClientProperty(NEXT_FOCUS);
    }

    /**
     * Stored as the JDK's {@code "nextFocus"} client property rather than a
     * field, which is what makes the {@code "nextFocus"} {@code PropertyChangeEvent}
     * fire — {@link #putClientProperty} fires it, here as in the JDK. What drops is
     * the traversal effect: the JDK's register/deregister pair hands the component
     * to the focus subsystem, and {@code transferFocus} here walks the emulator
     * tree instead (D_focus_managers).
     *
     * @param arg0 {@code null} clears the override
     */
    @Deprecated
    public void setNextFocusableComponent(vaadinx.awt.Component arg0) {
        vaadinx.EHelper.onNoop("JComponent", "setNextFocusableComponent");
        putClientProperty(NEXT_FOCUS, arg0);
    }

    /** The JDK's own client-property key for {@link #setNextFocusableComponent}. */
    private static final java.lang.String NEXT_FOCUS = "nextFocus";

    public final java.lang.Object getClientProperty(java.lang.Object arg0) {
        // Null key gets null (not an NPE): Swing's own JComponent tolerates
        // a null read even though the write NPEs. Missing keys also return
        // null — the same answer used to mean "not set".
        if (arg0 == null || clientProperties == null) return null;
        return clientProperties.get(arg0);
    }

    public void requestFocus() {
        // Component.requestFocus routes to the peer's Focusable.focus() and
        // moves the server-side focus pointer with it. Vaadin queues the focus
        // call and applies it on the browser after the next render — so a
        // post-show requestFocus from a ctor lands cleanly. Swing's JComponent
        // adds only the isRequestFocusEnabled gate on top, which we always
        // answer true (see below), so there's nothing to add here.
        super.requestFocus();
    }

    public boolean requestFocus(boolean temporary) {
        // JDK widens Component's protected overload to public on JComponent;
        // the behaviour is Component's (our peers can't distinguish temporary
        // from permanent focus).
        return super.requestFocus(temporary);
    }

    public boolean requestFocusInWindow() {
        // Same peer route as requestFocus: there is one window per browser tab,
        // so "in window" adds no constraint we could enforce differently.
        return super.requestFocusInWindow();
    }

    protected boolean requestFocusInWindow(boolean temporary) {
        return super.requestFocusInWindow(temporary);
    }

    public java.awt.FontMetrics getFontMetrics(java.awt.Font arg0) {
        // Component.getFontMetrics delegates to Toolkit.getDefaultToolkit()
        // — the closest we can get to real metrics without a live paint
        // pipeline. Honest answer for code that measures text width.
        return super.getFontMetrics(arg0);
    }

    public void setPreferredSize(java.awt.Dimension arg0) {
        // Component.setPreferredSize stores the field and writes CSS
        // min-width / min-height to the peer. Swing's JComponent adds
        // no extra behavior on top.
        super.setPreferredSize(arg0);
    }

    public java.awt.Dimension getPreferredSize() {
        // Component returns a defensive copy of the stored dimension (or
        // a zero Dimension if unset). Defensive-copy contract is what
        // migrated code needs; don't re-stub that.
        return super.getPreferredSize();
    }

    public void setMaximumSize(java.awt.Dimension arg0) {
        super.setMaximumSize(arg0);
    }

    public java.awt.Dimension getMaximumSize() {
        return super.getMaximumSize();
    }

    public void setMinimumSize(java.awt.Dimension arg0) {
        super.setMinimumSize(arg0);
    }

    public java.awt.Dimension getMinimumSize() {
        return super.getMinimumSize();
    }

    public java.awt.Insets getInsets(java.awt.Insets arg0) {
        // Fill-the-arg variant. Real Swing delegates to the border's
        // getBorderInsets; with no border installed, route through the
        // no-arg Container.getInsets (which reports zero insets) and copy.
        // Null arg: Swing allocates a fresh Insets — match.
        java.awt.Insets from = getInsets();
        if (arg0 == null) return from;
        arg0.top = from.top;
        arg0.left = from.left;
        arg0.bottom = from.bottom;
        arg0.right = from.right;
        return arg0;
    }

    public java.awt.Insets getInsets() {
        // JDK's JComponent.getInsets reads the installed border's insets,
        // falling back to zero when no border is installed. Matches so
        // migrated layout code that subtracts insets before placing
        // children sees the right numbers — even though our browser-side
        // layout is driven by CSS, not Swing insets (R_layouts_close_enough).
        if (border != null) {
            return border.getBorderInsets(this);
        }
        return super.getInsets();
    }

    public float getAlignmentY() {
        return alignmentYSet ? alignmentY : super.getAlignmentY();
    }

    public float getAlignmentX() {
        return alignmentXSet ? alignmentX : super.getAlignmentX();
    }

    public final javax.swing.InputMap getInputMap() {
        // JDK default: WHEN_FOCUSED — the "per-component" map.
        return getInputMap(WHEN_FOCUSED);
    }

    public final javax.swing.InputMap getInputMap(int condition) {
        // Lazy allocation: a component that never reads its InputMap
        // doesn't carry the allocation. Returning a live map that user
        // code can mutate is part of Swing's contract (idiomatic
        // `getInputMap().put(ks, key)` pattern), so we store-on-first-touch.
        return switch (condition) {
            case WHEN_FOCUSED -> {
                if (focusedInputMap == null) focusedInputMap = new javax.swing.InputMap();
                yield focusedInputMap;
            }
            case WHEN_ANCESTOR_OF_FOCUSED_COMPONENT -> {
                if (ancestorInputMap == null) ancestorInputMap = new javax.swing.InputMap();
                yield ancestorInputMap;
            }
            case WHEN_IN_FOCUSED_WINDOW -> {
                if (windowInputMap == null) windowInputMap = new javax.swing.InputMap();
                yield windowInputMap;
            }
            // JDK throws IllegalArgumentException for unknown conditions.
            // Match per R_match_swing_errors/D_never_fail_on_gaps — the never-fail rule scopes to incomplete
            // emulation, not input errors Swing itself rejects.
            default -> throw new IllegalArgumentException(
                    "condition must be one of WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, WHEN_IN_FOCUSED_WINDOW");
        };
    }

    public final javax.swing.ActionMap getActionMap() {
        if (actionMap == null) actionMap = new javax.swing.ActionMap();
        return actionMap;
    }

    public void registerKeyboardAction(java.awt.event.ActionListener listener,
                                       javax.swing.KeyStroke stroke,
                                       int condition) {
        registerKeyboardAction(listener, null, stroke, condition);
    }

    public void registerKeyboardAction(java.awt.event.ActionListener listener,
                                       java.lang.String command,
                                       javax.swing.KeyStroke stroke,
                                       int condition) {
        // JDK shape: wrap the listener in an ActionStandin so the same
        // Action object can serve as both the InputMap value (identifier)
        // and the ActionMap key+value. User code that reads back the
        // ActionMap sees a real Action it can invoke, including on
        // mnemonic paths.
        javax.swing.InputMap im = getInputMap(condition);
        javax.swing.ActionMap am = getActionMap();
        ActionStandin action = new ActionStandin(listener, command);
        im.put(stroke, action);
        am.put(action, action);
        installVaadinShortcut(condition, stroke, action);
    }

    public void unregisterKeyboardAction(javax.swing.KeyStroke stroke) {
        // JDK removes across every condition. We mirror: walk all three
        // InputMaps, drop the stroke (and its ActionMap entry by
        // identifier), uninstall the matching Vaadin shortcut.
        for (int condition : new int[]{WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, WHEN_IN_FOCUSED_WINDOW}) {
            javax.swing.InputMap im = rawInputMap(condition);
            if (im == null) continue;
            Object key = im.get(stroke);
            if (key == null) continue;
            im.remove(stroke);
            if (actionMap != null) actionMap.remove(key);
            uninstallShortcut(condition, stroke);
        }
    }

    public javax.swing.KeyStroke[] getRegisteredKeyStrokes() {
        // Union of strokes registered across all three conditions. Order
        // matches the InputMap walk (focused/ancestor/window); JDK makes
        // no ordering promise so any stable order is fine.
        java.util.LinkedHashSet<javax.swing.KeyStroke> strokes = new java.util.LinkedHashSet<>();
        for (int condition : new int[]{WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, WHEN_IN_FOCUSED_WINDOW}) {
            javax.swing.InputMap im = rawInputMap(condition);
            if (im == null) continue;
            javax.swing.KeyStroke[] keys = im.allKeys();
            if (keys != null) {
                java.util.Collections.addAll(strokes, keys);
            }
        }
        return strokes.toArray(new javax.swing.KeyStroke[0]);
    }

    public int getConditionForKeyStroke(javax.swing.KeyStroke stroke) {
        // JDK returns UNDEFINED_CONDITION (-1) when the stroke isn't
        // bound. Walk in the order JDK documents: focused first, then
        // ancestor, then window.
        if (focusedInputMap != null && focusedInputMap.get(stroke) != null) return WHEN_FOCUSED;
        if (ancestorInputMap != null && ancestorInputMap.get(stroke) != null) return WHEN_ANCESTOR_OF_FOCUSED_COMPONENT;
        if (windowInputMap != null && windowInputMap.get(stroke) != null) return WHEN_IN_FOCUSED_WINDOW;
        return UNDEFINED_CONDITION;
    }

    public java.awt.event.ActionListener getActionForKeyStroke(javax.swing.KeyStroke stroke) {
        // Resolve InputMap → action key → ActionMap → Action. JDK returns
        // null when the stroke isn't bound OR when the ActionMap has no
        // entry for the key — we match both.
        if (actionMap == null) return null;
        for (int condition : new int[]{WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, WHEN_IN_FOCUSED_WINDOW}) {
            javax.swing.InputMap im = rawInputMap(condition);
            if (im == null) continue;
            Object key = im.get(stroke);
            if (key != null) {
                return actionMap.get(key);
            }
        }
        return null;
    }

    public void resetKeyboardActions() {
        // Clear every condition's map + uninstall every Vaadin shortcut.
        // Field-null each InputMap rather than calling .clear(): the map
        // might be shared with a parent (JDK allows InputMap.setParent),
        // in which case clearing mutates the parent too.
        if (installedShortcuts != null) {
            java.util.List<com.vaadin.flow.component.ShortcutRegistration> regs =
                    new java.util.ArrayList<>(installedShortcuts.values());
            withPeer(p -> regs.forEach(com.vaadin.flow.component.ShortcutRegistration::remove));
            installedShortcuts.clear();
        }
        if (focusedInputMap != null) focusedInputMap.clear();
        if (ancestorInputMap != null) ancestorInputMap.clear();
        if (windowInputMap != null) windowInputMap.clear();
        if (actionMap != null) actionMap.clear();
    }

    /**
     * Raw accessor (no lazy allocation) — used by query paths so calling
     * {@code getConditionForKeyStroke} on a fresh component doesn't
     * materialise three empty InputMaps.
     */
    private javax.swing.InputMap rawInputMap(int condition) {
        return switch (condition) {
            case WHEN_FOCUSED -> focusedInputMap;
            case WHEN_ANCESTOR_OF_FOCUSED_COMPONENT -> ancestorInputMap;
            case WHEN_IN_FOCUSED_WINDOW -> windowInputMap;
            default -> null;
        };
    }

    /**
     * Install a Vaadin {@code Shortcuts} registration that routes a
     * browser key press through {@link EHelper#callSwing} back to the
     * Action's {@code actionPerformed}. Scope per condition:
     *
     * <ul>
     *   <li>{@link #WHEN_IN_FOCUSED_WINDOW} — no {@code listenOn}, so
     *       Vaadin scopes at the UI (≈ window for our single-UI model).</li>
     *   <li>{@link #WHEN_FOCUSED} / {@link #WHEN_ANCESTOR_OF_FOCUSED_COMPONENT}
     *       — {@code listenOn(peer)} so the key only fires when focus is
     *       within this component's peer subtree.</li>
     * </ul>
     *
     * <p>Unmappable {@code KeyStroke}s (punctuation, numpad, …) log an
     * onUnimplemented and skip the browser-side install. The InputMap +
     * ActionMap entries still land so {@code getActionForKeyStroke}
     * returns the Action — server-driven code paths (programmatic key
     * lookup, tests) keep working even when the browser wire-up can't.
     */
    private void installVaadinShortcut(int condition, javax.swing.KeyStroke stroke,
                                       final ActionStandin action) {
        com.vaadin.swingbridge.surrogates.util.KeyConvert.VaadinKeyBinding binding = com.vaadin.swingbridge.surrogates.util.KeyConvert.toVaadinKeyBinding(stroke);
        if (binding == null) {
            vaadinx.EHelper.onUnimplemented("JComponent", "registerKeyboardAction/unmappable-keystroke", stroke);
            return;
        }
        final vaadinx.awt.Component source = this;
        // Vaadin's Shortcuts API takes a Command (SerializableRunnable),
        // not a plain Runnable — declare the type explicitly so the
        // lambda targets the correct functional interface.
        com.vaadin.flow.server.Command command = () -> vaadinx.EHelper.callSwing(() -> {
            java.awt.event.ActionEvent e = new java.awt.event.ActionEvent(
                    source,
                    java.awt.event.ActionEvent.ACTION_PERFORMED,
                    action.command());
            action.actionPerformed(e);
        });
        com.vaadin.flow.component.ShortcutRegistration[] registered = new com.vaadin.flow.component.ShortcutRegistration[1];
        withPeer(p -> {
            registered[0] = com.vaadin.flow.component.Shortcuts.addShortcutListener(
                    p, command, binding.key(), binding.modifiers());
            if (condition != WHEN_IN_FOCUSED_WINDOW) {
                // Scope to this component's subtree — key only fires when
                // focus is within the peer. Best-effort match to Swing's
                // WHEN_FOCUSED / WHEN_ANCESTOR_OF_FOCUSED_COMPONENT.
                registered[0].listenOn(p);
            }
        });
        com.vaadin.flow.component.ShortcutRegistration reg = registered[0];
        if (installedShortcuts == null) installedShortcuts = new java.util.LinkedHashMap<>();
        ShortcutKey key = new ShortcutKey(condition, stroke);
        com.vaadin.flow.component.ShortcutRegistration previous = installedShortcuts.put(key, reg);
        if (previous != null) withPeer(p -> previous.remove());
    }

    /** Remove the Vaadin shortcut for a specific (condition, stroke). */
    private void uninstallShortcut(int condition, javax.swing.KeyStroke stroke) {
        if (installedShortcuts == null) return;
        com.vaadin.flow.component.ShortcutRegistration reg =
                installedShortcuts.remove(new ShortcutKey(condition, stroke));
        if (reg != null) withPeer(p -> reg.remove());
    }

    /**
     * {@link javax.swing.Action} adapter that wraps a plain
     * {@link java.awt.event.ActionListener} plus the optional command
     * string passed to {@code registerKeyboardAction}. Single object
     * serves as InputMap value, ActionMap key, and ActionMap value —
     * matches JDK's {@code ActionStandin} pattern.
     */
    private static final class ActionStandin extends javax.swing.AbstractAction {
        private final java.awt.event.ActionListener listener;
        private final String command;

        ActionStandin(java.awt.event.ActionListener listener, String command) {
            this.listener = listener;
            this.command = command;
        }

        String command() {
            return command;
        }

        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            // JDK re-sources the event if the command differs. We pass
            // the event through — the caller above already built an
            // event with the correct source + command.
            listener.actionPerformed(e);
        }
    }

    public final void setInputMap(int condition, javax.swing.InputMap map) {
        // Replacing the InputMap tears down every Vaadin shortcut we'd
        // installed for strokes under this condition — the replacement
        // may not carry them forward, and stale shortcuts would fire on
        // keys the InputMap no longer binds.
        uninstallShortcutsForCondition(condition);
        switch (condition) {
            case WHEN_FOCUSED -> focusedInputMap = map;
            case WHEN_ANCESTOR_OF_FOCUSED_COMPONENT -> ancestorInputMap = map;
            case WHEN_IN_FOCUSED_WINDOW -> windowInputMap = map;
            default -> throw new IllegalArgumentException(
                    "condition must be one of WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, WHEN_IN_FOCUSED_WINDOW");
        }
    }

    public final void setActionMap(javax.swing.ActionMap map) {
        this.actionMap = map;
    }

    /**
     * Remove every Vaadin shortcut we installed for the given condition.
     * Used by {@link #setInputMap} when the replacement InputMap may not
     * carry the previous bindings. No-op when no shortcuts were ever
     * installed (common case).
     */
    private void uninstallShortcutsForCondition(int condition) {
        if (installedShortcuts == null) return;
        java.util.Iterator<java.util.Map.Entry<ShortcutKey, com.vaadin.flow.component.ShortcutRegistration>> it =
                installedShortcuts.entrySet().iterator();
        while (it.hasNext()) {
            java.util.Map.Entry<ShortcutKey, com.vaadin.flow.component.ShortcutRegistration> e = it.next();
            if (e.getKey().condition() == condition) {
                com.vaadin.flow.component.ShortcutRegistration reg = e.getValue();
                withPeer(p -> reg.remove());
                it.remove();
            }
        }
    }

    public int getBaseline(int arg0, int arg1) {
        // Swing contract: -1 means "no baseline info for this component".
        // We don't compute baselines (R_layouts_close_enough — no font metrics pipeline),
        // so -1 is the honest, contract-correct answer.
        return -1;
    }

    public void setVisible(boolean arg0) {
        // Component.setVisible toggles the peer's display state and fires
        // the AWT events (COMPONENT_SHOWN / HIDDEN). Window overrides it
        // for Dialog open/close semantics; neither is JComponent's concern.
        super.setVisible(arg0);
    }

    public void setEnabled(boolean arg0) {
        // The bound "enabled" PropertyChangeEvent belongs here, not on
        // Component: java.awt.Component.setEnabled fires nothing bound, and
        // JComponent.setEnabled is where the JDK adds the fire (D_property_fanout_audit). Swing
        // reads isEnabled() *before* delegating and fires unconditionally
        // afterwards, so a no-change call still reaches the listener list
        // (PropertyChangeSupport's own equality dedupe is what suppresses it)
        // and a peer that could not honour the request still reports honestly.
        // Swing's cursor flip + repaint on top: cursor is Component's job,
        // repaint is R_layouts_close_enough.
        //
        // The new value read back via isEnabled() rather than echoed from the
        // argument: identical to the JDK for every peer that can be disabled
        // (Component writes the field, so isEnabled() == arg0), and it keeps
        // the one peer that cannot — Component.setEnabled's onUnsupported
        // branch leaves the field at true on purpose — from announcing a
        // transition to a state its own getter denies. Equality dedupe then
        // suppresses the event, which is what the JDK does too whenever the
        // requested value already holds.
        boolean oldEnabled = isEnabled();
        super.setEnabled(arg0);
        firePropertyChange("enabled", oldEnabled, isEnabled());
    }

    public void setForeground(java.awt.Color arg0) {
        // Component.setForeground writes CSS color to the peer and fires
        // the foreground PropertyChangeEvent. Swing adds nothing observable
        // beyond a repaint (R_layouts_close_enough).
        super.setForeground(arg0);
    }

    public void setBackground(java.awt.Color arg0) {
        // Component.setBackground writes CSS background-color; Swing's
        // JComponent override would gate on isOpaque before painting, but
        // we don't paint (R_layouts_close_enough) so the color just lands regardless.
        super.setBackground(arg0);
    }

    /**
     * Stored on the current UI, which is {@link #getDefaultLocale}'s scope; the
     * JVM default is never touched, since it is the *server's* and shared by every
     * session. Two consequences of the narrower scope: an F5 lands on a fresh UI and
     * reads the browser's locale again (real Swing's {@code AppContext} would have
     * survived), and a call with no current UI has nowhere to store and WARNs.
     *
     * @param arg0 {@code null} resets to the browser's locale, as the JDK's {@code null}
     *             resets to the JVM default
     */
    public static void setDefaultLocale(java.util.Locale arg0) {
        com.vaadin.flow.component.UI ui = com.vaadin.flow.component.UI.getCurrent();
        if (ui == null) {
            vaadinx.EHelper.onUnimplemented("JComponent", "setDefaultLocale", arg0);
            return;
        }
        DefaultLocale holder = com.vaadin.flow.component.ComponentUtil.getData(ui, DefaultLocale.class);
        if (holder == null) {
            holder = new DefaultLocale();
            com.vaadin.flow.component.ComponentUtil.setData(ui, DefaultLocale.class, holder);
        }
        holder.value = arg0;
    }

    // processKeyEvent is NOT redeclared here. vaadinx.awt.Component declares
    // the real, vaadinx.awt.event.KeyEvent-typed one and runs the listener
    // fan-out; a second java.awt.event.KeyEvent-typed overload on this class
    // was a ghost no import-swapped code could ever call, and it shadowed
    // nothing — so a migrator's override of the swapped signature landed on
    // Component's method regardless. R_no_vaadin_in_api limb 1: the JDK's signature must
    // speak the JDK's *ported* types, and there is only one of it.

    protected void processComponentKeyEvent(vaadinx.awt.event.KeyEvent arg0) {
        // JComponent-only hook (no Component counterpart), so it is retyped
        // rather than dropped. Empty in the JDK too — a subclass hook. It
        // stays unreached here because the caller would be the JDK's key-
        // binding dispatch, which D_focus_managers puts permanently out (R_match_swing_errors (b)).
        vaadinx.EHelper.onNoop("JComponent", "processComponentKeyEvent");
    }

    protected boolean processKeyBinding(javax.swing.KeyStroke arg0, vaadinx.awt.event.KeyEvent arg1, int arg2, boolean arg3) {
        // Bucket B onNoop — see processComponentKeyEvent. KeyStroke stays the
        // JDK's: SB-Emulators ports no vaadinx.swing.KeyStroke, so R_no_vaadin_in_api limb 1 has
        // nothing to swap it for.
        vaadinx.EHelper.onNoop("JComponent", "processKeyBinding");
        return false;
    }

    public java.lang.String getToolTipText(vaadinx.awt.event.MouseEvent arg0) {
        // JDK's location-aware variant lets a component return different
        // tooltip text depending on the hover point (used by JTable /
        // JTree cell tooltips). Our peers handle tooltips themselves via
        // HasTooltip — the location parameter doesn't reach us. Return
        // the static tooltip so code that calls this path without a
        // location-aware override still sees something sensible.
        return getToolTipText();
    }

    public java.lang.String getToolTipText() {
        return (java.lang.String) getClientProperty(TOOL_TIP_TEXT_KEY);
    }

    public int getX() {
        // Component-level stub returning 0 (layout dispatch
        // model — we don't compute pixel positions). Chain is preparation.
        return super.getX();
    }

    public int getY() {
        return super.getY();
    }

    public void scrollRectToVisible(java.awt.Rectangle arg0) {
        // Bucket B onNoop — pixel-coordinate scrolling has no Vaadin
        // counterpart at this layer (R_layouts_close_enough: layout dispatch is best-effort,
        // pixel-accurate placement is out of scope, permanently —
        // D_pixel_layout_not_planned).
        vaadinx.EHelper.onNoop("JComponent", "scrollRectToVisible");
    }

    // processMouseEvent / processMouseMotionEvent are NOT redeclared here,
    // for the same reason as processKeyEvent above: vaadinx.awt.Component
    // owns the real vaadinx.awt.event.MouseEvent-typed pair and runs the
    // fan-out, and a java.awt.event.MouseEvent-typed twin here was a ghost.

    public void disable() {
        // Deprecated AWT 1.0 alias; Component's override already routes
        // to setEnabled(false).
        super.disable();
    }

    public void setAutoscrolls(boolean arg0) {
        // Drag-autoscroll itself has no Vaadin counterpart; the flag the JDK's
        // Autoscroller reads is ordinary state and stays (R_decline_effect_only).
        vaadinx.EHelper.onNoop("JComponent", "setAutoscrolls");
        autoscrolls = arg0;
    }

    public void setFocusTraversalKeys(int arg0, java.util.Set<? extends java.awt.AWTKeyStroke> arg1) {
        // Component.setFocusTraversalKeys WARNs: rebinding the traversal keys
        // means intercepting Tab, which the browser owns (D_focus_managers tier 3). Chain so
        // the WARN keeps naming one place.
        super.setFocusTraversalKeys(arg0, arg1);
    }

    public void reshape(int arg0, int arg1, int arg2, int arg3) {
        // Deprecated AWT 1.0 name for setBounds. Component stubs it;
        // chain is preparation.
        super.reshape(arg0, arg1, arg2, arg3);
    }

    public void computeVisibleRect(java.awt.Rectangle arg0) {
        // Bucket B onNoop — pixel-coordinate visibility has no Vaadin
        // counterpart at this layer (R_layouts_close_enough). getVisibleRect already returns
        // a sensible default.
        vaadinx.EHelper.onNoop("JComponent", "computeVisibleRect");
    }

    protected void fireVetoableChange(java.lang.String arg0, java.lang.Object arg1, java.lang.Object arg2) throws java.beans.PropertyVetoException {
        // JavaBean-spec server-side bookkeeping. The JDK
        // delegate handles equality short-circuit, multi-listener dispatch,
        // and PropertyVetoException rollback — listener throws aborts the
        // change and the delegate re-fires the event with old/new swapped
        // at every prior listener.
        vetoableChangeSupport().fireVetoableChange(arg0, arg1, arg2);
    }

    public synchronized void addVetoableChangeListener(java.beans.VetoableChangeListener arg0) {
        vetoableChangeSupport().addVetoableChangeListener(arg0);
    }

    public synchronized void removeVetoableChangeListener(java.beans.VetoableChangeListener arg0) {
        vetoableChangeSupport().removeVetoableChangeListener(arg0);
    }

    public synchronized java.beans.VetoableChangeListener[] getVetoableChangeListeners() {
        return vetoableChangeSupport().getVetoableChangeListeners();
    }

    // AncestorListener wired via this.addNotify / removeNotify (which
    // Component's ctor routes from the peer's attach / detach listeners).
    // Listener type retyped to vaadinx.swing.event.AncestorListener — the
    // JDK's javax.swing.event.AncestorEvent ctor takes java.awt.Container
    // arguments we can't satisfy (D_event_port_policy). Storage piggybacks on the
    // inherited listenerList so getListeners(AncestorListener.class) works
    // through Component.getListeners without a special case.
    public void addAncestorListener(vaadinx.swing.event.AncestorListener l) {
        if (l == null) return;
        listenerList.add(vaadinx.swing.event.AncestorListener.class, l);
    }

    public void removeAncestorListener(vaadinx.swing.event.AncestorListener l) {
        if (l == null) return;
        listenerList.remove(vaadinx.swing.event.AncestorListener.class, l);
    }

    public vaadinx.swing.event.AncestorListener[] getAncestorListeners() {
        return listenerList.getListeners(vaadinx.swing.event.AncestorListener.class);
    }

    /**
     * Fires an ANCESTOR_ADDED / ANCESTOR_REMOVED to currently-stored
     * {@link vaadinx.swing.event.AncestorListener}s. Short-circuits when
     * nobody's listening — same pattern as Component's fire* helpers.
     * ANCESTOR_MOVED is not fired (Vaadin has no server-side
     * layout-position event); same accepted incompleteness as the
     * surrogate-side wiring in {@code JComponentMixin.addAncestorListener}.
     */
    private void fireAncestorEvent(int id) {
        if (listenerList.getListenerCount(vaadinx.swing.event.AncestorListener.class) == 0) return;
        // ancestor = self for direct attach/detach (matches the
        // surrogate-side SAncestorEvent wiring); ancestorParent = current
        // parent. On detach, Container.remove sets parent=null *after*
        // peer.removeFromParent (which triggers our DetachListener), so
        // by the time this fires the field is still set to the old
        // parent — useful for listeners that need to know which container
        // they're leaving.
        vaadinx.swing.event.AncestorEvent e = new vaadinx.swing.event.AncestorEvent(
                this, id, this, getParent());
        for (vaadinx.swing.event.AncestorListener l :
                listenerList.getListeners(vaadinx.swing.event.AncestorListener.class)) {
            if (id == vaadinx.swing.event.AncestorEvent.ANCESTOR_ADDED) {
                l.ancestorAdded(e);
            } else if (id == vaadinx.swing.event.AncestorEvent.ANCESTOR_REMOVED) {
                l.ancestorRemoved(e);
            }
        }
    }

    public <T extends java.util.EventListener> T[] getListeners(java.lang.Class<T> arg0) {
        // Component.getListeners handles both the shared listener list and
        // the PropertyChangeListener special case (which lives outside AWT's
        // main storage). Swing's JComponent also folds AncestorListener /
        // VetoableChangeListener in: AncestorListener piggybacks on the
        // shared listenerList (see addAncestorListener) so the super walk
        // already finds them; VetoableChangeListener lives in its own
        // VetoableChangeSupport — not folded here yet,
        // matches Component's PropertyChangeListener treatment.
        return super.getListeners(arg0);
    }

    public void addNotify() {
        // Fired from the peer's AttachListener (wired in Component's
        // constructor). Swing's JComponent.addNotify also registers with
        // RepaintManager — we don't have one (R_layouts_close_enough), so super is sufficient
        // for the displayability transition. Fire ANCESTOR_ADDED alongside
        // so AncestorListeners see the same Vaadin attach event JDK
        // listeners would see on a Window-rooted hierarchy attach.
        super.addNotify();
        // The JDK fires *both* here: the AncestorEvent below is JComponent's
        // own listener family, and "ancestor" is a bound property alongside it
        // (D_owed_events). Note the JDK passes null as the old value and the *current*
        // parent as the new one, so a component attaching with no emulator
        // parent fires (null, null) — PropertyChangeSupport lets a both-null
        // pair through, and the JDK relies on that.
        firePropertyChange("ancestor", null, getParent());
        fireAncestorEvent(vaadinx.swing.event.AncestorEvent.ANCESTOR_ADDED);
    }

    public void removeNotify() {
        // Mirror of addNotify — fired from the peer's DetachListener.
        // Swing's JComponent.removeNotify unregisters from RepaintManager
        // and resets ancestor-input-maps; neither is modeled here (R_layouts_close_enough/R_infra_not_surface).
        // Fire ANCESTOR_REMOVED before super so the listener sees state
        // consistent with "still attached to the leaving ancestor" — and
        // so a listener that itself unregisters (typical for one-shot
        // setup-on-show / teardown-on-hide) still gets the event.
        fireAncestorEvent(vaadinx.swing.event.AncestorEvent.ANCESTOR_REMOVED);
        super.removeNotify();
        // After super, mirroring the JDK's placement — which its own source
        // comments as "not strictly correct" (the event ought to follow the
        // parent going null, and does not). Faithful to the JDK's order rather
        // than to what the JDK wishes it were (D_owed_events).
        firePropertyChange("ancestor", getParent(), null);
    }

    public void paintImmediately(int arg0, int arg1, int arg2, int arg3) {
        // Bucket B onNoop — paint pipeline is permanent sub-bucket (b).
        vaadinx.EHelper.onNoop("JComponent", "paintImmediately");
    }

    public void paintImmediately(java.awt.Rectangle arg0) {
        // Bucket B onNoop — see paintImmediately(int,int,int,int).
        vaadinx.EHelper.onNoop("JComponent", "paintImmediately");
    }

    protected boolean isPaintingOrigin() {
        // Swing default is false. Paint isn't modeled (R_layouts_close_enough); this value is
        // only consulted during a paint dispatch we never run.
        return false;
    }

    public java.lang.String getUIClassID() {
        // Bucket B onNoop — L&F dispatch is permanent sub-bucket (b)
        // (CLAUDE.md §"Current scope": Look-and-Feel handled in a later
        // Vaadin+CSS pass, outside this project). Subclasses (JLabel,
        // JCheckBox, etc.) override this to return their canonical UI key
        // for UIManager
        // parity; this base override applies when no subclass cares.
        vaadinx.EHelper.onNoop("JComponent", "getUIClassID");
        return null;
    }

    public void hide() {
        // Deprecated AWT 1.0 alias for setVisible(false); Component has
        // the real impl.
        super.hide();
    }

    /**
     * Stores the flag and fires {@code "inheritsPopupMenu"}; the inheritance
     * itself is not modelled — a Vaadin {@code ContextMenu} binds to one target
     * element, and walking to an ancestor's menu on a bare right-click has no
     * counterpart. State and notification are owed regardless (R_decline_effect_only, D_owed_events): the
     * flag was previously dropped, so {@code getInheritsPopupMenu} contradicted
     * the setter and no listener ever fired.
     */
    public void setInheritsPopupMenu(boolean arg0) {
        boolean old = this.inheritsPopupMenu;
        this.inheritsPopupMenu = arg0;
        vaadinx.EHelper.onNoop("JComponent", "setInheritsPopupMenu");
        firePropertyChange("inheritsPopupMenu", old, arg0);
    }

    public void setComponentPopupMenu(vaadinx.swing.JPopupMenu popup) {
        // D_jpopupmenu: ported to the emulator type. Round-trip the field, then drive
        // the binding by delegating through the surrogate peer's Swing-
        // flavoured helper (SD_sjpopupmenu), which calls ContextMenu.setTarget(peer).
        // The setTarget binding thus lives in exactly one place across both
        // layers. Every emulator peer is a JComponentMixin surrogate; the
        // popup's peer is R_leaf_peer_lockdown-locked to SJPopupMenu.
        vaadinx.swing.JPopupMenu old = this.componentPopup;
        this.componentPopup = popup;
        withPeer(p -> {
            if (p instanceof com.vaadin.swingbridge.surrogates.swing.JComponentMixin m) {
                m.setComponentPopupMenu(popup == null ? null
                        : (com.vaadin.swingbridge.surrogates.SJPopupMenu) popup.getPeer());
            }
        });
        // The JDK fires unconditionally, without an equality guard (D_owed_events).
        firePropertyChange("componentPopupMenu", old, popup);
    }

    public void updateUI() {
        // Bucket B onNoop — L&F dispatch, see getUIClassID.
        vaadinx.EHelper.onNoop("JComponent", "updateUI");
    }

    public javax.swing.plaf.ComponentUI getUI() {
        // Bucket B onNoop — L&F dispatch, see getUIClassID.
        vaadinx.EHelper.onNoop("JComponent", "getUI");
        return null;
    }

    protected void setUI(javax.swing.plaf.ComponentUI arg0) {
        // Bucket B onNoop — L&F dispatch, see getUIClassID.
        vaadinx.EHelper.onNoop("JComponent", "setUI");
    }

    public boolean isPaintingTile() {
        // Swing default is false — true only during a specific repaint
        // optimization we don't run (R_layouts_close_enough). Silent honest-default.
        return false;
    }

    public final boolean isPaintingForPrint() {
        // Same story as isPaintingTile — paint flag we never set.
        return false;
    }

    public void setRequestFocusEnabled(boolean arg0) {
        // The effect is the L&F's: BasicButtonListener and friends consult the flag
        // on a mouse press, and L&F dispatch is out of scope (sub-bucket (b)), so
        // requestFocus() here honours no veto. The flag itself is state and stays.
        vaadinx.EHelper.onNoop("JComponent", "setRequestFocusEnabled");
        requestFocusEnabled = arg0;
    }

    public boolean isRequestFocusEnabled() {
        return requestFocusEnabled;
    }

    public void grabFocus() {
        // JDK's grabFocus is "requestFocus without the FocusTraversalPolicy
        // check" — traversal policy is a pluggable object we don't model
        // (D_focus_managers tier 3), so requestFocus's peer-delegation is functionally
        // identical. Same route.
        requestFocus();
    }

    /**
     * Stores the flag and fires {@code "verifyInputWhenFocusTarget"}; the gate
     * it controls is not modelled. {@link #setInputVerifier} itself <em>is</em>
     * wired (BlurNotifier-driven), but the JDK applies this flag during focus
     * <em>traversal</em> — asking the component losing focus to verify before
     * the target accepts it — and SB-Emulators has no traversal pipeline to gate (D_focus_managers).
     * State and notification are owed regardless (R_decline_effect_only, D_owed_events).
     */
    public void setVerifyInputWhenFocusTarget(boolean arg0) {
        boolean old = this.verifyInputWhenFocusTarget;
        this.verifyInputWhenFocusTarget = arg0;
        vaadinx.EHelper.onNoop("JComponent", "setVerifyInputWhenFocusTarget");
        firePropertyChange("verifyInputWhenFocusTarget", old, arg0);
    }

    /**
     * @return what {@link #setVerifyInputWhenFocusTarget} stored; Swing's
     *     default is {@code true}
     */
    public boolean getVerifyInputWhenFocusTarget() {
        return verifyInputWhenFocusTarget;
    }

    public void setBorder(vaadinx.swing.border.Border newBorder) {
        // AbstractBorder subclasses carry their own CSS via
        // applyCss; custom user borders that extend Border directly don't
        // render (R_best_effort_behaviour best-effort) but still round-trip through
        // getBorder and contribute their insets to getInsets. Matches
        // the JDK shape of storing the field and firing the "border" PCE.
        vaadinx.swing.border.Border old = this.border;
        if (java.util.Objects.equals(old, newBorder)) return;
        this.border = newBorder;
        if (newBorder instanceof vaadinx.swing.border.AbstractBorder ab) {
            withPeer(p -> ab.applyCss(p.getElement()));
        } else {
            // Null or custom non-AbstractBorder: strip any previously-
            // written CSS so the old border doesn't linger. A custom
            // Border's visual rendering is a deferred gap (no applyCss
            // extension point exposed publicly yet); log once so
            // migrations with custom borders surface the drop.
            withPeer(p -> vaadinx.swing.border.AbstractBorder.clearBorderCss(p.getElement()));
            if (newBorder != null) {
                vaadinx.EHelper.onUnimplemented("JComponent", "setBorder/custom-Border-impl", newBorder);
            }
        }
        firePropertyChange("border", old, newBorder);
    }

    /**
     * @param arg0 clamped into {@code [0, 1]}, as the JDK's private
     *             {@code validateAlignment} does — {@code 2.0f} reads back as {@code 1.0f}
     */
    public void setAlignmentY(float arg0) {
        // The paint-time effect is what drops (R_layouts_close_enough): a browser lays
        // out from CSS, so nothing reads this back but the migrator's own code.
        vaadinx.EHelper.onNoop("JComponent", "setAlignmentY");
        alignmentY = validateAlignment(arg0);
        alignmentYSet = true;
    }

    /** @param arg0 clamped into {@code [0, 1]} — see {@link #setAlignmentY}. */
    public void setAlignmentX(float arg0) {
        vaadinx.EHelper.onNoop("JComponent", "setAlignmentX");
        alignmentX = validateAlignment(arg0);
        alignmentXSet = true;
    }

    private static float validateAlignment(float alignment) {
        return alignment > 1.0f ? 1.0f : alignment < 0.0f ? 0.0f : alignment;
    }

    public void setInputVerifier(vaadinx.swing.InputVerifier newVerifier) {
        // Wires through the peer's blur listener when the peer is a
        // BlurNotifier (most input peers — TextField, Button, Checkbox,
        // … — are). When focus would leave, shouldYieldFocus(this)
        // decides; false restores focus via peer.focus(). Previous
        // listener is uninstalled on replace so swapping verifiers
        // doesn't stack dispatches.
        vaadinx.swing.InputVerifier old = this.inputVerifier;
        if (old == newVerifier) return;
        if (blurListenerRegistration != null) {
            com.vaadin.flow.shared.Registration stale = blurListenerRegistration;
            withPeer(p -> stale.remove());
            blurListenerRegistration = null;
        }
        this.inputVerifier = newVerifier;
        if (newVerifier != null && getPeer() instanceof com.vaadin.flow.component.BlurNotifier<?> bn) {
            com.vaadin.flow.shared.Registration[] registered = new com.vaadin.flow.shared.Registration[1];
            withPeer(p -> registered[0] = bn.addBlurListener(e ->
                    vaadinx.EHelper.callSwing(() -> {
                        // verify/shouldYieldFocus reads the component's
                        // state; false means the value is invalid and we
                        // restore focus. peer.focus() queues the refocus
                        // for the next browser round-trip.
                        if (!newVerifier.shouldYieldFocus(this)
                                && getPeer() instanceof com.vaadin.flow.component.Focusable<?> f) {
                            f.focus();
                        }
                    })));
            blurListenerRegistration = registered[0];
        }
        firePropertyChange("inputVerifier", old, newVerifier);
    }

    public vaadinx.swing.InputVerifier getInputVerifier() {
        return inputVerifier;
    }

    /**
     * @param arg0 a positive bitmask stores; {@code 0} is <em>ignored</em> and a
     *             negative value clears — {@code DebugGraphicsInfo.setDebugOptions}'
     *             three branches, measured on JDK 25, where {@code NONE_OPTION} (0)
     *             leaves the previous options standing rather than switching debugging off
     */
    public void setDebugGraphicsOptions(int arg0) {
        // The debug-paint pipeline it drives has no Vaadin counterpart — we run no
        // paint, so there is nothing to overlay (R_layouts_close_enough).
        vaadinx.EHelper.onNoop("JComponent", "setDebugGraphicsOptions");
        if (arg0 > 0) {
            debugGraphicsOptions = arg0;
        } else if (arg0 < 0) {
            debugGraphicsOptions = 0;
        }
    }

    public int getDebugGraphicsOptions() {
        return debugGraphicsOptions;
    }

    public boolean requestDefaultFocus() {
        vaadinx.EHelper.onUnimplemented("JComponent", "requestDefaultFocus");
        return false;
    }

    public void setToolTipText(java.lang.String text) {
        // Swing stores the field and fires a "ToolTipText" PCE. We also
        // drive the peer via com.vaadin.flow.component.shared.HasTooltip
        // when the peer supports it (Button, TextField, Checkbox,
        // PasswordField, TextArea, … — the common input surface). Peers
        // that don't implement HasTooltip still round-trip the field so
        // getToolTipText reports what user code set; the tooltip just
        // doesn't render in the browser. No WARN: a tooltip on an
        // unsupported peer is a close-enough R_best_effort_behaviour fallback, not an
        // unimplemented stub.
        if (getPeer() instanceof com.vaadin.flow.component.shared.HasTooltip ht) {
            withPeer(p -> ht.setTooltipText(text));
        }
        // The text lives in the client-property table, where the JDK puts it,
        // and putClientProperty is what fires "ToolTipText" — no separate
        // field and no separate fire. Routing rather than duplicating is
        // R_no_vaadin_in_api limb 2: a migrator reading getClientProperty(TOOL_TIP_TEXT_KEY)
        // sees the tooltip, as on the desktop.
        putClientProperty(TOOL_TIP_TEXT_KEY, text);
    }

    public java.awt.Point getToolTipLocation(vaadinx.awt.event.MouseEvent arg0) {
        // Bucket B onNoop — pixel-coordinate tooltip placement has no Vaadin
        // counterpart at this layer (R_layouts_close_enough). JDK default is null ("use the
        // standard location"), which is
        // exactly what Vaadin's HasTooltip does.
        vaadinx.EHelper.onNoop("JComponent", "getToolTipLocation");
        return null;
    }

    public java.awt.Point getPopupLocation(vaadinx.awt.event.MouseEvent arg0) {
        vaadinx.EHelper.onUnimplemented("JComponent", "getPopupLocation", arg0);
        return null;
    }

    public javax.swing.JToolTip createToolTip() {
        vaadinx.EHelper.onUnimplemented("JComponent", "createToolTip");
        return null;
    }

    public boolean getAutoscrolls() {
        return autoscrolls;
    }

    /** Installed transfer handler, or null until {@link #setTransferHandler} lands one (D_drag_and_drop). */
    private vaadinx.swing.TransferHandler transferHandler;

    public void setTransferHandler(vaadinx.swing.TransferHandler newHandler) {
        // D_drag_and_drop: ported from the javax.swing.TransferHandler stub to the emulator
        // type (D_whitelist_porting — the handler references vaadinx.swing.JComponent). Storing
        // the handler then asking DndBridge to (re)wire the peer is the single
        // entry point both the handler change and the JList/JTable
        // dragEnabled / dropMode changes funnel through.
        vaadinx.swing.TransferHandler old = this.transferHandler;
        this.transferHandler = newHandler;
        vaadinx.swing.DndBridge.reconfigure(this);
        firePropertyChange("transferHandler", old, newHandler);
    }

    public vaadinx.swing.TransferHandler getTransferHandler() {
        return transferHandler;
    }

    public java.awt.Rectangle getVisibleRect() {
        vaadinx.EHelper.onUnimplemented("JComponent", "getVisibleRect");
        return null;
    }

    public vaadinx.awt.Container getTopLevelAncestor() {
        // Swing walks up getParent() until it finds a Window (or a non-
        // Container root). Our Window extends Container, so the instanceof
        // check doubles as the stop condition. Null if the component
        // isn't attached to a Window yet — matches Swing's contract.
        for (vaadinx.awt.Container p = getParent(); p != null; p = p.getParent()) {
            if (p instanceof vaadinx.awt.Window) return p;
        }
        return null;
    }

    public boolean isValidateRoot() {
        // Container.isValidateRoot returns false by default; Window flips
        // to true. That matches Swing's JComponent default (false — only
        // specific subclasses like JRootPane and JScrollPane override to
        // true). Chain up so any future refinements land in one place.
        return super.isValidateRoot();
    }

    public void setDoubleBuffered(boolean arg0) {
        // We don't paint (R_layouts_close_enough), so there is no backing store to
        // install — but the flag is what the JDK's own getter answers, and JPanel /
        // JRootPane turn it on from their constructors, so it has to be stored.
        vaadinx.EHelper.onNoop("JComponent", "setDoubleBuffered");
        doubleBuffered = arg0;
    }

}
