/*
 * Copyright (c) 2000, 2023, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JFormattedTextField
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JFormattedTextField,
// hand-finished for the D_jformattedtextfield strategy-dispatch design.
//
// Public ctors funnel through the pickStrategy* helpers, which return a
// FormattedFieldStrategy chosen from the formatter's (or value's) family:
//   - DateStrategy for DateFormatter / InternationalFormatter wrapping
//     DateFormat (peer = SJFormattedDatePicker);
//   - IntegerStrategy / LongStrategy / NumberStrategy for the numeric
//     formatters (peers = SJFormatted{Integer,Long,Number}Field);
//   - MaskStrategy for MaskFormatter (peer = SJFormattedTextField +
//     browser pattern attr);
//   - DefaultFormattedStrategy as the catch-all (peer = SJFormattedTextField)
//     for everything else.
// Strategy is pinned for the instance's lifetime; same-family setFormatter
// swap re-runs formatter logic in-place, cross-family swap WARNs and keeps
// the original strategy per D_formatter_swap_rules.
//
// See emulators/decisions.md §D_jformattedtextfield for the strategy table + swap rules,
// surrogates/decisions.md §SD_sjformatted_family for the SJFormatted* family.

/** Emulator for {@link javax.swing.JFormattedTextField}. */
public class JFormattedTextField extends vaadinx.swing.JTextField {

    /** Commit policy on focus loss. JDK enum reused from JFormattedTextField. */
    public static final int COMMIT           = javax.swing.JFormattedTextField.COMMIT;
    public static final int COMMIT_OR_REVERT = javax.swing.JFormattedTextField.COMMIT_OR_REVERT;
    public static final int REVERT           = javax.swing.JFormattedTextField.REVERT;
    public static final int PERSIST          = javax.swing.JFormattedTextField.PERSIST;

    /**
     * Pinned at ctor time per D_formatted_peer_family. {@link DateStrategy#INSTANCE} for date
     * formatters; {@link DefaultFormattedStrategy#INSTANCE} for everything
     * else. Drives every peer-side write (initial value, programmatic
     * setValue, formatter swap re-run) through the strategy's hooks.
     */
    private final FormattedFieldStrategy strategy;

    // Object value source-of-truth on the emulator side. Per R_swing_is_truth the
    // field shadow drives the JDK contract (getValue returns this);
    // showValue propagates it to the Document and the peer. Peer-originated
    // value changes route through the strategy's install bridge back to
    // setValue, which equality-short-circuits to close the round-trip.
    private java.lang.Object value;

    // Currently installed formatter, or null. Fired in PCE("textFormatter")
    // on swap. The strategy's documentText routes formatter.valueToString,
    // falling back to Object.toString when no formatter is installed.
    private javax.swing.JFormattedTextField.AbstractFormatter formatter;

    // Currently installed factory, or null. setFormatterFactory pulls its
    // formatter and installs via setFormatter, which applies D_formatter_swap_rules's
    // same-family-swap rule.
    private javax.swing.JFormattedTextField.AbstractFormatterFactory formatterFactory;

    // JDK default per the JFormattedTextField javadoc.
    private int focusLostBehavior = COMMIT_OR_REVERT;

    public JFormattedTextField() {
        this(DefaultFormattedStrategy.INSTANCE);
    }

    public JFormattedTextField(java.lang.Object value) {
        this(pickStrategyForValue(value));
        if (value != null) {
            setValue(value);
        }
    }

    public JFormattedTextField(java.text.Format format) {
        this(format == null
                ? DefaultFormattedStrategy.INSTANCE
                : pickStrategyForFormatter(new javax.swing.text.InternationalFormatter(format)));
        if (format != null) {
            setFormatter(new javax.swing.text.InternationalFormatter(format));
        }
    }

    public JFormattedTextField(javax.swing.JFormattedTextField.AbstractFormatter formatter) {
        this(pickStrategyForFormatter(formatter));
        if (formatter != null) {
            setFormatter(formatter);
        }
    }

    public JFormattedTextField(javax.swing.JFormattedTextField.AbstractFormatterFactory factory) {
        this(pickStrategyForFactory(factory, null));
        if (factory != null) {
            setFormatterFactory(factory);
        }
    }

    public JFormattedTextField(javax.swing.JFormattedTextField.AbstractFormatterFactory factory,
                               java.lang.Object value) {
        this(pickStrategyForFactory(factory, value));
        if (factory != null) {
            setFormatterFactory(factory);
        }
        if (value != null) {
            setValue(value);
        }
    }

    /**
     * The single ctor that actually selects the peer. Package-private (not
     * private) so the static-helper-driven public ctors above can chain
     * through it; not exposed to user code, so D_framework_peer_selection's "framework picks the
     * peer; user code can't influence" invariant per D_formatter_is_framework_config holds — the
     * formatter argument is the framework-level signal, declarative-type-
     * info shaped.
     *
     * <p>R_leaf_peer_lockdown lock-down: per
     * <a href="../../../../emulators/decisions.md#D_jformattedtextfield_lockdown">D_jformattedtextfield_lockdown</a>,
     * with the swap-rule shape now settled (D_formatter_swap_rules),
     * R_leaf_peer_lockdown lock-down applies: no protected {@code (Component peer)} ctor,
     * no escape hatch for user subclasses to swap the peer. The class
     * stays non-final per R_leaf_peer_lockdown — user-code subclasses for behavior
     * (custom commitEdit, fireActionPerformed override, custom focus
     * handling) inherit the strategy-dispatched peer and work fine.
     */
    JFormattedTextField(FormattedFieldStrategy strategy) {
        super(peerTypeOf(strategy), strategy::createPeer);
        this.strategy = strategy;
        withPeer(p -> {
            strategy.install(this, p);
            installFocusLostCommit(p);
        });
    }

    /** The strategy's peer type, widened to what its {@code createPeer} is declared to return. */
    @SuppressWarnings("unchecked")
    private static Class<com.vaadin.flow.component.Component> peerTypeOf(FormattedFieldStrategy strategy) {
        return (Class<com.vaadin.flow.component.Component>) strategy.peerType();
    }

    /**
     * Wire the peer's blur to the JDK focus-lost commit contract. Real
     * Swing runs {@link #commitEdit()} (or a revert) when focus leaves the
     * field, honoring {@link #getFocusLostBehavior()} — that commit is what
     * refreshes {@link #getValue()} and reformats the display, and (because
     * the commit re-pushes the formatted text through the R_swing_is_truth Document sync)
     * fires the {@code DocumentListener}s downstream code hangs recompute
     * logic on. Without it only Enter (via {@link #fireActionPerformed})
     * committed, so a typed-then-tabbed edit left the value stale.
     *
     * <p>Every {@code SJFormatted*} peer is a Vaadin input control and thus
     * a {@link com.vaadin.flow.component.BlurNotifier}; the listener funnels
     * through {@link vaadinx.EHelper#callSwing} per R_callswing_envelope. This is the peer-side
     * trigger for the same policy {@link #processFocusEvent} applies when an
     * AWT {@code FOCUS_LOST} is dispatched programmatically.
     */
    private void installFocusLostCommit(com.vaadin.flow.component.Component peer) {
        if (peer instanceof com.vaadin.flow.component.BlurNotifier<?> bn) {
            bn.addBlurListener(e -> vaadinx.EHelper.callSwing(this::applyFocusLostBehavior));
        }
    }

    /**
     * Apply {@link #getFocusLostBehavior()} as JDK JFormattedTextField does
     * on focus loss: COMMIT / COMMIT_OR_REVERT try {@link #commitEdit()};
     * COMMIT_OR_REVERT and REVERT reformat the display back to the last
     * valid value on a parse failure; PERSIST leaves the typed text as-is.
     * The happy path (valid text) mirrors the Enter commit exactly.
     */
    private void applyFocusLostBehavior() {
        switch (focusLostBehavior) {
            case COMMIT, COMMIT_OR_REVERT -> {
                try {
                    commitEdit();
                } catch (java.text.ParseException e) {
                    invalidEdit();
                    if (focusLostBehavior == COMMIT_OR_REVERT) {
                        reformatToValue();
                    }
                    // COMMIT: leave the invalid text so the user can fix it.
                }
            }
            case REVERT -> reformatToValue();
            case PERSIST -> { /* keep the typed text; don't touch the value */ }
        }
    }

    /**
     * Re-push the current value through the strategy so the peer's displayed
     * text normalizes to {@code formatter.valueToString(value)}. Bypasses
     * {@link #setValue}'s equality short-circuit — the value may be unchanged
     * while the displayed text still holds a rejected edit that must revert.
     */
    private void reformatToValue() {
        showValue(value);
    }

    /**
     * Shows {@code v}: the strategy's text reaches the Document Swing-side, as the JDK
     * formatter's {@code install} sets it, and the Document sync renders it; then the
     * strategy's peer-only push. Skipped when the Document already holds the text, which
     * fires no {@code DocumentEvent}.
     */
    private void showValue(java.lang.Object v) {
        java.lang.String text = strategy.documentText(this, v);
        if (text != null && !text.equals(getText())) {
            setText(text);
        }
        withPeer(p -> strategy.afterSetValue(this, p, v));
    }

    // --- Strategy resolution (D_formatted_strategy_interface) --------------------------------------

    /** Pick from a value's runtime type per the JDK's typical mapping. */
    private static FormattedFieldStrategy pickStrategyForValue(Object value) {
        if (value instanceof java.util.Date || value instanceof java.util.Calendar) {
            return DateStrategy.INSTANCE;
        }
        if (value instanceof Integer) {
            return IntegerStrategy.INSTANCE;
        }
        if (value instanceof Long) {
            return LongStrategy.INSTANCE;
        }
        if (value instanceof Number) {
            return NumberStrategy.INSTANCE;
        }
        return DefaultFormattedStrategy.INSTANCE;
    }

    /** Pick from a formatter — D_formatted_strategy_interface step 1–4. */
    private static FormattedFieldStrategy pickStrategyForFormatter(
            javax.swing.JFormattedTextField.AbstractFormatter formatter) {
        if (DateStrategy.INSTANCE.accepts(formatter)) {
            return DateStrategy.INSTANCE;
        }
        if (IntegerStrategy.INSTANCE.accepts(formatter)) {
            return IntegerStrategy.INSTANCE;
        }
        if (LongStrategy.INSTANCE.accepts(formatter)) {
            return LongStrategy.INSTANCE;
        }
        if (NumberStrategy.INSTANCE.accepts(formatter)) {
            return NumberStrategy.INSTANCE;
        }
        if (MaskStrategy.INSTANCE.accepts(formatter)) {
            return MaskStrategy.INSTANCE;
        }
        return DefaultFormattedStrategy.INSTANCE;
    }

    /**
     * Pick from a factory + optional initial value: the factory's default
     * formatter (or the formatter chosen for the value) drives the pick.
     * Cross-family factories are partially constrained by D_formatter_swap_rules's swap rule.
     */
    private static FormattedFieldStrategy pickStrategyForFactory(
            javax.swing.JFormattedTextField.AbstractFormatterFactory factory,
            Object initialValue) {
        if (factory == null) {
            return pickStrategyForValue(initialValue);
        }
        // The factory's getFormatter(JFormattedTextField) needs an actual
        // field instance, which we don't have yet (we're picking the
        // strategy that builds it). Best-effort: dispatch off the value
        // type for now; the factory's chosen formatter installs after
        // construction via setFormatterFactory. Mismatched-family factory
        // leaves the strategy mismatched and the swap rule WARNs
        // on the eventual formatter swap.
        return pickStrategyForValue(initialValue);
    }

    // --- Object value (R_swing_is_truth source of truth) ------------------------------

    public java.lang.Object getValue() {
        return value;
    }

    public void setValue(java.lang.Object value) {
        java.lang.Object old = this.value;
        if (old == null ? value == null : old.equals(value)) return;
        this.value = value;
        firePropertyChange("value", old, value);
        showValue(value);
    }

    // --- Formatter / formatterFactory -----------------------------------

    public javax.swing.JFormattedTextField.AbstractFormatter getFormatter() {
        return formatter;
    }

    /**
     * Per D_formatter_swap_rules: a same-family swap re-runs the formatter in-place — the current
     * value is re-pushed through the strategy, refreshing the displayed text via
     * {@code formatter.valueToString}. A cross-family swap WARNs and keeps the
     * original strategy: the formatter is stored so {@code getFormatter}
     * round-trips, but the pinned peer keeps rendering under its original family
     * (D_formatter_is_framework_config peer pinning).
     */
    protected void setFormatter(javax.swing.JFormattedTextField.AbstractFormatter formatter) {
        javax.swing.JFormattedTextField.AbstractFormatter old = this.formatter;
        if (old == formatter) return;
        this.formatter = formatter;
        if (formatter != null && !strategy.accepts(formatter)) {
            // Cross-family swap — D_formatter_swap_rules (c). Strategy stays put; the
            // formatter is stored so getFormatter round-trips, but the
            // peer continues to render under the original strategy's
            // family.
            vaadinx.EHelper.onUnimplemented("JFormattedTextField",
                    "setFormatter cross-family swap (D_formatter_swap_rules (c)) — strategy="
                            + strategy.getClass().getSimpleName(), formatter);
        }
        firePropertyChange("textFormatter", old, formatter);
        // Same-family swap: re-run by showing the current value again, which
        // refreshes the displayed text via formatter.valueToString.
        if (formatter != null && strategy.accepts(formatter) && value != null) {
            showValue(value);
        }
    }

    public javax.swing.JFormattedTextField.AbstractFormatterFactory getFormatterFactory() {
        return formatterFactory;
    }

    public void setFormatterFactory(javax.swing.JFormattedTextField.AbstractFormatterFactory factory) {
        javax.swing.JFormattedTextField.AbstractFormatterFactory old = this.formatterFactory;
        if (old == factory) return;
        this.formatterFactory = factory;
        firePropertyChange("formatterFactory", old, factory);
        // Pull the factory's current display formatter and install via
        // setFormatter — which applies D_formatter_swap_rules's same-family-vs-cross-family
        // rule. JDK calls factory.getFormatter(this), but the API expects
        // javax.swing.JFormattedTextField; we work around by reaching
        // directly into DefaultFormatterFactory's display-formatter
        // accessor (the dominant case in real-world code), and falling
        // back to factory.getFormatter(null) for custom factories that
        // tolerate null source.
        //
        // Focus-state-driven swap (display vs edit formatter) is NOT
        // wired here — most app code installs a single display formatter
        // via the factory and doesn't ever switch to an edit formatter.
        // Revisit if a migration target depends on the swap.
        javax.swing.JFormattedTextField.AbstractFormatter pulled =
                pullCurrentFormatterFromFactory(factory);
        if (pulled != null) {
            setFormatter(pulled);
        }
    }

    private static javax.swing.JFormattedTextField.AbstractFormatter
            pullCurrentFormatterFromFactory(
                    javax.swing.JFormattedTextField.AbstractFormatterFactory factory) {
        if (factory == null) return null;
        if (factory instanceof javax.swing.text.DefaultFormatterFactory dff) {
            // Prefer display formatter (the no-focus state); fall back to
            // default, then edit. Mirrors DefaultFormatterFactory.getFormatter
            // when value != null and hasFocus == false.
            javax.swing.JFormattedTextField.AbstractFormatter f = dff.getDisplayFormatter();
            if (f == null) f = dff.getDefaultFormatter();
            if (f == null) f = dff.getEditFormatter();
            return f;
        }
        // Custom factory — call getFormatter(null) and accept whatever
        // result. Factories that dereference the source NPE here; we
        // catch and degrade to no formatter installation.
        try {
            return factory.getFormatter(null);
        } catch (NullPointerException e) {
            vaadinx.EHelper.onUnimplemented("JFormattedTextField",
                    "setFormatterFactory custom factory NPE on null source", factory);
            return null;
        }
    }

    // --- focusLostBehavior round-trip -----------------------------------

    public int getFocusLostBehavior() {
        return focusLostBehavior;
    }

    public void setFocusLostBehavior(int behavior) {
        if (behavior != COMMIT && behavior != COMMIT_OR_REVERT
                && behavior != REVERT && behavior != PERSIST) {
            throw new IllegalArgumentException(
                    "setFocusLostBehavior must be one of: JFormattedTextField.COMMIT, "
                            + "COMMIT_OR_REVERT, PERSIST or REVERT");
        }
        // No PropertyChangeEvent: JFormattedTextField.setFocusLostBehavior
        // validates the argument, assigns, and returns (D_property_fanout_audit).
        this.focusLostBehavior = behavior;
    }

    // --- commitEdit / isEditValid / invalidEdit -------------------------

    public void commitEdit() throws java.text.ParseException {
        // Per JDK: parse the current displayed text via formatter.stringToValue
        // and store the result via setValue. With no formatter installed
        // (or a formatter that doesn't apply per the strategy's accept
        // check), the displayed text IS the value.
        if (formatter != null) {
            Object parsed = formatter.stringToValue(getText());
            setValue(parsed);
        } else {
            setValue(getText());
        }
    }

    public boolean isEditValid() {
        // Returns whether the displayed text parses through the formatter
        // without ParseException. With no formatter, every text is "valid"
        // (degenerate case — the field is just a JTextField with an Object
        // value field). DateStrategy fields override this implicitly:
        // DatePicker rejects invalid dates client-side, so getText is
        // always parseable.
        if (formatter == null) return true;
        try {
            formatter.stringToValue(getText());
            return true;
        } catch (java.text.ParseException e) {
            return false;
        }
    }

    protected void invalidEdit() {
        // JDK fires UIManager.getLookAndFeel().provideErrorFeedback. We
        // have no L&F; silent no-op matches the audit's Bucket B stance.
    }

    @Override
    protected void fireActionPerformed() {
        // JDK JFormattedTextField: Enter triggers a commitEdit before
        // dispatching ActionEvent to user listeners. ParseException
        // means the typed text doesn't match the formatter — fire
        // invalidEdit and skip the ActionEvent dispatch (matches the
        // intent of D_formatter_swap_rules-shape "stay in invalid state until user fixes").
        try {
            commitEdit();
        } catch (java.text.ParseException e) {
            invalidEdit();
            return;
        }
        super.fireActionPerformed();
    }

    @Override
    public javax.swing.Action[] getActions() {
        // JDK returns the JFormattedTextField-specific actions
        // (commit-action, cancel-edit). We don't expose action-map editor
        // kit actions; empty array keeps callers that iterate from NPE.
        return new javax.swing.Action[0];
    }

    @Override
    public void setDocument(javax.swing.text.Document doc) {
        // JDK JFormattedTextField.setDocument re-installs the document
        // filter that the formatter wires for input rejection. We delegate
        // to the parent (just swap the document); reinstalling the filter
        // when the formatter is non-null is not wired (WARNs below).
        super.setDocument(doc);
        if (formatter != null) {
            vaadinx.EHelper.onUnimplemented("JFormattedTextField",
                    "setDocument with active formatter (DocumentFilter reinstall outstanding)", doc);
        }
    }

    @Override
    public java.lang.String getUIClassID() {
        return "FormattedTextFieldUI";
    }

    @Override
    protected void processInputMethodEvent(vaadinx.awt.event.InputMethodEvent e) {
        // L&F-driven IME path; out of scope per R_match_swing_errors sub-bucket (b).
        vaadinx.EHelper.onUnimplemented("JFormattedTextField", "processInputMethodEvent", e);
    }

    @Override
    protected void processFocusEvent(vaadinx.awt.event.FocusEvent e) {
        super.processFocusEvent(e);
        // Focus-lost consults focusLostBehavior and runs commitEdit / revert
        // / persist. The live browser trigger is the peer blur listener wired
        // in installFocusLostCommit() (there is no peer→FocusEvent bridge
        // today); this branch keeps the policy consistent for a programmatic
        // AWT FOCUS_LOST dispatch, converging on the same applyFocusLostBehavior.
        if (e != null && e.getID() == vaadinx.awt.event.FocusEvent.FOCUS_LOST) {
            applyFocusLostBehavior();
        }
    }
}
