/*
 * Copyright (c) 1997, 2022, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JLabel
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

import com.vaadin.swingbridge.surrogates.SJLabel;
import vaadinx.EHelper;

import javax.accessibility.Accessible;
import javax.accessibility.AccessibleContext;
import javax.swing.SwingConstants;
import javax.swing.plaf.LabelUI;
import java.awt.Image;
import java.util.Objects;
import java.util.function.Supplier;

// Generated by vaadinx.internal.Generator from javax.swing.JLabel
// Hand-finished — text + icon are wired to the SJLabel peer (NativeLabel-
// based, with manual DOM children for the icon-text coexistence story);
// alignment/text-position/gap/mnemonic round-trip as fields only.
// Alignment/text-position CSS deferred per surrogate's drop-and-WARN —
// see SD_sjlabel.

/** Emulator for {@link javax.swing.JLabel}. */
public class JLabel extends JComponent implements SwingConstants, Accessible {

    // Text is stored Swing-side so getText round-trips null; peer sees
    // "" when the field is null — Vaadin Span.setText NPEs on null.
    private String text;
    private Icon icon;
    private Icon disabledIcon;

    // Alignment / text position / gap — Swing defaults. Field-only
    // round-trip: Vaadin Span doesn't expose these as first-class
    // properties, and translating to CSS (text-align etc.) without
    // modeling the icon-vs-text layout meaningfully would be lossy.
    // Stored so getters report what setters received.
    private int horizontalAlignment = LEADING;
    private int verticalAlignment = CENTER;
    private int horizontalTextPosition = TRAILING;
    private int verticalTextPosition = CENTER;
    private int iconTextGap = 4;

    // Mnemonic state. Swing stores these with -1 meaning "no underline".
    // We don't paint underlines (R_layouts_close_enough), so the fields are round-trip only.
    private int displayedMnemonic = 0;
    private int displayedMnemonicIndex = -1;

    // Accessibility wiring (<label for="id">) would need peer-ID minting;
    // deferred. Field-only today so getLabelFor honours what
    // was set.
    protected vaadinx.awt.Component labelFor;

    public JLabel() {
        // Swing's no-arg: "" text, no icon, LEADING.
        this("", null, LEADING);
    }

    public JLabel(Icon image) {
        // Icon-only convenience defaults to CENTER — an image without
        // text typically wants the image centered, not LEADING.
        this(null, image, CENTER);
    }

    public JLabel(Icon image, int horizontalAlignment) {
        this(null, image, horizontalAlignment);
    }

    public JLabel(String text) {
        this(text, null, LEADING);
    }

    public JLabel(String text, int horizontalAlignment) {
        this(text, null, horizontalAlignment);
    }

    public JLabel(String text, Icon icon, int horizontalAlignment) {
        // Root public ctor — every other ctor funnels here, which in
        // turn hands its peer to the protected super ctor. The
        // setHorizontalAlignment → setText → setIcon order matches
        // Swing's own JLabel ctor so subclasses overriding any of these
        // see the same call sequence during construction. Peer is the
        // SJLabel surrogate (NativeLabel-based) — handles text + icon
        // coexistence via manual DOM children per SD_sjlabel. Built lazily, once a UI is
        // current, so a label made on a worker runs no Vaadin code there.
        super(SJLabel.class, SJLabel::new);
        setHorizontalAlignment(horizontalAlignment);
        setText(text);
        setIcon(icon);
        setAlignmentX(LEFT_ALIGNMENT);   // JDK's ctor closes with this, so getAlignmentX() is 0.0f
    }

    protected JLabel(com.vaadin.flow.component.Component peer) {
        super(peer);
    }

    /** The lazy form: see {@link vaadinx.awt.Component#Component(Class, Supplier)}. */
    protected <P extends com.vaadin.flow.component.Component> JLabel(Class<P> peerType,
            Supplier<? extends P> peerFactory) {
        super(peerType, peerFactory);
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        // R_swing_is_truth shape: capture old, update field, push to peer, fire PCE.
        // No preventPeerEvents guard — SJLabel has no bidirectional value
        // channel back to us; the write is one-way. Null at the field
        // round-trips; SJLabel writes "" so the inner text-bearing Span
        // doesn't NPE on Vaadin's HasText.
        String old = this.text;
        if (Objects.equals(old, text)) return;
        this.text = text;
        withPeer(p -> {
            if (p instanceof SJLabel sj) sj.setText(text == null ? "" : text);
        });
        firePropertyChange("text", old, text);
    }

    public Icon getIcon() {
        return icon;
    }

    public void setIcon(Icon icon) {
        // R_swing_is_truth shape: store the field, push to the SJLabel peer, fire PCE.
        // Path 1 (D_icon_rendering): ImageIcon unwraps to its JDK
        // delegate and SJLabel runs the bridge. Other Icon impls drop
        // with a WARN — they'd reach SJLabel as null anyway, but
        // surfacing the WARN here names "JLabel" as the receiver in
        // migration logs (the surrogate-side WARN would say "SJLabel").
        //
        // The push runs through withPeerOnLiveUI (R_tolerate_off_ui_thread's Swing→peer seam)
        // because this one is reachable from a background thread in practice and
        // fails there without it: an
        // ImageIcon becomes a Vaadin Image, whose ctor resolves a StreamResource URI
        // and so needs a current UI. Measured on testapps/inventory, where a
        // SwingWorker.doInBackground() builds an error popup. State and notification
        // stay on the calling thread — only the effect hops, per R_decline_effect_only.
        Icon old = this.icon;
        if (old == icon) return;
        this.icon = icon;
        withPeerOnLiveUI(false, peer -> {
            if (peer instanceof SJLabel sj) {
                if (icon == null) {
                    sj.setIcon((javax.swing.Icon) null);
                } else if (icon instanceof ImageIcon ours) {
                    sj.setIcon(ours.asJdk());
                } else {
                    sj.setIcon((javax.swing.Icon) null);
                    EHelper.onUnimplemented("JLabel", "setIcon", icon);
                }
            }
        });
        firePropertyChange("icon", old, icon);
    }

    public Icon getDisabledIcon() {
        return disabledIcon;
    }

    public void setDisabledIcon(Icon disabledIcon) {
        Icon old = this.disabledIcon;
        if (old == disabledIcon) return;
        this.disabledIcon = disabledIcon;
        firePropertyChange("disabledIcon", old, disabledIcon);
    }

    public int getHorizontalAlignment() {
        return horizontalAlignment;
    }

    public void setHorizontalAlignment(int alignment) {
        // Swing validates and throws on unknown values — D_never_fail_on_gaps preserves
        // those failure modes even while we don't render the alignment.
        int checked = checkHorizontalKey(alignment, "horizontalAlignment");
        int old = this.horizontalAlignment;
        if (old == checked) return;
        this.horizontalAlignment = checked;
        firePropertyChange("horizontalAlignment", old, checked);
    }

    public int getVerticalAlignment() {
        return verticalAlignment;
    }

    public void setVerticalAlignment(int alignment) {
        int checked = checkVerticalKey(alignment, "verticalAlignment");
        int old = this.verticalAlignment;
        if (old == checked) return;
        this.verticalAlignment = checked;
        firePropertyChange("verticalAlignment", old, checked);
    }

    public int getHorizontalTextPosition() {
        return horizontalTextPosition;
    }

    public void setHorizontalTextPosition(int textPosition) {
        int checked = checkHorizontalKey(textPosition, "horizontalTextPosition");
        int old = this.horizontalTextPosition;
        if (old == checked) return;
        this.horizontalTextPosition = checked;
        firePropertyChange("horizontalTextPosition", old, checked);
    }

    public int getVerticalTextPosition() {
        return verticalTextPosition;
    }

    public void setVerticalTextPosition(int textPosition) {
        int checked = checkVerticalKey(textPosition, "verticalTextPosition");
        int old = this.verticalTextPosition;
        if (old == checked) return;
        this.verticalTextPosition = checked;
        firePropertyChange("verticalTextPosition", old, checked);
    }

    public int getIconTextGap() {
        return iconTextGap;
    }

    public void setIconTextGap(int iconTextGap) {
        // Swing fires propertyChange but doesn't validate here — any
        // int is accepted (negative gaps are unusual but legal). Match.
        int old = this.iconTextGap;
        if (old == iconTextGap) return;
        this.iconTextGap = iconTextGap;
        firePropertyChange("iconTextGap", old, iconTextGap);
    }

    public int getDisplayedMnemonic() {
        return displayedMnemonic;
    }

    public void setDisplayedMnemonic(int key) {
        int old = this.displayedMnemonic;
        if (old == key) return;
        this.displayedMnemonic = key;
        firePropertyChange("displayedMnemonic", old, key);
    }

    public void setDisplayedMnemonic(char aChar) {
        // Swing's char overload upper-cases and delegates to the int form. The (int)
        // cast is load-bearing: Character.toUpperCase(char) returns a char, so without
        // it this overload calls itself until the stack runs out.
        setDisplayedMnemonic((int) Character.toUpperCase(aChar));
    }

    public int getDisplayedMnemonicIndex() {
        return displayedMnemonicIndex;
    }

    public void setDisplayedMnemonicIndex(int index) throws IllegalArgumentException {
        // Swing allows -1 unconditionally (no underline); any other value
        // must be a valid index into the current text. When text is null,
        // only -1 is legal — matching real Swing, which uses textLength=0
        // and rejects index>=0 in that case.
        if (index != -1) {
            int textLen = (text == null) ? 0 : text.length();
            if (index < -1 || index >= textLen) {
                throw new IllegalArgumentException("Invalid mnemonic index: " + index);
            }
        }
        int old = this.displayedMnemonicIndex;
        if (old == index) return;
        this.displayedMnemonicIndex = index;
        firePropertyChange("displayedMnemonicIndex", old, index);
    }

    public vaadinx.awt.Component getLabelFor() {
        return labelFor;
    }

    public void setLabelFor(vaadinx.awt.Component c) {
        // Field-only round-trip; accessibility wiring (<label for="id">)
        // needs peer-ID minting and is deferred.
        vaadinx.awt.Component old = this.labelFor;
        if (old == c) return;
        this.labelFor = c;
        firePropertyChange("labelFor", old, c);
    }

    protected int checkHorizontalKey(int key, String message) {
        // Swing's protected validation seam. Valid horizontal keys:
        // LEFT, CENTER, RIGHT, LEADING, TRAILING. Throws IAE otherwise.
        // Kept protected so user subclasses can widen/tighten the set
        // (rare, but Swing exposes it for that reason).
        if (key == LEFT || key == CENTER || key == RIGHT
                || key == LEADING || key == TRAILING) {
            return key;
        }
        throw new IllegalArgumentException(message);
    }

    protected int checkVerticalKey(int key, String message) {
        // Valid vertical keys: TOP, CENTER, BOTTOM.
        if (key == TOP || key == CENTER || key == BOTTOM) {
            return key;
        }
        throw new IllegalArgumentException(message);
    }

    public boolean imageUpdate(Image img, int infoflags, int x, int y, int w, int h) {
        // Real JLabel overrides to short-circuit on the disabled icon
        // (skipping the repaint chain). We don't paint (R_layouts_close_enough) so
        // Component's "always return false — image is as loaded as
        // it'll ever get" is the honest answer. Chain kept so any
        // future paint-pipeline work lands in one place.
        return super.imageUpdate(img, infoflags, x, y, w, h);
    }

    public String getUIClassID() {
        // Swing constant for L&F delegate lookup. We don't plug L&F
        // (Vaadin owns the DOM), but the canonical value keeps
        // UIManager reflective lookups from NPEing — same shape as
        // JButton.getUIClassID and JPanel.getUIClassID.
        return "LabelUI";
    }

    public LabelUI getUI() {
        EHelper.onUnimplemented("JLabel", "getUI");
        return null;
    }

    public void setUI(LabelUI ui) {
        EHelper.onUnimplemented("JLabel", "setUI", ui);
    }

    public void updateUI() {
        // L&F swap — no-op. Real Swing reinstalls a LabelUI from
        // UIManager; our rendering is the Span peer, not pluggable.
    }

    protected String paramString() {
        // Chain up and append JLabel-specific state — matches Swing's
        // toString shape so migrated debug-logging code stays readable.
        return super.paramString()
                + ",defaultIcon=" + (icon == null ? "" : icon)
                + ",disabledIcon=" + (disabledIcon == null ? "" : disabledIcon)
                + ",horizontalAlignment=" + horizontalAlignment
                + ",horizontalTextPosition=" + horizontalTextPosition
                + ",iconTextGap=" + iconTextGap
                + ",text=" + (text == null ? "" : text)
                + ",verticalAlignment=" + verticalAlignment
                + ",verticalTextPosition=" + verticalTextPosition;
    }

    public AccessibleContext getAccessibleContext() {
        EHelper.onUnimplemented("JLabel", "getAccessibleContext");
        return null;
    }

}
