/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JPanel
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JPanel
// Hand-finished — each public ctor funnels through the LayoutManager +
// boolean form, matching Swing's own ctor chain (which converges on the
// two-arg ctor below).

/** Emulator for {@link javax.swing.JPanel}. */
public class JPanel extends vaadinx.swing.JComponent implements javax.accessibility.Accessible {

    public JPanel() {
        // Swing's JPanel default layout is FlowLayout — migrated code that
        // does `new JPanel()` then adds children expects the flex-wrap
        // flow behavior, not raw block-stacking. isDoubleBuffered=true
        // matches Swing's default (accepted-and-dropped here; R_layouts_close_enough).
        this(new vaadinx.awt.FlowLayout(), true);
    }

    public JPanel(boolean isDoubleBuffered) {
        this(new vaadinx.awt.FlowLayout(), isDoubleBuffered);
    }

    public JPanel(vaadinx.awt.LayoutManager layout) {
        this(layout, true);
    }

    public JPanel(vaadinx.awt.LayoutManager layout, boolean isDoubleBuffered) {
        // SJPanel peer (SD_sjpanel; locked-down per R_leaf_peer_lockdown — JPanel is a leaf in
        // the public javax.swing hierarchy, nothing in javax.swing.*
        // extends it). SJPanel IS-A Div so locator paths still resolve.
        // The surrogate brings
        // inherited mixin layout / opaque / border CSS dispatch for
        // pure-surrogate users; the emulator continues to drive its own
        // setLayout / setOpaque path on top, which writes to the same
        // host element since SJPanel is the peer.
        //
        // Real Swing chains:
        //   setLayout(layout); setDoubleBuffered(...); setUIProperty("opaque", TRUE); updateUI();
        super(new com.vaadin.swingbridge.surrogates.SJPanel());
        setLayout(layout);
        setDoubleBuffered(isDoubleBuffered);   // no buffer to install, but isDoubleBuffered() answers it
        setOpaque(true);  // Real Swing sets this via setUIProperty at L&F time.
    }

    protected java.lang.String paramString() {
        // Real Swing's JPanel.paramString chains up and adds nothing —
        // JPanel has no state of its own beyond what JComponent (opaque,
        // doubleBuffered) and Container (layout=) already report.
        return super.paramString();
    }

    public void updateUI() {
        // L&F swap — no-op for us. Real Swing reinstalls a PanelUI from
        // UIManager; our "UI" is the Vaadin Div peer, which isn't
        // pluggable. Safe to ignore — same shape as JButton.updateUI.
    }

    public javax.swing.plaf.PanelUI getUI() {
        // No UI delegate; real Swing hands back a BasicPanelUI. Null-and-
        // WARN so migration logs surface user/library code that reaches
        // for the UI delegate (rare, but happens in L&F-aware apps).
        vaadinx.EHelper.onUnimplemented("JPanel", "getUI");
        return null;
    }

    public void setUI(javax.swing.plaf.PanelUI arg0) {
        // L&F surgery — we don't model it (see updateUI). Silent accept
        // would hide integration gaps; warn.
        vaadinx.EHelper.onUnimplemented("JPanel", "setUI", arg0);
    }

    public java.lang.String getUIClassID() {
        // Swing constant; some user/library code reads reflectively to
        // register custom UIs against UIManager. L&F doesn't drive
        // rendering here (Vaadin owns the DOM), but the canonical value
        // keeps such lookups from NPEing — same shape as JButton.
        return "PanelUI";
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JPanel", "getAccessibleContext");
        return null;
    }

}
