/*
 * Copyright (c) 1997, 2022, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JPasswordField
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JPasswordField
// Hand-finished. Peer is always
// com.vaadin.swingbridge.surrogates.SJPasswordField (locked down per R_leaf_peer_lockdown) which extends Vaadin PasswordField (a
// TextFieldBase) so the R_swing_is_truth Document↔peer sync lifted into JTextComponent
// works transparently. A surrogate-layer R_swing_is_truth sync runs alongside
// — same two-layer Document↔peer shape SD_sjtextfield documents for SJTextField
// (each layer's preventPeerEvents flag is independent; Vaadin's idempotent
// setValue makes the surrogate's echo back to the peer a no-op so the
// chain naturally converges).
//
// Peer lock-down: nothing in this codebase or in the JDK extends
// JPasswordField (it is a leaf class in javax.swing's hierarchy). With no
// subclass needing the D_peer_ctor_injection custom-peer escape hatch, the protected
// JPasswordField(Component peer) ctor is gone and the root public ctor
// calls super(new SJPasswordField()) directly. Result: every JPasswordField
// instance — through any public ctor or any future subclass — is guaranteed
// to peer over an SJPasswordField. The class itself stays non-final to
// match JDK shape per R_swing_is_truth, but the peer type is locked at the type system
// level: a subclass can only reach super through the public ctors, all of
// which hard-code SJPasswordField. The same lock-down isn't applied to
// vaadinx.swing.JTextField because JPasswordField extends it — JTextField's
// protected (Component peer) ctor is the seam JPasswordField uses to pass
// SJPasswordField up the chain.
//
// JPasswordField's JDK-distinctive surface is:
//   - getPassword() returns char[]  (not String; caller is expected to
//     clear the array after use so cleartext doesn't linger in the heap);
//   - getText() / getText(int,int) are @Deprecated in favour of it;
//   - copy / cut beep and decline rather than leak cleartext to the
//     system clipboard.
//
// getText() returns CLEARTEXT, like the JDK's. It does not mask, and no
// getter here reads echoChar — that is a rendering input consumed only by
// BasicPasswordFieldUI's view, and the browser's `<input type=password>`
// plays that role for us. SB-Emulators believed the inverse from 2026-04-22 to
// 2026-09-01 and shipped a masking getText(); see SD_sjpasswordfield's
// correction note for the false premise and how it propagated.
//
// echoChar is a field here, as in the JDK, and getPassword() reads this
// layer's own Document, so neither reads the peer and both answer on any
// thread — a login SwingWorker reading the password in doInBackground() is
// the case that matters (D_emulator_owned_state). setEchoChar
// pushes the value on to SJPasswordField through withPeer; the surrogate
// keeps its own copy for stage-3 code and raises the masking WARN.

/** Emulator for {@link javax.swing.JPasswordField}. */
public class JPasswordField extends vaadinx.swing.JTextField {

    // '*' is JPasswordField.updateUI's fallback. The JDK's actual default comes from
    // the look and feel (Metal's is '\u2022'), and L&F dispatch is out of scope.
    private char echoChar = '*';

    public JPasswordField() {
        this(null, null, 0);
    }

    public JPasswordField(java.lang.String text) {
        this(null, text, 0);
    }

    public JPasswordField(int columns) {
        this(null, null, columns);
    }

    public JPasswordField(java.lang.String text, int columns) {
        this(null, text, columns);
    }

    public JPasswordField(javax.swing.text.Document doc, java.lang.String text, int columns) {
        // Root ctor — mirrors JTextField's shape. Peer is hard-coded to
        // com.vaadin.swingbridge.surrogates.SJPasswordField (lock-down per file-header
        // comment); calling super directly rather than chaining via a
        // protected (Component peer) ctor closes the only seam through
        // which a subclass could swap the peer type. The browser still
        // renders `<input type="password">` natively (SJPasswordField
        // extends Vaadin PasswordField). Columns / document / initial-
        // text wiring identical to JTextField; JTextComponent's ctor
        // installs the emulator-side R_swing_is_truth sync, and SJPasswordField's own
        // ctor installs the surrogate-side sync — see SD_sjtextfield §"Two-layer
        // R_swing_is_truth sync" for the convergence argument.
        super(new com.vaadin.swingbridge.surrogates.SJPasswordField());
        if (columns < 0) {
            throw new IllegalArgumentException("columns less than zero.");
        }
        if (doc != null) {
            setDocument(doc);
        }
        if (columns > 0) {
            setColumns(columns);
        }
        if (text != null) {
            setText(text);
        }
    }

    /** Narrow the peer to its SJPasswordField type; peer is locked-down per R_leaf_peer_lockdown. */
    private com.vaadin.swingbridge.surrogates.SJPasswordField surrogate() {
        return (com.vaadin.swingbridge.surrogates.SJPasswordField) getPeer();
    }

    /**
     * @return a fresh array the caller should zero after use, or {@code null} when the
     *     Document refuses to hand over its text, as in the JDK
     */
    public char[] getPassword() {
        javax.swing.text.Document doc = getDocument();
        javax.swing.text.Segment txt = new javax.swing.text.Segment();
        try {
            doc.getText(0, doc.getLength(), txt); // use the non-String API
        } catch (javax.swing.text.BadLocationException e) {
            return null;
        }
        char[] retValue = new char[txt.count];
        System.arraycopy(txt.array, txt.offset, retValue, 0, txt.count);
        return retValue;
    }

    /**
     * Returns cleartext, as the JDK does. Kept as an override — rather than
     * inherited — because that is exactly what the JDK does: both bodies are
     * {@code return super.getText(...)} and exist only to carry
     * {@code @Deprecated}, so a migrator recompiling against SB-Emulators keeps the
     * javac warning their Swing build already emitted.
     *
     * @deprecated per the JDK. Prefer {@link #getPassword()}: this returns an
     *     immutable {@code String} that cannot be zeroed after use.
     */
    @Deprecated
    public java.lang.String getText() {
        return super.getText();
    }

    /** @deprecated per the JDK; see {@link #getText()}. */
    @Deprecated
    public java.lang.String getText(int offs, int len) throws javax.swing.text.BadLocationException {
        return super.getText(offs, len);
    }

    public char getEchoChar() {
        return echoChar;
    }

    public void setEchoChar(char c) {
        echoChar = c;
        // The surrogate raises the R_match_swing_errors sub-bucket (c) WARN when
        // the masked-vs-cleartext boundary is crossed — see SJPasswordField.setEchoChar.
        // The push reaches nothing observable: the browser's visual mask is
        // unchanged either way (no Vaadin server-side toggle exists — direct
        // migrators at setRevealButtonVisible for the "show password" UX).
        //
        // No PropertyChangeEvent at either layer: JPasswordField.setEchoChar
        // assigns, then repaint() + revalidate() (D_property_fanout_audit).
        withPeer(p -> surrogate().setEchoChar(c));
    }

    public boolean echoCharIsSet() {
        return echoChar != 0;
    }

    public void copy() {
        // Swing: copy() invokes the toolkit's beep() and refuses, on
        // the grounds that sending cleartext to the system clipboard
        // defeats the point of a password field. We can't beep on the
        // server — log + decline.
        vaadinx.EHelper.onUnsupported("JPasswordField", "copy");
    }

    public void cut() {
        // Same rationale as copy(): Swing declines to cut from a
        // password field.
        vaadinx.EHelper.onUnsupported("JPasswordField", "cut");
    }

    public java.lang.String getUIClassID() {
        return "PasswordFieldUI";
    }

    protected java.lang.String paramString() {
        // Unmasked, as the JDK's own body prints it.
        return super.paramString() + ",echoChar=" + echoChar;
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JPasswordField", "getAccessibleContext");
        return null;
    }
}
