/*
 * Copyright (c) 1997, 2024, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JTextArea
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JTextArea
// Hand-finished. Peer is always com.vaadin.swingbridge.surrogates.SJTextArea (locked down
// per R_leaf_peer_lockdown) which extends Vaadin TextArea
// (a TextFieldBase) so the R_swing_is_truth Document↔peer sync lifted into JTextComponent
// works transparently. A surrogate-layer R_swing_is_truth sync runs alongside
// — same two-layer Document↔peer shape SD_sjtextfield documents for SJTextField and
// SD_sjpasswordfield documents for SJPasswordField (each layer's preventPeerEvents flag
// is independent; Vaadin's idempotent setValue makes the surrogate's echo
// back to the peer a no-op so the chain naturally converges).
//
// Peer lock-down: nothing in this codebase or in the JDK extends JTextArea
// (it is a leaf class in javax.swing's hierarchy). With no subclass needing
// the D_peer_ctor_injection custom-peer escape hatch, the protected JTextArea(Component peer)
// ctor is gone and the root public ctor peers on SJTextArea
// directly via JTextComponent's (Component peer) ctor. Result: every
// JTextArea instance — through any public ctor or any future subclass —
// is guaranteed to peer over an SJTextArea. The class itself stays
// non-final to match JDK shape per R_swing_is_truth.
//
// JTextArea-specific state lives where the JDK keeps it: rows / columns /
// wrap / word are fields here, and tabSize is the Document's
// PlainDocument.tabSizeAttribute property, so installing a new Document
// resets it to that Document's own value, as in Swing. No getter reads the
// peer, so every one of them answers on any thread
// (D_emulator_owned_state). Each setter pushes the value on
// to SJTextArea through withPeer: rows / columns become its CSS sizing,
// the other three are field-only there.

/** Emulator for {@link javax.swing.JTextArea}. */
public class JTextArea extends vaadinx.swing.text.JTextComponent {

    private int rows;
    private int columns;
    private boolean word;
    private boolean wrap;

    public JTextArea() {
        this(null, null, 0, 0);
    }

    public JTextArea(java.lang.String text) {
        this(null, text, 0, 0);
    }

    public JTextArea(int rows, int columns) {
        this(null, null, rows, columns);
    }

    public JTextArea(java.lang.String text, int rows, int columns) {
        this(null, text, rows, columns);
    }

    public JTextArea(javax.swing.text.Document doc) {
        this(doc, null, 0, 0);
    }

    public JTextArea(javax.swing.text.Document doc, java.lang.String text, int rows, int columns) {
        // Root public ctor — all others funnel here. Peer is hard-coded
        // to com.vaadin.swingbridge.surrogates.SJTextArea (lock-down per file-header
        // comment); calling super directly rather than chaining via a
        // protected (Component peer) ctor closes the only seam through
        // which a subclass could swap the peer type. JTextComponent's
        // ctor installs the emulator-side R_swing_is_truth sync, and SJTextArea's own
        // ctor installs the surrogate-side sync — see SD_sjtextfield §"Two-layer
        // R_swing_is_truth sync" for the convergence argument.
        super(com.vaadin.swingbridge.surrogates.SJTextArea.class, com.vaadin.swingbridge.surrogates.SJTextArea::new);
        if (rows < 0) {
            // JDK throws IAE on negative rows/columns.
            throw new IllegalArgumentException("rows: " + rows);
        }
        if (columns < 0) {
            throw new IllegalArgumentException("columns: " + columns);
        }
        if (doc != null) {
            setDocument(doc);
        }
        // Assigned, not set: the JDK's ctor writes the fields, so a subclass's
        // setRows override is not called from here.
        this.rows = rows;
        this.columns = columns;
        withPeer(p -> {
            if (rows > 0) surrogate().setRows(rows);
            if (columns > 0) surrogate().setColumns(columns);
        });
        if (text != null) {
            setText(text);
        }
    }

    /** Narrow the peer to its SJTextArea type; peer is locked-down per R_leaf_peer_lockdown. */
    private com.vaadin.swingbridge.surrogates.SJTextArea surrogate() {
        return (com.vaadin.swingbridge.surrogates.SJTextArea) getPeer();
    }

    public int getRows() {
        return rows;
    }

    public void setRows(int rows) {
        int oldVal = this.rows;
        if (rows < 0) {
            throw new IllegalArgumentException("rows less than zero.");
        }
        if (rows != oldVal) {
            this.rows = rows;
            // The JDK invalidates; the pixel layout is R_layouts_close_enough, and
            // SJTextArea turns rows into min-rows CSS. No PropertyChangeEvent.
            withPeer(p -> surrogate().setRows(rows));
        }
    }

    public int getColumns() {
        return columns;
    }

    public void setColumns(int columns) {
        int oldVal = this.columns;
        if (columns < 0) {
            throw new IllegalArgumentException("columns less than zero.");
        }
        if (columns != oldVal) {
            this.columns = columns;
            withPeer(p -> surrogate().setColumns(columns));
        }
    }

    public int getTabSize() {
        int size = 8;
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            Integer i = (Integer) doc.getProperty(javax.swing.text.PlainDocument.tabSizeAttribute);
            if (i != null) {
                size = i.intValue();
            }
        }
        return size;
    }

    public void setTabSize(int size) {
        javax.swing.text.Document doc = getDocument();
        if (doc != null) {
            int old = getTabSize();
            doc.putProperty(javax.swing.text.PlainDocument.tabSizeAttribute, Integer.valueOf(size));
            withPeer(p -> surrogate().setTabSize(size));
            firePropertyChange("tabSize", old, size);
        }
    }

    public boolean getLineWrap() {
        return wrap;
    }

    public void setLineWrap(boolean wrap) {
        boolean old = this.wrap;
        this.wrap = wrap;
        withPeer(p -> surrogate().setLineWrap(wrap));
        firePropertyChange("lineWrap", old, wrap);
    }

    public boolean getWrapStyleWord() {
        return word;
    }

    public void setWrapStyleWord(boolean word) {
        boolean old = this.word;
        this.word = word;
        withPeer(p -> surrogate().setWrapStyleWord(word));
        firePropertyChange("wrapStyleWord", old, word);
    }

    public void append(java.lang.String str) {
        // Mutations route through the emulator's own Document so
        // emulator-registered DocumentListeners still fire. The R_swing_is_truth sync
        // mirrors into the surrogate's Document via the peer's
        // setValue echo path (two-layer convergence per SD_sjtextfield).
        if (str == null) return;
        javax.swing.text.Document doc = getDocument();
        try {
            doc.insertString(doc.getLength(), str, null);
        } catch (javax.swing.text.BadLocationException e) {
            vaadinx.EHelper.onUnsupported("JTextArea", "append", e);
        }
    }

    public void insert(java.lang.String str, int pos) {
        // JDK throws IAE when pos is out of range — we match per R_match_swing_errors/D_never_fail_on_gaps.
        if (str == null) return;
        javax.swing.text.Document doc = getDocument();
        if (pos < 0 || pos > doc.getLength()) {
            throw new IllegalArgumentException(
                    "Invalid insert position " + pos);
        }
        try {
            doc.insertString(pos, str, null);
        } catch (javax.swing.text.BadLocationException e) {
            vaadinx.EHelper.onUnsupported("JTextArea", "insert", e);
        }
    }

    public void replaceRange(java.lang.String str, int start, int end) {
        // JDK validates start/end against document length; null str
        // means "just delete the range." IAE on bad bounds matches JDK.
        javax.swing.text.Document doc = getDocument();
        if (start < 0 || end < start || end > doc.getLength()) {
            throw new IllegalArgumentException(
                    "Invalid range: start=" + start + " end=" + end);
        }
        try {
            doc.remove(start, end - start);
            if (str != null && !str.isEmpty()) {
                doc.insertString(start, str, null);
            }
        } catch (javax.swing.text.BadLocationException e) {
            vaadinx.EHelper.onUnsupported("JTextArea", "replaceRange", e);
        }
    }

    public int getLineCount() {
        // PlainDocument's root element has one child per line — that's
        // exactly Swing's line count. Works for any Document that
        // models lines via the default root element, which covers the
        // common case. Non-line-structured Documents get 0.
        javax.swing.text.Document doc = getDocument();
        javax.swing.text.Element root = doc.getDefaultRootElement();
        return root == null ? 0 : root.getElementCount();
    }

    public int getLineOfOffset(int offset) throws javax.swing.text.BadLocationException {
        javax.swing.text.Document doc = getDocument();
        if (offset < 0 || offset > doc.getLength()) {
            throw new javax.swing.text.BadLocationException(
                    "Invalid offset", offset);
        }
        return doc.getDefaultRootElement().getElementIndex(offset);
    }

    public int getLineStartOffset(int line) throws javax.swing.text.BadLocationException {
        javax.swing.text.Element root = getDocument().getDefaultRootElement();
        if (line < 0 || line >= root.getElementCount()) {
            throw new javax.swing.text.BadLocationException(
                    "No such line", line);
        }
        return root.getElement(line).getStartOffset();
    }

    public int getLineEndOffset(int line) throws javax.swing.text.BadLocationException {
        javax.swing.text.Element root = getDocument().getDefaultRootElement();
        if (line < 0 || line >= root.getElementCount()) {
            throw new javax.swing.text.BadLocationException(
                    "No such line", line);
        }
        return root.getElement(line).getEndOffset();
    }

    /**
     * The JDK's document factory for this class, and the documented seam for
     * installing a custom {@link javax.swing.text.Document} on a JTextArea
     * subclass. Returns a fresh {@code PlainDocument}, as Swing does.
     */
    protected javax.swing.text.Document createDefaultModel() {
        return super.createDefaultDocument();
    }

    /**
     * Routes the base class's construction-time document factory to this class's
     * JDK-shaped one, so a subclass overriding {@link #createDefaultModel} is
     * actually reached (R_no_vaadin_in_api second limb, D_r12_provenance). Same construction-order caveat as
     * {@link JTextField#createDefaultDocument()}, and the same as Swing's.
     */
    @Override
    protected javax.swing.text.Document createDefaultDocument() {
        return createDefaultModel();
    }

    public java.awt.Dimension getPreferredSize() {
        // Pixel sizing is R_layouts_close_enough close-enough; rows/columns already drive
        // peer CSS width/minRows. Chain for symmetry with JTextField.
        return super.getPreferredSize();
    }

    protected int getColumnWidth() {
        // Same rationale as JTextField.getColumnWidth — we don't carry
        // font metrics (R_layouts_close_enough); return 0 and log.
        vaadinx.EHelper.onUnimplemented("JTextArea", "getColumnWidth");
        return 0;
    }

    protected int getRowHeight() {
        vaadinx.EHelper.onUnimplemented("JTextArea", "getRowHeight");
        return 0;
    }

    public void setFont(java.awt.Font f) {
        // Component.setFont writes CSS font-* to the peer and fires
        // the font PCE. JDK JTextArea invalidates its preferred-size
        // cache too — irrelevant here (R_layouts_close_enough).
        super.setFont(f);
    }

    public java.lang.String getUIClassID() {
        return "TextAreaUI";
    }

    public boolean getScrollableTracksViewportWidth() {
        // JDK: true when lineWrap is on OR the textarea's minimum size
        // exceeds the viewport. We don't model viewports; honour the
        // lineWrap-true branch so a wrapped TextArea reports the value
        // user code expects. Without JViewport the returned value is
        // advisory either way.
        return wrap;
    }

    public java.awt.Dimension getPreferredScrollableViewportSize() {
        // Pixel-sizing stub (R_layouts_close_enough); chain to JTextComponent's default.
        return super.getPreferredScrollableViewportSize();
    }

    public int getScrollableUnitIncrement(java.awt.Rectangle visibleRect, int orientation, int direction) {
        // Scroll-increment math needs font metrics we don't have (R_layouts_close_enough).
        // onUnimplemented logs; returning 1 keeps callers that scale
        // it from degenerating to a zero-step infinite loop.
        vaadinx.EHelper.onUnimplemented("JTextArea", "getScrollableUnitIncrement",
                visibleRect, orientation, direction);
        return 1;
    }

    protected java.lang.String paramString() {
        // The JDK's shape, typo included. columWidth / rowHeight are its font-metric
        // caches, which stay 0 until getColumnWidth / getRowHeight fill them; those
        // are unimplemented here (R_layouts_close_enough), so 0 is what the JDK prints too.
        return super.paramString()
                + ",columns=" + columns
                + ",columWidth=0"
                + ",rows=" + rows
                + ",rowHeight=0"
                + ",word=" + word
                + ",wrap=" + wrap;
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JTextArea", "getAccessibleContext");
        return null;
    }
}
