/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JTextField
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JTextField
// Hand-finished. The R_swing_is_truth Document ↔ peer sync is lifted into JTextComponent
// (so JPasswordField and JTextArea inherit it uniformly). This file carries only the
// JTextField-specific surface: Enter-to-ActionEvent, columns → peer width,
// horizontalAlignment validation, and the ActionListener EventListenerList
// bookkeeping.

/** Emulator for {@link javax.swing.JTextField}. */
public class JTextField extends vaadinx.swing.text.JTextComponent implements javax.swing.SwingConstants {

    // The Action name under which Swing's editor kit binds Enter to
    // postActionEvent. Present as a name so getActionMap().get(notifyAction) at a
    // call site compiles; Enter reaches postActionEvent through the peer's own
    // key handling rather than through a keymap, so nothing here looks it up.
    public static final String notifyAction = "notify-field-accept";

    // Swing field defaults. columns=0 means "no preferred width" —
    // JDK ctors allow 0; the setColumns validator rejects negatives
    // (matches Swing).
    private int columns;

    // Swing default: HORIZONTAL alignment = LEADING (text follows the
    // ComponentOrientation). Valid values: LEFT, CENTER, RIGHT,
    // LEADING, TRAILING.
    private int horizontalAlignment = LEADING;

    // actionCommand has a public setter but no public getter on
    // JTextField (Swing quirk — stored internally for Action-driven
    // command propagation). When null, fireActionPerformed falls back
    // to the current text — the meaningful command for a form submit.
    private java.lang.String actionCommand;

    public JTextField() {
        this(null, null, 0);
    }

    public JTextField(java.lang.String text) {
        this(null, text, 0);
    }

    public JTextField(int columns) {
        this(null, null, columns);
    }

    public JTextField(java.lang.String text, int columns) {
        this(null, text, columns);
    }

    public JTextField(javax.swing.text.Document doc, java.lang.String text, int columns) {
        // Root public ctor — all others funnel here so the ctor-time
        // ordering is uniform: create peer (installs the R_swing_is_truth sync in
        // JTextComponent's ctor), then setDocument (if overriding the
        // default), then columns, then initial text. That ordering
        // ensures the internal DocumentListener is live before the
        // first setText call, so the initial text reaches the peer
        // through the same sync path as later edits.
        //
        // Peer is SJTextField (SD_sjtextfield; extends Vaadin
        // TextField). Two-layer R_swing_is_truth sync — emulator's preventPeerEvents
        // and surrogate's preventPeerEvents are independent flags,
        // each guarding its own layer's listener re-entry. Programmatic
        // emulator setText writes peer; Vaadin's idempotent setValue
        // short-circuits when the surrogate's docToPeer push echoes the
        // same value back, so no infinite loop. See SD_sjtextfield.
        this(new com.vaadin.swingbridge.surrogates.SJTextField());
        if (columns < 0) {
            // Swing throws IAE; D_never_fail_on_gaps preserves programming-error failures.
            throw new IllegalArgumentException("columns less than zero.");
        }
        if (doc != null) {
            setDocument(doc);
        }
        this.columns = columns;
        applyColumnsToPeer();
        if (text != null) {
            setText(text);
        }
    }

    protected JTextField(com.vaadin.flow.component.Component peer) {
        super(peer);
        // Enter key fires ActionEvent — Swing JTextField's "submit the
        // form" idiom. fireActionPerformed reads actionCommand (or
        // falls back to text), constructs an ActionEvent with
        // source=this, dispatches LIFO. The R_swing_is_truth Document/peer sync and
        // setEditable propagation now live in JTextComponent's ctor;
        // we only add the JTextField-specific Enter wiring here.
        // JTextArea does NOT inherit this wiring (a newline key in a
        // textarea means "insert a newline," not "submit"), which is
        // why this listener lives here rather than one level up.
        //
        // Today this ctor has three callers: JTextField (peer =
        // SJTextField extends TextField), JPasswordField (peer =
        // SJPasswordField extends PasswordField), and JFormattedTextField
        // post-D_jformattedtextfield (peer is one of SJFormatted* which may not be a
        // TextFieldBase — DatePicker / IntegerField / LongField /
        // NumberField). TextField + PasswordField inherit KeyNotifier
        // via TextFieldBase and get the Enter-as-submit wiring; foreign
        // peers (D_jformattedtextfield strategy dispatch) skip wiring silently — the
        // strategy installs its own commit semantic per D_jtextfield_ctor_widening.
        // The previous "throw on TextArea misuse" defense is preserved
        // because JTextArea extends JTextComponent directly (not
        // JTextField), so a TextArea peer never reaches this ctor.
        if (peer instanceof com.vaadin.flow.component.textfield.TextField
                || peer instanceof com.vaadin.flow.component.textfield.PasswordField) {
            ((com.vaadin.flow.component.KeyNotifier) peer).addKeyPressListener(
                    com.vaadin.flow.component.Key.ENTER,
                    e -> vaadinx.EHelper.callSwing(this::fireActionPerformed));
        }
    }

    public int getColumns() {
        return columns;
    }

    public void setColumns(int columns) {
        // Swing throws IAE on negative columns.
        if (columns < 0) {
            throw new IllegalArgumentException("columns less than zero.");
        }
        if (this.columns == columns) return;
        this.columns = columns;
        applyColumnsToPeer();
        // No PropertyChangeEvent: JTextField.setColumns assigns and calls
        // invalidate(). It is a layout hint, not a bound property (D_property_fanout_audit).
    }

    /**
     * Set the peer's CSS width from the columns hint — one shared mapping with
     * the surrogate side, {@link com.vaadin.swingbridge.surrogates.util.CssConvert#columnsToCssWidth},
     * which documents why the width carries the field's chrome and not just the
     * text. columns=0 clears the width so the peer picks its own default.
     */
    private void applyColumnsToPeer() {
        // The TextFieldBase guard is load-bearing for JPasswordField
        // inheritance, not just D_peer_ctor_injection's custom-peer escape hatch:
        // JPasswordField extends JTextField unchanged but its peer is
        // a raw PasswordField (JTextField's own peer is an
        // SJTextField). A direct cast to TextField (or SJTextField)
        // would crash JPasswordField.setColumns with ClassCastException.
        // TextFieldBase is the lowest common type covering both —
        // SJPasswordField (extends PasswordField)
        // keeps the bound here.
        if (getPeer() instanceof com.vaadin.flow.component.textfield.TextFieldBase<?, ?> tf) {
            // Behind the D_layout_owns_child_sizing variable: columns is a preferred
            // width, so a parent layout that sizes the axis itself overrides it.
            String width = com.vaadin.swingbridge.surrogates.util.LayoutCss.prefWidth(
                    com.vaadin.swingbridge.surrogates.util.CssConvert.columnsToCssWidth(columns));
            withPeer(p -> tf.setWidth(width));
        }
    }

    public int getHorizontalAlignment() {
        return horizontalAlignment;
    }

    public void setHorizontalAlignment(int alignment) {
        // Swing validates and throws; D_never_fail_on_gaps preserves the failure mode
        // even while the alignment itself is field-only (Vaadin
        // TextField doesn't expose text-align for the value directly;
        // CSS mapping deferred).
        if (alignment != LEFT && alignment != CENTER && alignment != RIGHT
                && alignment != LEADING && alignment != TRAILING) {
            throw new IllegalArgumentException("horizontalAlignment");
        }
        int old = this.horizontalAlignment;
        if (old == alignment) return;
        this.horizontalAlignment = alignment;
        firePropertyChange("horizontalAlignment", old, alignment);
    }

    public synchronized void addActionListener(java.awt.event.ActionListener l) {
        // Shared EventListenerList storage — same mechanism as
        // AbstractButton. Null-tolerant via EventListenerList's own
        // null check.
        listenerList.add(java.awt.event.ActionListener.class, l);
    }

    public synchronized void removeActionListener(java.awt.event.ActionListener l) {
        listenerList.remove(java.awt.event.ActionListener.class, l);
    }

    public synchronized java.awt.event.ActionListener[] getActionListeners() {
        return listenerList.getListeners(java.awt.event.ActionListener.class);
    }

    protected void fireActionPerformed() {
        // Source is the emulator (this) — migrated code casts
        // `(JTextField) e.getSource()`, which only works with the
        // emulator, not the Vaadin peer. actionCommand falls back to
        // the current text so a form-style "Enter to submit" carries
        // a meaningful payload by default.
        java.lang.String cmd = (actionCommand != null) ? actionCommand : getText();
        java.awt.event.ActionEvent e = new java.awt.event.ActionEvent(
                this, java.awt.event.ActionEvent.ACTION_PERFORMED, cmd);
        // EventListenerList.getListeners already returns in LIFO
        // order (last-added first) — iterate directly, matching
        // AbstractButton.fireActionPerformed's dispatch shape.
        for (java.awt.event.ActionListener l :
                listenerList.getListeners(java.awt.event.ActionListener.class)) {
            l.actionPerformed(e);
        }
    }

    public void setActionCommand(java.lang.String command) {
        // Swing's setter is public; there's no public getter (stored
        // internally for Action-driven propagation). We match —
        // fireActionPerformed reads the field directly.
        this.actionCommand = command;
    }

    public void postActionEvent() {
        // Swing public entry point equivalent to fireActionPerformed —
        // user code / test harnesses can synthesize an ActionEvent
        // without going through the peer. Useful for non-Enter submit
        // triggers.
        fireActionPerformed();
    }

    /**
     * The JDK's document factory for this class, and the documented seam for
     * installing a custom {@link javax.swing.text.Document} (a filtering
     * {@code PlainDocument} subclass, typically) on a JTextField subclass.
     * Returns a fresh {@code PlainDocument}, as Swing does.
     */
    protected javax.swing.text.Document createDefaultModel() {
        return super.createDefaultDocument();
    }

    /**
     * Routes the base class's construction-time document factory to this class's
     * JDK-shaped one, so that a subclass overriding {@link #createDefaultModel}
     * — the only hook Swing offers here — is actually reached (R_no_vaadin_in_api second limb, D_r12_provenance).
     *
     * <p>Inherits the JDK's own footgun along with its shape: the call happens during
     * {@code JTextComponent}'s constructor, so an override reading the subclass's own
     * fields sees them uninitialized. Swing behaves identically, for the same reason.
     */
    @Override
    protected javax.swing.text.Document createDefaultDocument() {
        return createDefaultModel();
    }

    public java.awt.Dimension getPreferredSize() {
        // Component-level stub (pixel layout, R_layouts_close_enough). The columns hint drives peer width via
        // CSS in applyColumnsToPeer; no pixel computation needed at
        // this level. Chain so any later pixel work lands in one
        // place.
        return super.getPreferredSize();
    }

    protected int getColumnWidth() {
        // Pixel width of a "wide character" in the current font. We
        // don't have metrics (R_layouts_close_enough); return 0 to match Component's
        // other pixel stubs. User code that actually relies on this
        // number for math hits a silent 0, which is survivable —
        // Swing's own answer depends on font metrics we can't
        // replicate.
        vaadinx.EHelper.onUnimplemented("JTextField", "getColumnWidth");
        return 0;
    }

    public void setFont(java.awt.Font f) {
        // Component.setFont writes CSS font-* to the peer and fires
        // the font PCE. Swing's JTextField override invalidates its
        // BoundedRangeModel and revalidates — neither applies here
        // (R_layouts_close_enough/R_infra_not_surface).
        super.setFont(f);
    }

    public java.lang.String getUIClassID() {
        // Swing constant; keeps UIManager reflective lookups from
        // NPEing. L&F doesn't drive rendering here (Vaadin owns the
        // DOM), same stance as JButton / JPanel / JLabel.
        return "TextFieldUI";
    }

    public boolean isValidateRoot() {
        // Real Swing JTextField is a validate root *only* when not inside a
        // JViewport. Validation has no layout effect here — CSS lays the tree out
        // (R_layouts_close_enough) — so Container's default answer stands.
        return super.isValidateRoot();
    }

    protected java.lang.String paramString() {
        // Chain and append JTextField-specific state. Matches Swing's
        // toString shape for migrated debug-logging.
        return super.paramString()
                + ",columns=" + columns
                + ",columnWidth=" + getColumnWidth()
                + ",command=" + (actionCommand == null ? "" : actionCommand)
                + ",horizontalAlignment=" + horizontalAlignment;
    }

    // Action wiring. Narrower than AbstractButton's: JTextField propagates
    // only enabled / SHORT_DESCRIPTION / ACTION_COMMAND_KEY — it doesn't
    // copy Action.NAME into setText (the text is user-entered form data,
    // not a button label) and doesn't model mnemonics or icons. Enter key
    // in the field still fires ActionEvent via the TextField ctor wiring;
    // when an Action is installed, it's registered as an ActionListener so
    // that same dispatch reaches Action.actionPerformed.
    private javax.swing.Action action;
    private java.beans.PropertyChangeListener actionPropertyChangeListener;

    public javax.swing.Action getAction() {
        return action;
    }

    public void setAction(javax.swing.Action a) {
        // Mirrors AbstractButton.setAction shape — tear down old listener
        // pair, seed narrow property set, wire new listener pair, fire PCE.
        javax.swing.Action oldValue = this.action;
        if (oldValue == null ? a == null : oldValue.equals(a)) return;
        this.action = a;
        if (oldValue != null) {
            removeActionListener(oldValue);
            if (actionPropertyChangeListener != null) {
                oldValue.removePropertyChangeListener(actionPropertyChangeListener);
                actionPropertyChangeListener = null;
            }
        }
        configurePropertiesFromAction(a);
        if (a != null) {
            if (!isActionListener(a)) {
                addActionListener(a);
            }
            actionPropertyChangeListener = createActionPropertyChangeListener(a);
            a.addPropertyChangeListener(actionPropertyChangeListener);
        }
        firePropertyChange("action", oldValue, a);
    }

    private boolean isActionListener(java.awt.event.ActionListener a) {
        for (java.awt.event.ActionListener l : listenerList.getListeners(java.awt.event.ActionListener.class)) {
            if (l == a) return true;
        }
        return false;
    }

    protected void configurePropertiesFromAction(javax.swing.Action a) {
        // JDK JTextField's configure shape: enabled + tooltip + command.
        // No NAME or icon propagation (would overwrite the form value).
        setEnabled(a == null || a.isEnabled());
        setToolTipTextFromAction(a);
        setActionCommandFromAction(a);
    }

    private void setToolTipTextFromAction(javax.swing.Action a) {
        // JComponent.setToolTipText drives the peer via HasTooltip; null
        // clears. Pass-through matches JDK's shape: removing
        // SHORT_DESCRIPTION from an attached Action clears the field's
        // tooltip.
        setToolTipText(a == null ? null : (String) a.getValue(javax.swing.Action.SHORT_DESCRIPTION));
    }

    private void setActionCommandFromAction(javax.swing.Action a) {
        // JTextField stores the command internally (no public getter in
        // the JDK either — it's used purely to seed the outgoing
        // ActionEvent on Enter). Null clears; fireActionPerformed falls
        // back to getText() when this is null.
        setActionCommand(a == null ? null : (String) a.getValue(javax.swing.Action.ACTION_COMMAND_KEY));
    }

    protected java.beans.PropertyChangeListener createActionPropertyChangeListener(javax.swing.Action a) {
        return new TextFieldActionPropertyChangeListener(this, a);
    }

    private static final class TextFieldActionPropertyChangeListener
            implements java.beans.PropertyChangeListener, java.io.Serializable {
        private final JTextField field;
        private final javax.swing.Action action;

        TextFieldActionPropertyChangeListener(JTextField field, javax.swing.Action action) {
            this.field = field;
            this.action = action;
        }

        @Override
        public void propertyChange(java.beans.PropertyChangeEvent e) {
            field.actionPropertyChanged(action, e.getPropertyName());
        }
    }

    protected void actionPropertyChanged(javax.swing.Action a, java.lang.String propertyName) {
        // Narrow fan-out matching configurePropertiesFromAction's set.
        if ("enabled".equals(propertyName)) {
            setEnabled(a.isEnabled());
        } else if (propertyName == javax.swing.Action.SHORT_DESCRIPTION) {
            setToolTipTextFromAction(a);
        } else if (propertyName == javax.swing.Action.ACTION_COMMAND_KEY) {
            setActionCommandFromAction(a);
        }
        // Other keys (NAME, MNEMONIC_KEY, icons) are intentionally dropped
        // — a shared Action between a button and a text field updates only
        // the properties that make sense for each.
    }

    // --- onUnimplemented stubs for API that's out of scope.

    public javax.swing.Action[] getActions() {
        // Swing returns the combined editor-kit actions. We don't
        // model the action map (R_infra_not_surface); empty array keeps callers that
        // iterate from NPE.
        return new javax.swing.Action[0];
    }

    public javax.swing.BoundedRangeModel getHorizontalVisibility() {
        vaadinx.EHelper.onUnimplemented("JTextField", "getHorizontalVisibility");
        return null;
    }

    public int getScrollOffset() {
        return scrollOffset;
    }

    /**
     * Stores the offset without scrolling anything — the browser owns the input's
     * horizontal scroll position, and R_decline_effect_only permits dropping the effect
     * but not the state.
     */
    public void setScrollOffset(int scrollOffset) {
        this.scrollOffset = scrollOffset;
        vaadinx.EHelper.onNoop("JTextField", "setScrollOffset");
    }

    /** Horizontal scroll offset in pixels — stored per R_decline_effect_only, never acted on. */
    private int scrollOffset;

    public void scrollRectToVisible(java.awt.Rectangle r) {
        vaadinx.EHelper.onUnimplemented("JTextField", "scrollRectToVisible", r);
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JTextField", "getAccessibleContext");
        return null;
    }

}
