/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JToggleButton
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JToggleButton
// Hand-finished. Thin shell over SJToggleButton, whose peer is a Vaadin
// Button (SD_sjtogglebutton_button_peer) — a bare JToggleButton renders as a stays-pressed button
// (its real Swing look, not a checkbox glyph) and supports icons. The
// surrogate's JToggleButton.ToggleButtonModel is the source of truth for
// selection; click events flow through the surrogate's ButtonModel pulse,
// and the bridges (Action + Change in AbstractButton's ctor; Item below)
// deliver events to the emulator's listenerList with source rebound.
//
// Per D_jradiobutton, the peer-aware code paths (Item-bridge install, setSelected,
// doClick, setText) dispatch on the surrogate's mixin interfaces
// (AbstractButtonMixin for the toggle behaviour) rather than on a concrete
// surrogate type. So the two subclasses that swap in a glyph peer —
// JCheckBox (SJCheckBox → Checkbox) and JRadioButton (SJRadioButton →
// VaadinRadioButton) — hit the same branch without per-peer narrowing.
// setText additionally routes the label through HasLabel for those
// glyph peers, which are HasLabel-not-HasText (see setText below).
//
// A custom non-surrogate Checkbox peer passed through the protected ctor
// keeps a fallback ValueChangeListener path for selection sync; surrogate
// peers route everything through the mixin's model.
//
// `selected` field is updated by the Item bridge so emulator.isSelected
// stays consistent with the surrogate's model; emulator.setSelected
// delegates to the surrogate so the model fires Item + Change → bridges
// re-source them at the emulator level. doClick delegates to the
// surrogate's doClick — the model pulse via ToggleButtonModel toggles
// selected and fires Item + Change + Action all at once.

/** Emulator for {@link javax.swing.JToggleButton}. Thin shell over {@link com.vaadin.swingbridge.surrogates.SJToggleButton} (Button peer, SD_sjtogglebutton_button_peer). */
public class JToggleButton extends vaadinx.swing.AbstractButton implements javax.accessibility.Accessible {

    // Swing's ButtonModel.isSelected, flattened. Defaults to false per
    // JDK JToggleButton. Surrogate path: kept in sync by the Item bridge
    // installed below, so emulator.isSelected stays consistent with the
    // surrogate's model. Legacy non-surrogate path: maintained directly
    // by setSelected / syncSelectedFromPeer.
    private boolean selected;

    // R_swing_is_truth feedback-loop guard for the legacy non-surrogate ValueChangeListener
    // path. Surrogate path doesn't need it — the surrogate's own
    // preventPeerEvents (in SJToggleButton) handles its own loop, and the
    // bridge listeners fire on emulator.listenerList without re-entering
    // setSelected. Kept on the emulator for the protected-ctor non-
    // surrogate fallback.
    private boolean preventPeerEvents;

    // ButtonGroup browser-click coordination guard per D_buttongroup_browser_click. When the
    // SJToggleButton bridge fires for a click that the group vetoes (e.g.
    // user clicks the lone-selected radio trying to deselect it), the
    // bridge pushes the group's verdict back to the surrogate via a
    // guarded sjt.setSelected — which re-enters the bridge with the
    // corrected event. Set during the push-back so the re-entry absorbs
    // into emulator state without re-running group consultation and
    // without re-firing user-facing ItemEvent.
    private boolean preventGroupCoord;

    public JToggleButton() {
        this(null, null, false);
    }

    public JToggleButton(vaadinx.swing.Icon icon) {
        this(null, icon, false);
    }

    public JToggleButton(vaadinx.swing.Icon icon, boolean selected) {
        this(null, icon, selected);
    }

    public JToggleButton(java.lang.String text) {
        this(text, null, false);
    }

    public JToggleButton(java.lang.String text, boolean selected) {
        this(text, null, selected);
    }

    public JToggleButton(java.lang.String text, vaadinx.swing.Icon icon) {
        this(text, icon, false);
    }

    public JToggleButton(javax.swing.Action action) {
        this();
        setAction(action);
    }

    public JToggleButton(java.lang.String text, vaadinx.swing.Icon icon, boolean selected) {
        // Root public ctor — peer defaults to SJToggleButton (Button, SD_sjtogglebutton_button_peer).
        // AbstractButton's ctor wires the Action + Change bridge; our
        // ctor below wires the Item bridge.
        this(new com.vaadin.swingbridge.surrogates.SJToggleButton());
        init(text, icon);
        // Seed selected via the setter so the surrogate's model picks
        // up the initial state and the bridge updates `selected` + fires
        // Item once.
        if (selected) {
            setSelected(true);
        }
    }

    protected JToggleButton(com.vaadin.flow.component.Component peer) {
        super(peer);
        if (peer instanceof com.vaadin.swingbridge.surrogates.swing.AbstractButtonMixin abm) {
            // Item bridge: surrogate's model fires Item via the mixin's
            // bridge ItemListener. We mirror that into emulator.selected
            // and re-fire at the emulator level with source rebound.
            // Action + Change bridges live in AbstractButton's ctor (they
            // apply to every AbstractButtonMixin peer); only Item is
            // JToggleButton-specific.
            //
            // ButtonGroup coordination per D_buttongroup_browser_click: every bridge entry
            // consults the group on the proposed new state and re-reads
            // the group's verdict. When the verdict differs (e.g. lone
            // selection click-to-deselect), push the verdict back to the
            // surrogate via a preventGroupCoord-guarded abm.setSelected
            // — the re-entry absorbs the event into emulator.selected
            // without re-firing user-facing ItemEvent. Cascade to the
            // prior selection (when newSelected=true and the group had
            // a different selectedButton) flows through the group's
            // setSelectedButton, which calls oldSelection.setSelected(false)
            // — that walks AbstractButton.setSelected on the sibling,
            // which (for any AbstractButtonMixin sibling) lands here too
            // via its own surrogate's setSelected pulse.
            abm.addItemListener(e -> vaadinx.EHelper.relayModelEvent(() -> {
                boolean newSelected = e.getStateChange() == java.awt.event.ItemEvent.SELECTED;
                if (preventGroupCoord) {
                    // Re-entry from a prior bridge's group push-back —
                    // just absorb into emulator state. No group consult,
                    // no user-facing fire. The original click already
                    // observed (Action + Change bridged from AbstractButton);
                    // the user-visible ItemEvent semantics for a
                    // group-vetoed toggle is "no Item fired" per JDK
                    // (the model's state didn't actually change), and
                    // that's what we deliver overall.
                    this.selected = newSelected;
                    return;
                }
                if (buttonGroup != null) {
                    buttonGroup.setSelectedButton(this, newSelected);
                    boolean groupVerdict = buttonGroup.isSelectedButton(this);
                    if (groupVerdict != newSelected) {
                        // Group vetoed — push the verdict back to the
                        // surrogate. preventGroupCoord short-circuits
                        // the re-entry above so we don't re-consult or
                        // fire a contradictory ItemEvent.
                        preventGroupCoord = true;
                        try {
                            abm.setSelected(groupVerdict);
                        } finally {
                            preventGroupCoord = false;
                        }
                        return;
                    }
                }
                this.selected = newSelected;
                fireItemStateChanged(new java.awt.event.ItemEvent(
                        this,
                        java.awt.event.ItemEvent.ITEM_STATE_CHANGED,
                        this,
                        e.getStateChange()));
            }));
        } else if (peer instanceof com.vaadin.flow.component.checkbox.Checkbox cb) {
            // Legacy non-surrogate fallback for the protected ctor: a raw
            // Checkbox peer (no surrogate). Wire the ValueChangeListener
            // directly since there's no model pulse to bridge from.
            cb.addValueChangeListener(e -> {
                // Read the feedback-loop guard before entering callSwing, not only
                // inside the callback — see JTextComponent's listener for why.
                if (preventPeerEvents) return;
                vaadinx.EHelper.callSwing(
                        () -> syncSelectedFromPeer(Boolean.TRUE.equals(e.getValue())));
            });
        }
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean b) {
        // ButtonGroup veto per D_buttongroup: when in a group, group.setSelected
        // re-targets selection (cascading deselect to the prior member's
        // setSelected(false), which itself walks this code path on the
        // sibling), and group.isSelected re-reads the verdict so a
        // setSelected(false) on the lone selection becomes a no-op.
        // Consultation happens before any peer write so the cascade
        // settles fully before we touch the surrogate.
        b = consultButtonGroup(b);
        if (getPeer() instanceof com.vaadin.swingbridge.surrogates.swing.AbstractButtonMixin abm) {
            // Surrogate is authority — setSelected delegates to the
            // surrogate's model.setSelected, which fires Item + Change.
            // The bridges in AbstractButton's ctor + this class's ctor
            // re-source those events to the emulator and update `selected`.
            // Equality short-circuit lives inside the surrogate's mixin
            // (model.setSelected returns early on equal).
            abm.setSelected(b);
        } else {
            // Legacy non-surrogate path: direct ItemEvent + ChangeEvent
            // fan-out. Matches the pre-SD_toggle_checkbox_first_cut emulator behaviour.
            if (this.selected == b) return;
            this.selected = b;
            pushSelectedToPeer();
            fireItemStateChanged(new java.awt.event.ItemEvent(
                    this,
                    java.awt.event.ItemEvent.ITEM_STATE_CHANGED,
                    this,
                    b ? java.awt.event.ItemEvent.SELECTED
                      : java.awt.event.ItemEvent.DESELECTED));
            fireStateChanged();
        }
    }

    /**
     * Set the peer's value to match the current {@code selected} field
     * under the preventPeerEvents guard so the peer's
     * ValueChangeListener bails instead of round-tripping. Used only on
     * the legacy non-surrogate path; surrogate-driven setSelected goes
     * through {@link com.vaadin.swingbridge.surrogates.SJToggleButton#setSelected} which
     * has its own push wire.
     */
    private void pushSelectedToPeer() {
        if (getPeer() instanceof com.vaadin.flow.component.checkbox.Checkbox cb) {
            boolean value = selected;
            withPeer(p -> {
                preventPeerEvents = true;
                try {
                    cb.setValue(value);
                } finally {
                    preventPeerEvents = false;
                }
            });
        }
    }

    /**
     * Mirror a peer-originated boolean value into the {@code selected}
     * field and fire the Swing-side ItemEvent + ChangeEvent. Legacy
     * non-surrogate path only.
     */
    private void syncSelectedFromPeer(boolean value) {
        if (preventPeerEvents) return;
        if (this.selected == value) return;
        this.selected = value;
        fireItemStateChanged(new java.awt.event.ItemEvent(
                this,
                java.awt.event.ItemEvent.ITEM_STATE_CHANGED,
                this,
                value ? java.awt.event.ItemEvent.SELECTED
                      : java.awt.event.ItemEvent.DESELECTED));
        fireStateChanged();
    }

    public void doClick(int pressTime) {
        if (getPeer() instanceof com.vaadin.swingbridge.surrogates.swing.AbstractButtonMixin abm) {
            // Route through the surrogate's doClick so the
            // ToggleButtonModel pulse fires (toggles selected + fires
            // Item + Change + Action all in one model state machine
            // step). The bridges deliver everything to the emulator —
            // Item via this class's ctor, Action + Change via
            // AbstractButton's ctor. More JDK-faithful than pre-SD_toggle_checkbox_first_cut's
            // "setSelected then Action" sequence (single Change per click).
            abm.doClick(pressTime);
        } else {
            // Legacy non-surrogate path: serialise setSelected +
            // super.doClick for deterministic ordering.
            setSelected(!selected);
            super.doClick(pressTime);
        }
    }

    public void setText(java.lang.String newText) {
        // AbstractButton.setText pushes into HasText peers and fires PCE.
        // The default peer SJToggleButton is a Button (HasText), so
        // super.setText renders it. The glyph subclasses' peers (SJCheckBox
        // → Checkbox, SJRadioButton → VaadinRadioButton per D_jradiobutton) are
        // HasLabel-not-HasText — super.setText's HasText branch misses them,
        // so we route the label through HasLabel here after chaining up for
        // the PCE. Button is not HasLabel, so bare JToggleButton skips this
        // branch (already rendered by super). Null normalises to "".
        super.setText(newText);
        if (getPeer() instanceof com.vaadin.flow.component.HasLabel hl) {
            withPeer(p -> hl.setLabel(newText != null ? newText : ""));
        }
    }

    public java.lang.Object[] getSelectedObjects() {
        // ItemSelectable: when selected, return an array containing
        // the button's text (matches JDK AbstractButton). When not
        // selected, null — AbstractButton's base getSelectedObjects
        // would always return null since it doesn't know about
        // selection; we override to honour the real contract.
        if (!selected) return null;
        return new java.lang.Object[] { getText() };
    }

    public java.lang.String getUIClassID() {
        return "ToggleButtonUI";
    }

    public void updateUI() {
        // L&F swap — same rationale as JButton.updateUI. Vaadin owns
        // the DOM; there's no pluggable UI.
    }

    protected java.lang.String paramString() {
        // JDK JToggleButton.paramString is essentially empty (returns
        // AbstractButton's). Chain so the toString shape matches.
        return super.paramString();
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JToggleButton", "getAccessibleContext");
        return null;
    }
}
