/*
 * Copyright (c) 1997, 2021, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * Copyright 2000-2026 Vaadin Ltd.
 * SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
 *
 * This file is derived from OpenJDK's javax.swing.JToggleButton
 * (https://github.com/openjdk/jdk, tag jdk-25-ga) and was modified by
 * Vaadin Ltd in 2026; see PROVENANCE.md at the root of
 * https://github.com/vaadin/swingbridge-emulators for how and why, and the
 * repository history for each change. Vaadin Ltd licenses its modifications
 * under the same GNU General Public License version 2 only and extends the
 * "Classpath" exception, as set out in the LICENSE file that accompanied
 * this code, to its version of this file.
 */

package vaadinx.swing;

// Generated by vaadinx.internal.Generator from javax.swing.JToggleButton
// Hand-finished. The emulator owns the ToggleButtonModel, as the JDK's
// JToggleButton does, and hands the same instance to its surrogate: a
// browser click pulses the model through the surrogate, setSelected and
// doClick reach it directly, and every Item / Change / Action event reaches
// this button's listeners through AbstractButton's Handler.
//
// The peer is SJToggleButton (a Vaadin Button, SD_sjtogglebutton_button_peer),
// or the glyph peer a subclass passes — SJCheckBox (Checkbox) for JCheckBox,
// SJRadioButton (VaadinRadioButton) for JRadioButton, per D_jradiobutton.
// setText additionally routes the label through HasLabel for those glyph
// peers, which are HasLabel-not-HasText (see setText below).

/** Emulator for {@link javax.swing.JToggleButton}, rendered by {@link com.vaadin.swingbridge.surrogates.SJToggleButton} (Button peer, SD_sjtogglebutton_button_peer). */
public class JToggleButton extends vaadinx.swing.AbstractButton implements javax.accessibility.Accessible {

    public JToggleButton() {
        this(null, null, false);
    }

    public JToggleButton(vaadinx.swing.Icon icon) {
        this(null, icon, false);
    }

    public JToggleButton(vaadinx.swing.Icon icon, boolean selected) {
        this(null, icon, selected);
    }

    public JToggleButton(java.lang.String text) {
        this(text, null, false);
    }

    public JToggleButton(java.lang.String text, boolean selected) {
        this(text, null, selected);
    }

    public JToggleButton(java.lang.String text, vaadinx.swing.Icon icon) {
        this(text, icon, false);
    }

    public JToggleButton(javax.swing.Action action) {
        this();
        setAction(action);
    }

    public JToggleButton(java.lang.String text, vaadinx.swing.Icon icon, boolean selected) {
        this(com.vaadin.swingbridge.surrogates.SJToggleButton.class, com.vaadin.swingbridge.surrogates.SJToggleButton::new);
        initToggle(text, icon, selected);
    }

    /** Peers on {@code peer}, built by the caller, over a fresh {@link ToggleButtonModel}. */
    protected JToggleButton(com.vaadin.flow.component.Component peer) {
        super(peer);
        setModel(new ToggleButtonModel());
    }

    /** The lazy form: see {@link vaadinx.awt.Component#Component(Class, java.util.function.Supplier)}. */
    protected <P extends com.vaadin.flow.component.Component> JToggleButton(Class<P> peerType,
            java.util.function.Supplier<? extends P> peerFactory) {
        super(peerType, peerFactory);
        setModel(new ToggleButtonModel());
    }

    /** The rest of the JDK's root constructor, after its {@code setModel}. */
    final void initToggle(java.lang.String text, vaadinx.swing.Icon icon, boolean selected) {
        model.setSelected(selected);
        init(text, icon);
    }

    /**
     * The JDK's {@code JToggleButton.ToggleButtonModel}: a release while armed flips the
     * selection, and a selection change fires {@code ChangeEvent} before {@code ItemEvent}.
     *
     * <p>Extends the JDK class and adds one thing: membership of a {@link vaadinx.swing.ButtonGroup}.
     * The JDK keeps the group on the model as a {@code javax.swing.ButtonGroup}, which this
     * group is not, so the inherited {@code getGroup()} stays {@code null} and the group is
     * consulted here instead, exactly where the JDK's {@code setSelected} consults its own.
     */
    public static class ToggleButtonModel extends javax.swing.JToggleButton.ToggleButtonModel {

        /** Set by {@link vaadinx.swing.ButtonGroup#add} / {@code remove}. */
        transient vaadinx.swing.ButtonGroup buttonGroup;

        public ToggleButtonModel() {
        }

        /**
         * Lets the group veto or redirect the change first: selecting deselects the group's
         * previous selection, and deselecting the group's selection does nothing.
         */
        @Override
        public void setSelected(boolean b) {
            vaadinx.swing.ButtonGroup group = buttonGroup;
            if (group != null) {
                group.setSelected(this, b);
                b = group.isSelected(this);
            }
            super.setSelected(b);
        }
    }

    public void setText(java.lang.String newText) {
        // AbstractButton.setText pushes into HasText peers and fires PCE.
        // The default peer SJToggleButton is a Button (HasText), so
        // super.setText renders it. The glyph subclasses' peers (SJCheckBox
        // → Checkbox, SJRadioButton → VaadinRadioButton per D_jradiobutton) are
        // HasLabel-not-HasText — super.setText's HasText branch misses them,
        // so we route the label through HasLabel here after chaining up for
        // the PCE. Button is not HasLabel, so bare JToggleButton skips this
        // branch (already rendered by super). Null normalises to "".
        super.setText(newText);
        withPeer(p -> {
            if (p instanceof com.vaadin.flow.component.HasLabel hl) hl.setLabel(newText != null ? newText : "");
        });
    }

    public java.lang.String getUIClassID() {
        return "ToggleButtonUI";
    }

    public void updateUI() {
        // L&F swap — same rationale as JButton.updateUI. Vaadin owns
        // the DOM; there's no pluggable UI.
    }

    protected java.lang.String paramString() {
        // JDK JToggleButton.paramString is essentially empty (returns
        // AbstractButton's). Chain so the toString shape matches.
        return super.paramString();
    }

    public javax.accessibility.AccessibleContext getAccessibleContext() {
        vaadinx.EHelper.onUnimplemented("JToggleButton", "getAccessibleContext");
        return null;
    }
}
